<a href="https://colab.research.google.com/github/jgte29/ucbhonorsthesis2023-2024/blob/main/SF_DA_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install firebase-admin

# Load in Data & Libraries

In [3]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from scipy import stats
import warnings
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.diagnostic import linear_lm
import sklearn
from sklearn.model_selection import train_test_split
from datetime import datetime
# Initialize the Firebase app with your service account key
cred = credentials.Certificate(r'PRIVATE-KEY-sf-da-analysis-firebase.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://sf-da-analysis-6f156-default-rtdb.firebaseio.com/'
})

In [4]:
# For sf_prosecutions
# Get a reference to the Firebase Realtime Database
ref = db.reference('/District_Attorney_Cases_Prosecuted_2014_2023')

# Load data from the collection
sf_prosecutions = ref.get()

# Process the loaded data & converts it to a df
sf_prosecutions = pd.json_normalize(sf_prosecutions)
sf_prosecutions = sf_prosecutions.drop('id', axis=1)

# For sf_case_resolutions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_All_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_all = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_all = pd.json_normalize(sf_case_resolutions_all)
sf_case_resolutions_all = sf_case_resolutions_all.drop('id', axis=1)

# For sf_case_resolutions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_Violent_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_violent = pd.json_normalize(sf_case_resolutions_violent)
sf_case_resolutions_violent = sf_case_resolutions_violent.drop('id', axis=1)

# For sf_da_actions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_All_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_all = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_all = pd.json_normalize(sf_da_actions_all)
sf_da_actions_all = sf_da_actions_all.drop('id', axis=1)

# For sf_da_actions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_Violent_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_violent = pd.json_normalize(sf_da_actions_violent)
sf_da_actions_violent = sf_da_actions_violent.drop('id', axis=1)

# For sfpd_incidents_outcomes_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Outcomes_of_SFPD_Incidents_All_Crimes_2015_2023')

# Load data from the collection
sfpd_incidents_outcomes_all = ref.get()

# Process the loaded data & converts it to a df
sfpd_incidents_outcomes_all = pd.json_normalize(sfpd_incidents_outcomes_all)
sfpd_incidents_outcomes_all = sfpd_incidents_outcomes_all.drop('id', axis=1)

# For fed_off_by_crime_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_all = pd.json_normalize(fed_off_by_crime_all)
fed_off_by_crime_all = fed_off_by_crime_all.drop('id', axis=1)

# For fed_off_by_crime_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_violent = pd.json_normalize(fed_off_by_crime_violent)
fed_off_by_crime_violent = fed_off_by_crime_violent.drop('id', axis=1)

# For fed_off_by_dist_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_all = pd.json_normalize(fed_off_by_dist_all)
fed_off_by_dist_all = fed_off_by_dist_all.drop('id', axis=1)

# For fed_off_by_dist_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_violent = pd.json_normalize(fed_off_by_dist_violent)
fed_off_by_dist_violent = fed_off_by_dist_violent.drop('id', axis=1)

In [5]:
fed_off_by_dist_all

          Circuit              District  Fiscal_Year      N    Pct
0     Grand Total                 Total         2022  64157  1.000
1      DC Circuit  District of Columbia         2022    312  0.005
2     1st Circuit                 Maine         2022    180  0.003
3     1st Circuit         Massachusetts         2022    466  0.007
4     1st Circuit         New Hampshire         2022    180  0.003
..            ...                   ...          ...    ...    ...
755  11th Circuit     Florida, Northern         2015    255  0.004
756  11th Circuit     Florida, Southern         2015   2238  0.032
757  11th Circuit       Georgia, Middle         2015    377  0.005
758  11th Circuit     Georgia, Northern         2015    592  0.008
759  11th Circuit     Georgia, Southern         2015    420  0.006

[760 rows x 5 columns]

In [6]:
date_format = "%Y-%m-%dT%H:%M:%S.%fZ"

sf_prosecutions['arrest_date'] = pd.to_datetime(sf_prosecutions['arrest_date'], format = date_format)
sf_prosecutions['data_as_of'] = pd.to_datetime(sf_prosecutions['data_as_of'], format = date_format)
sf_prosecutions['data_loaded_at'] = pd.to_datetime(sf_prosecutions['data_loaded_at'], format = date_format)

In [7]:
boudin_start_date = datetime(2020, 1, 8, 0, 0, 0)
boudin_end_date = datetime(2022, 7, 9, 0, 0, 0)
sf_prosecutions_boudin = sf_prosecutions[(sf_prosecutions["arrest_date"] >= boudin_start_date) &
                                         (sf_prosecutions["arrest_date"] < boudin_end_date)]

sf_prosecutions_boudin

,arrest_date,case_status,court_number,crime_type,da_action_taken,data_as_of,data_loaded_at,dv_case,filed_case_type,incident_number,list_of_filed_charges
9383,2020-01-09 08:00:00,Filed Motion to Revoke,2506152,"Forgery, Checks, Access Cards",New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20171107-02506152,470D/F/0
9384,2020-01-30 08:00:00,Filed Motion to Revoke,2520522,Theft,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20200115-02520522,"487C/F/0, 245A4/M/0"
9385,2020-01-14 08:00:00,Filed Motion to Revoke,14005420,Assault,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,Yes,MTR,140153084,"591.5/M/0, 273.5A/F/0, 273.5A/F/0, 273.5A/F/0,..."
9386,2020-01-22 08:00:00,Filed Motion to Revoke,15018930,Robbery,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150735638,"242/M/0, 245A4/F/0, 243B/M/0, 211/F/2"
9387,2020-01-16 08:00:00,Filed Motion to Revoke,15026261,Narcotics,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150025953,"11378/F/0, 11377/M/0, 23123A/I/0"
...,...,...,...,...,...,...,...,...,...,...,...
99090,2022-06-24 07:00:00,,2530936,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,23-00344,
99091,2022-06-13 07:00:00,Pending,2530799,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,Z20220613-02530799,
99092,2022-07-06 07:00:00,Fugitive Status,22006648,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,Felony,220445185,"664/1085A/F/0, 664/496DA/F/0"
99096,2022-07-04 07:00:00,Pled Guilty to Other Case or Other DA Action,22006556,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220438726,
99097,2022-07-04 07:00:00,,22006565,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220437825,

# PART I - Boudin v National Trends (DID)

## All Crimes

In [ ]:
def year_marker(year, start, end=9999, mode = 'range'):
  # Default of 9999 is used to indicate ongoing
  if mode == 'before':
    try:
      if year < start:
        return 1
      else:
        return 0
    except:
      return 0

  if mode == 'after':
    start += 1 #Increments start by 1

  # Used for both 'after' and 'range' modes
  else:
    try:
      if year >= start and year <= end:
        return 1
      else:
        return 0
    except:
      return 0

In [ ]:
fed_off_totals_all = fed_off_by_dist_all[fed_off_by_dist_all["District"] == "Total"].reset_index(drop=True)
fed_off_totals_all = fed_off_totals_all.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_all.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_all.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_all['Log_Total'] = np.log(fed_off_totals_all['Total'])
fed_off_totals_all['Boudin'] = 0
fed_off_totals_all['SF'] = 0
fed_off_totals_all['Before_COVID'] = fed_off_totals_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_all

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022  64157  11.069088       0   0             0
1  2021  57304  10.956126       0   0             0
2  2020  64591  11.075830       0   0             0
3  2019  76593  11.246261       0   0             1
4  2018  69470  11.148650       0   0             1
5  2017  66899  11.110939       0   0             1
6  2016  67794  11.124229       0   0             1
7  2015  71030  11.170858       0   0             1

In [ ]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions = sf_case_resolutions_all[["Year", "Conviction"]]
sfda_convictions["Conviction"] = sfda_convictions["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions['Log_Total'] = np.log(sfda_convictions['Total'])
sfda_convictions['Boudin'] = sfda_convictions.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions['SF'] = 1
sfda_convictions['Before_COVID'] = sfda_convictions.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_proj = sfda_convictions.copy() #Creates defensive copy
sfda_convictions_proj.iloc[8, 1] = sfda_convictions_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_proj = sfda_convictions_proj.drop(9)

# Drops '2023*' Row
sfda_convictions = sfda_convictions.drop(9)

sfda_convictions["Year"] = sfda_convictions["Year"].astype(int)
sfda_convictions_proj["Year"] = sfda_convictions_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

In [ ]:
# Concatenate vertically (along rows)
sf_fed_off_totals = pd.concat([fed_off_totals_all, sfda_convictions], axis=0)
sf_fed_off_totals_proj = pd.concat([fed_off_totals_all, sfda_convictions_proj], axis=0)

# Reset the index
sf_fed_off_totals = sf_fed_off_totals.reset_index(drop=True)
sf_fed_off_totals_proj = sf_fed_off_totals_proj.reset_index(drop=True)

sf_fed_off_totals

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0
16  2023   1342   7.201916       0   1             0

### 2023 Inclusive

In [ ]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     395.2
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           5.06e-12
Time:                        23:55:35   Log-Likelihood:                -156.57
No. Observations:                  17   AIC:                             325.1
Df Residuals:                      11   BIC:                             330.1
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.588e+06   1.23e+06     -1.289      0.224    -4.3e+06    1.12e+06
Boudin        2.241e+06   4.47e+06      0.501      0.626    -7.6e+06    1.21e+07
Year           817.0633    609.820      1.340      0.207    -525.142    2159.268
SF           -6.592e+04   1691.337    -38.976      0.000   -6.96e+04   -6.22e+04
Before_COVID  1.016e+04   3355.503      3.029      0.011    2777.804    1.75e+04
Boudin:Year  -1106.5633   2211.710     -0.500      0.627   -5974.503    3761.377
==============================================================================
Omnibus:                        1.075   Durbin-Watson:                   1.893
Prob(Omnibus):                  0.584   Jarque-Bera (JB):                0.106
Skew:                          -0.081   Prob(JB):                        0.948
Kurtosis:                       3.351   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.991
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     244.3
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           6.96e-11
Time:                        23:55:35   Log-Likelihood:                 6.8828
No. Observations:                  17   AIC:                            -1.766
Df Residuals:                      11   BIC:                             3.234
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       67.9599     82.269      0.826      0.426    -113.113     249.033
Boudin         292.9657    298.328      0.982      0.347    -363.650     949.581
Year            -0.0282      0.041     -0.694      0.502      -0.118       0.061
SF              -3.2145      0.113    -28.477      0.000      -3.463      -2.966
Before_COVID     0.2379      0.224      1.062      0.311      -0.255       0.731
Boudin:Year     -0.1451      0.148     -0.983      0.347      -0.470       0.180
==============================================================================
Omnibus:                        4.041   Durbin-Watson:                   1.370
Prob(Omnibus):                  0.133   Jarque-Bera (JB):                2.186
Skew:                          -0.859   Prob(JB):                        0.335
Kurtosis:                       3.366   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     381.5
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           6.14e-12
Time:                        23:55:35   Log-Likelihood:                -156.85
No. Observations:                  17   AIC:                             325.7
Df Residuals:                      11   BIC:                             330.7
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.644e+06   1.25e+06     -1.312      0.216    -4.4e+06    1.11e+06
Boudin        2.297e+06   4.54e+06      0.505      0.623   -7.71e+06    1.23e+07
Year           844.8797    620.021      1.363      0.200    -519.777    2209.537
SF            -6.58e+04   1719.629    -38.264      0.000   -6.96e+04    -6.2e+04
Before_COVID  1.011e+04   3411.633      2.964      0.013    2602.338    1.76e+04
Boudin:Year  -1134.3797   2248.707     -0.504      0.624   -6083.750    3814.990
==============================================================================
Omnibus:                        1.003   Durbin-Watson:                   1.863
Prob(Omnibus):                  0.606   Jarque-Bera (JB):                0.088
Skew:                          -0.079   Prob(JB):                        0.957
Kurtosis:                       3.315   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.991
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     244.3
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           6.96e-11
Time:                        23:55:35   Log-Likelihood:                 6.8828
No. Observations:                  17   AIC:                            -1.766
Df Residuals:                      11   BIC:                             3.234
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       67.9599     82.269      0.826      0.426    -113.113     249.033
Boudin         292.9657    298.328      0.982      0.347    -363.650     949.581
Year            -0.0282      0.041     -0.694      0.502      -0.118       0.061
SF              -3.2145      0.113    -28.477      0.000      -3.463      -2.966
Before_COVID     0.2379      0.224      1.062      0.311      -0.255       0.731
Boudin:Year     -0.1451      0.148     -0.983      0.347      -0.470       0.180
==============================================================================
Omnibus:                        4.041   Durbin-Watson:                   1.370
Prob(Omnibus):                  0.133   Jarque-Bera (JB):                2.186
Skew:                          -0.859   Prob(JB):                        0.335
Kurtosis:                       3.366   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

### 2023 Exclusive

In [ ]:
# Drops '2023' Row
sf_fed_off_totals_no2023 = sf_fed_off_totals[sf_fed_off_totals["Year"] != 2023]
sf_fed_off_totals_no2023

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0

In [ ]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.995
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     393.9
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           3.84e-11
Time:                        23:55:35   Log-Likelihood:                -146.62
No. Observations:                  16   AIC:                             305.2
Df Residuals:                      10   BIC:                             309.9
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.092e+06   1.26e+06     -0.867      0.406    -3.9e+06    1.71e+06
Boudin        1.745e+06   4.36e+06      0.400      0.697   -7.97e+06    1.15e+07
Year           570.7727    622.964      0.916      0.381    -817.277    1958.822
SF           -6.701e+04   1848.009    -36.258      0.000   -7.11e+04   -6.29e+04
Before_COVID  1.062e+04   3280.679      3.238      0.009    3313.149    1.79e+04
Boudin:Year   -860.2727   2158.009     -0.399      0.699   -5668.617    3948.072
==============================================================================
Omnibus:                        0.783   Durbin-Watson:                   2.016
Prob(Omnibus):                  0.676   Jarque-Bera (JB):                0.042
Skew:                           0.088   Prob(JB):                        0.979
Kurtosis:                       3.179   Cond. No.                     1.23e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.23e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.998
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     858.8
Date:                Wed, 20 Sep 2023   Prob (F-statistic):           7.92e-13
Time:                        23:55:35   Log-Likelihood:                 17.576
No. Observations:                  16   AIC:                            -23.15
Df Residuals:                      10   BIC:                            -18.52
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -9.1745     43.966     -0.209      0.839    -107.136      88.787
Boudin         369.9318    152.302      2.429      0.036      30.583     709.281
Year             0.0100      0.022      0.460      0.656      -0.038       0.058
SF              -3.0463      0.065    -47.204      0.000      -3.190      -2.902
Before_COVID     0.1665      0.115      1.453      0.177      -0.089       0.422
Boudin:Year     -0.1834      0.075     -2.433      0.035      -0.351      -0.015
==============================================================================
Omnibus:                        4.008   Durbin-Watson:                   2.548
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                2.519
Skew:                          -0.972   Prob(JB):                        0.284
Kurtosis:                       2.992   Cond. No.                     1.23e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.23e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

## Violent Crimes

In [ ]:
fed_off_totals_violent = fed_off_by_dist_violent[fed_off_by_dist_violent["District"] == "Total"].reset_index(drop=True)
fed_off_totals_violent = fed_off_totals_violent.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_violent.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_violent.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_violent['Log_Total'] = np.log(fed_off_totals_violent['Total'])
fed_off_totals_violent['Boudin'] = 0
fed_off_totals_violent['SF'] = 0
fed_off_totals_violent['Before_COVID'] = fed_off_totals_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_violent

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022   4417   8.393216       0   0             0
1  2021   3438   8.142645       0   0             0
2  2020   3219   8.076826       0   0             0
3  2019   4326   8.372399       0   0             1
4  2018   3973   8.287277       0   0             1
5  2017   3927   8.275631       0   0             1
6  2016   3816   8.246958       0   0             1
7  2015   3835   8.251925       0   0             1

In [ ]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions_violent = sf_case_resolutions_violent[["Year", "Conviction"]]
sfda_convictions_violent["Conviction"] = sfda_convictions_violent["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions_violent.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions_violent['Log_Total'] = np.log(sfda_convictions_violent['Total'])
sfda_convictions_violent['Boudin'] = sfda_convictions_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions_violent['SF'] = 1
sfda_convictions_violent['Before_COVID'] = sfda_convictions_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_violent_proj = sfda_convictions_violent.copy() #Creates defensive copy
sfda_convictions_violent_proj.iloc[8, 1] = sfda_convictions_violent_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_violent_proj = sfda_convictions_violent_proj.drop(9)

# Drops '2023*' Row
sfda_convictions_violent = sfda_convictions_violent.drop(9)

sfda_convictions_violent["Year"] = sfda_convictions_violent["Year"].astype(int)
sfda_convictions_violent_proj["Year"] = sfda_convictions_violent_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
# Concatenate vertically (along rows)
sf_fed_off_totals_violent = pd.concat([fed_off_totals_violent, sfda_convictions_violent], axis=0)
sf_fed_off_totals_violent_proj = pd.concat([fed_off_totals_violent, sfda_convictions_violent_proj], axis=0)

# Reset the index
sf_fed_off_totals_violent = sf_fed_off_totals_violent.reset_index(drop=True)
sf_fed_off_totals_violent_proj = sf_fed_off_totals_violent_proj.reset_index(drop=True)

sf_fed_off_totals_violent

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0
16  2023    397   5.983936       0   1             0

### 2023 Inclusive

In [ ]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.969
Method:                 Least Squares   F-statistic:                     101.8
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           7.89e-09
Time:                        01:18:56   Log-Likelihood:                -116.56
No. Observations:                  17   AIC:                             245.1
Df Residuals:                      11   BIC:                             250.1
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.711e+05   1.17e+05     -1.460      0.172   -4.29e+05    8.68e+04
Boudin        3.172e+05   4.25e+05      0.747      0.471   -6.18e+05    1.25e+06
Year            86.4177     57.952      1.491      0.164     -41.134     213.969
SF           -3095.9620    160.730    -19.262      0.000   -3449.726   -2742.198
Before_COVID   778.2203    318.878      2.440      0.033      76.375    1480.065
Boudin:Year   -156.9177    210.182     -0.747      0.471    -619.524     305.689
==============================================================================
Omnibus:                       17.479   Durbin-Watson:                   1.520
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.270
Skew:                           1.740   Prob(JB):                     0.000178
Kurtosis:                       6.503   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.960
Model:                            GLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     52.82
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           2.56e-07
Time:                        01:18:57   Log-Likelihood:                 5.3307
No. Observations:                  17   AIC:                             1.339
Df Residuals:                      11   BIC:                             6.338
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.2685     90.134      0.314      0.760    -170.114     226.651
Boudin         233.2816    326.846      0.714      0.490    -486.102     952.666
Year            -0.0100      0.045     -0.224      0.827      -0.108       0.088
SF              -1.5781      0.124    -12.760      0.000      -1.850      -1.306
Before_COVID     0.2915      0.245      1.188      0.260      -0.249       0.831
Boudin:Year     -0.1155      0.162     -0.714      0.490      -0.471       0.240
==============================================================================
Omnibus:                        4.033   Durbin-Watson:                   1.217
Prob(Omnibus):                  0.133   Jarque-Bera (JB):                1.759
Skew:                          -0.582   Prob(JB):                        0.415
Kurtosis:                       4.062   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.980
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     110.5
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           5.10e-09
Time:                        01:18:57   Log-Likelihood:                -115.76
No. Observations:                  17   AIC:                             243.5
Df Residuals:                      11   BIC:                             248.5
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.876e+05   1.12e+05     -1.679      0.121   -4.34e+05    5.84e+04
Boudin        3.337e+05   4.05e+05      0.823      0.428   -5.58e+05    1.23e+06
Year            94.6297     55.287      1.712      0.115     -27.055     216.315
SF           -3059.8291    153.338    -19.955      0.000   -3397.323   -2722.335
Before_COVID   762.8911    304.212      2.508      0.029      93.325    1432.457
Boudin:Year   -165.1297    200.515     -0.824      0.428    -606.460     276.201
==============================================================================
Omnibus:                       17.043   Durbin-Watson:                   1.599
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               16.447
Skew:                           1.716   Prob(JB):                     0.000268
Kurtosis:                       6.383   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.960
Model:                            GLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     52.82
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           2.56e-07
Time:                        01:18:57   Log-Likelihood:                 5.3307
No. Observations:                  17   AIC:                             1.339
Df Residuals:                      11   BIC:                             6.338
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.2685     90.134      0.314      0.760    -170.114     226.651
Boudin         233.2816    326.846      0.714      0.490    -486.102     952.666
Year            -0.0100      0.045     -0.224      0.827      -0.108       0.088
SF              -1.5781      0.124    -12.760      0.000      -1.850      -1.306
Before_COVID     0.2915      0.245      1.188      0.260      -0.249       0.831
Boudin:Year     -0.1155      0.162     -0.714      0.490      -0.471       0.240
==============================================================================
Omnibus:                        4.033   Durbin-Watson:                   1.217
Prob(Omnibus):                  0.133   Jarque-Bera (JB):                1.759
Skew:                          -0.582   Prob(JB):                        0.415
Kurtosis:                       4.062   Cond. No.                     1.26e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.26e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [ ]:
# Drops '2023' Row
sf_fed_off_totals_violent_no2023 = sf_fed_off_totals_violent[sf_fed_off_totals_violent["Year"] != 2023]
sf_fed_off_totals_violent_no2023

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0

In [ ]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.981
Model:                            GLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     101.8
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           3.04e-08
Time:                        01:18:57   Log-Likelihood:                -108.74
No. Observations:                  16   AIC:                             229.5
Df Residuals:                      10   BIC:                             234.1
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.221e+05   1.18e+05     -1.883      0.089   -4.85e+05    4.07e+04
Boudin        3.681e+05   4.09e+05      0.901      0.389   -5.42e+05    1.28e+06
Year           111.7273     58.370      1.914      0.085     -18.329     241.784
SF           -2984.6000    173.153    -17.237      0.000   -3370.409   -2598.791
Before_COVID   730.9758    307.390      2.378      0.039      46.067    1415.884
Boudin:Year   -182.2273    202.199     -0.901      0.389    -632.756     268.301
==============================================================================
Omnibus:                        9.074   Durbin-Watson:                   1.681
Prob(Omnibus):                  0.011   Jarque-Bera (JB):                5.683
Skew:                           1.135   Prob(JB):                       0.0583
Kurtosis:                       4.837   Cond. No.                     1.23e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.23e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + SF + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.985
Method:                 Least Squares   F-statistic:                     194.6
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           1.26e-09
Time:                        01:18:57   Log-Likelihood:                 16.810
No. Observations:                  16   AIC:                            -21.62
Df Residuals:                      10   BIC:                            -16.98
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -57.3137     46.120     -1.243      0.242    -160.076      45.448
Boudin         318.6771    159.765      1.995      0.074     -37.301     674.655
Year             0.0324      0.023      1.421      0.186      -0.018       0.083
SF              -1.3914      0.068    -20.554      0.000      -1.542      -1.241
Before_COVID     0.2123      0.120      1.766      0.108      -0.055       0.480
Boudin:Year     -0.1580      0.079     -1.998      0.074      -0.334       0.018
==============================================================================
Omnibus:                        0.125   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.939   Jarque-Bera (JB):                0.239
Skew:                          -0.170   Prob(JB):                        0.887
Kurtosis:                       2.508   Cond. No.                     1.23e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.23e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# PART II - SF Before & After Boudin Takes Office (RDD)

## All Crimes

### 2023 Inclusive

In [ ]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_all = sf_case_resolutions_all.copy()
sf_cr_all["Conviction"] = sf_cr_all["Conviction"].astype(int)

sf_cr_all['Log_Conviction'] = np.log(sf_cr_all['Conviction'])
sf_cr_all['Log_Total'] = np.log(sf_cr_all['Total'])
sf_cr_all['Boudin'] = sf_cr_all.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_all['Before_COVID'] = sf_cr_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_all_proj = sf_cr_all.copy() #Creates defensive copy
sf_cr_all_proj.iloc[8, 1] = sf_cr_all_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_all_proj = sf_cr_all_proj.drop(9)

# Drops '2023*' Row
sf_cr_all = sf_cr_all.drop(9)

# Addresses type issues
sf_cr_all["Year"] = sf_cr_all["Year"].astype(int)
sf_cr_all["Med_Arrest_To_Close"] = sf_cr_all["Med_Arrest_To_Close"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Conviction"] = sf_cr_all["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Dismissal"] = sf_cr_all["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_all_proj["Year"] = sf_cr_all_proj["Year"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close"] = sf_cr_all_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_all_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_all_no2023 = sf_cr_all[sf_cr_all["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [ ]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.880
Model:                            GLS   Adj. R-squared:                  0.809
Method:                 Least Squares   F-statistic:                     12.26
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00965
Time:                        01:24:21   Log-Likelihood:                 11.177
No. Observations:                   9   AIC:                            -14.35
Df Residuals:                       5   BIC:                            -13.57
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -84.9060     54.757     -1.551      0.182    -225.664      55.852
Boudin           0.2475      0.121      2.044      0.096      -0.064       0.559
Year             0.0460      0.027      1.701      0.150      -0.024       0.116
Before_COVID     0.7476      0.192      3.891      0.012       0.254       1.242
==============================================================================
Omnibus:                        0.472   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.790   Jarque-Bera (JB):                0.248
Skew:                           0.333   Prob(JB):                        0.883
Kurtosis:                       2.533   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.880
Model:                            GLS   Adj. R-squared:                  0.809
Method:                 Least Squares   F-statistic:                     12.26
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00965
Time:                        01:24:21   Log-Likelihood:                 11.177
No. Observations:                   9   AIC:                            -14.35
Df Residuals:                       5   BIC:                            -13.57
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -84.9060     54.757     -1.551      0.182    -225.664      55.852
Boudin           0.2475      0.121      2.044      0.096      -0.064       0.559
Year             0.0460      0.027      1.701      0.150      -0.024       0.116
Before_COVID     0.7476      0.192      3.891      0.012       0.254       1.242
==============================================================================
Omnibus:                        0.472   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.790   Jarque-Bera (JB):                0.248
Skew:                           0.333   Prob(JB):                        0.883
Kurtosis:                       2.533   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.916
Model:                            GLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     18.23
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00401
Time:                        01:24:22   Log-Likelihood:                 6.0050
No. Observations:                   9   AIC:                            -4.010
Df Residuals:                       5   BIC:                            -3.221
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       56.9768     97.283      0.586      0.584    -193.096     307.050
Boudin           0.0716      0.215      0.333      0.753      -0.481       0.624
Year            -0.0246      0.048     -0.512      0.631      -0.148       0.099
Before_COVID     0.7644      0.341      2.239      0.075      -0.113       1.642
==============================================================================
Omnibus:                        0.553   Durbin-Watson:                   2.080
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.256
Skew:                           0.353   Prob(JB):                        0.880
Kurtosis:                       2.571   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.916
Model:                            GLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     18.23
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00401
Time:                        01:24:22   Log-Likelihood:                 6.0050
No. Observations:                   9   AIC:                            -4.010
Df Residuals:                       5   BIC:                            -3.221
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       56.9768     97.283      0.586      0.584    -193.096     307.050
Boudin           0.0716      0.215      0.333      0.753      -0.481       0.624
Year            -0.0246      0.048     -0.512      0.631      -0.148       0.099
Before_COVID     0.7644      0.341      2.239      0.075      -0.113       1.642
==============================================================================
Omnibus:                        0.553   Durbin-Watson:                   2.080
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.256
Skew:                           0.353   Prob(JB):                        0.880
Kurtosis:                       2.571   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.913
Model:                              GLS   Adj. R-squared:                  0.861
Method:                   Least Squares   F-statistic:                     17.52
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00439
Time:                          01:24:22   Log-Likelihood:                -55.955
No. Observations:                     9   AIC:                             119.9
Df Residuals:                         5   BIC:                             120.7
Df Model:                             3
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.254e+05    9.5e+04     -3.424      0.019    -5.7e+05   -8.11e+04
Boudin         599.8333    210.093      2.855      0.036      59.772    1139.894
Year           161.4167     46.978      3.436      0.019      40.655     282.178
Before_COVID   498.1000    333.512      1.493      0.196    -359.220    1355.420
==============================================================================
Omnibus:                        0.211   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.900   Jarque-Bera (JB):                0.376
Skew:                           0.154   Prob(JB):                        0.828
Kurtosis:                       2.047   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.913
Model:                              GLS   Adj. R-squared:                  0.861
Method:                   Least Squares   F-statistic:                     17.52
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00439
Time:                          01:24:22   Log-Likelihood:                -55.955
No. Observations:                     9   AIC:                             119.9
Df Residuals:                         5   BIC:                             120.7
Df Model:                             3
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.254e+05    9.5e+04     -3.424      0.019    -5.7e+05   -8.11e+04
Boudin         599.8333    210.093      2.855      0.036      59.772    1139.894
Year           161.4167     46.978      3.436      0.019      40.655     282.178
Before_COVID   498.1000    333.512      1.493      0.196    -359.220    1355.420
==============================================================================
Omnibus:                        0.211   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.900   Jarque-Bera (JB):                0.376
Skew:                           0.154   Prob(JB):                        0.828
Kurtosis:                       2.047   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.963
Model:                             GLS   Adj. R-squared:                  0.941
Method:                  Least Squares   F-statistic:                     43.63
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):           0.000522
Time:                         01:24:22   Log-Likelihood:                -39.339
No. Observations:                    9   AIC:                             86.68
Df Residuals:                        5   BIC:                             87.47
Df Model:                            3
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.058e+04    1.5e+04     -2.705      0.043   -7.91e+04   -2015.494
Boudin          33.8333     33.162      1.020      0.354     -51.412     119.078
Year            20.2500      7.415      2.731      0.041       1.189      39.311
Before_COVID   -74.9000     52.643     -1.423      0.214    -210.222      60.422
==============================================================================
Omnibus:                        2.843   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.241   Jarque-Bera (JB):                0.254
Skew:                          -0.067   Prob(JB):                        0.881
Kurtosis:                       3.813   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.963
Model:                             GLS   Adj. R-squared:                  0.941
Method:                  Least Squares   F-statistic:                     43.63
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):           0.000522
Time:                         01:24:22   Log-Likelihood:                -39.339
No. Observations:                    9   AIC:                             86.68
Df Residuals:                        5   BIC:                             87.47
Df Model:                            3
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.058e+04    1.5e+04     -2.705      0.043   -7.91e+04   -2015.494
Boudin          33.8333     33.162      1.020      0.354     -51.412     119.078
Year            20.2500      7.415      2.731      0.041       1.189      39.311
Before_COVID   -74.9000     52.643     -1.423      0.214    -210.222      60.422
==============================================================================
Omnibus:                        2.843   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.241   Jarque-Bera (JB):                0.254
Skew:                          -0.067   Prob(JB):                        0.881
Kurtosis:                       3.813   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.993
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     242.1
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           7.85e-06
Time:                                    01:24:22   Log-Likelihood:                -28.819
No. Observations:                               9   AIC:                             65.64
Df Residuals:                                   5   BIC:                             66.43
Df Model:                                       3
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.104e+04   4660.719     -6.661      0.001    -4.3e+04   -1.91e+04
Boudin          26.3333     10.303      2.556      0.051      -0.152      52.819
Year            15.5000      2.304      6.728      0.001       9.578      21.422
Before_COVID   -50.2000     16.356     -3.069      0.028     -92.244      -8.156
==============================================================================
Omnibus:                        1.206   Durbin-Watson:                   1.764
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.710
Skew:                           0.625   Prob(JB):                        0.701
Kurtosis:                       2.425   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.993
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     242.1
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           7.85e-06
Time:                                    01:24:22   Log-Likelihood:                -28.819
No. Observations:                               9   AIC:                             65.64
Df Residuals:                                   5   BIC:                             66.43
Df Model:                                       3
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.104e+04   4660.719     -6.661      0.001    -4.3e+04   -1.91e+04
Boudin          26.3333     10.303      2.556      0.051      -0.152      52.819
Year            15.5000      2.304      6.728      0.001       9.578      21.422
Before_COVID   -50.2000     16.356     -3.069      0.028     -92.244      -8.156
==============================================================================
Omnibus:                        1.206   Durbin-Watson:                   1.764
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.710
Skew:                           0.625   Prob(JB):                        0.701
Kurtosis:                       2.425   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.927
Model:                                       GLS   Adj. R-squared:                  0.883
Method:                            Least Squares   F-statistic:                     21.18
Date:                           Thu, 21 Sep 2023   Prob (F-statistic):            0.00285
Time:                                   01:24:22   Log-Likelihood:                -38.402
No. Observations:                              9   AIC:                             84.80
Df Residuals:                                  5   BIC:                             85.59
Df Model:                                      3
Covariance Type:                       nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.195e+04   1.35e+04     -0.884      0.417   -4.67e+04    2.28e+04
Boudin         -65.8333     29.882     -2.203      0.079    -142.646      10.980
Year             6.0833      6.682      0.910      0.404     -11.093      23.259
Before_COVID  -136.3000     47.435     -2.873      0.035    -258.237     -14.363
==============================================================================
Omnibus:                        0.572   Durbin-Watson:                   2.046
Prob(Omnibus):                  0.751   Jarque-Bera (JB):                0.502
Skew:                          -0.003   Prob(JB):                        0.778
Kurtosis:                       1.843   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.999
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     425.7
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00235
Time:                        01:24:22   Log-Likelihood:                 33.812
No. Observations:                   9   AIC:                            -53.62
Df Residuals:                       2   BIC:                            -52.24
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -365.0293     22.457    -16.255      0.004    -461.654    -268.405
Boudin                             0.4844      0.029     16.924      0.003       0.361       0.608
Year                               0.1859      0.011     16.585      0.004       0.138       0.234
Before_COVID                       0.2739      0.056      4.861      0.040       0.031       0.516
Med_Arrest_To_Close               -0.0024      0.000     -8.881      0.012      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0059      0.001     -7.635      0.017      -0.009      -0.003
Med_Arrest_To_Close_Dismissal   9.208e-06      0.000      0.036      0.975      -0.001       0.001
==============================================================================
Omnibus:                        1.466   Durbin-Watson:                   2.441
Prob(Omnibus):                  0.480   Jarque-Bera (JB):                0.614
Skew:                           0.621   Prob(JB):                        0.735
Kurtosis:                       2.687   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.999
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     425.7
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00235
Time:                        01:24:22   Log-Likelihood:                 33.812
No. Observations:                   9   AIC:                            -53.62
Df Residuals:                       2   BIC:                            -52.24
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -365.0293     22.457    -16.255      0.004    -461.654    -268.405
Boudin                             0.4844      0.029     16.924      0.003       0.361       0.608
Year                               0.1859      0.011     16.585      0.004       0.138       0.234
Before_COVID                       0.2739      0.056      4.861      0.040       0.031       0.516
Med_Arrest_To_Close               -0.0024      0.000     -8.881      0.012      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0059      0.001     -7.635      0.017      -0.009      -0.003
Med_Arrest_To_Close_Dismissal   9.208e-06      0.000      0.036      0.975      -0.001       0.001
==============================================================================
Omnibus:                        1.466   Durbin-Watson:                   2.441
Prob(Omnibus):                  0.480   Jarque-Bera (JB):                0.614
Skew:                           0.621   Prob(JB):                        0.735
Kurtosis:                       2.687   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                     117.4
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00847
Time:                        01:24:22   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -28.50
Df Residuals:                       2   BIC:                            -27.12
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.8469     90.702     -4.276      0.051    -778.107       2.413
Boudin                             0.4843      0.116      4.190      0.053      -0.013       0.982
Year                               0.1974      0.045      4.361      0.049       0.003       0.392
Before_COVID                       0.0626      0.228      0.275      0.809      -0.916       1.042
Med_Arrest_To_Close               -0.0044      0.001     -4.114      0.054      -0.009       0.000
Med_Arrest_To_Close_Conviction    -0.0088      0.003     -2.784      0.108      -0.022       0.005
Med_Arrest_To_Close_Dismissal      0.0005      0.001      0.480      0.679      -0.004       0.005
==============================================================================
Omnibus:                        7.408   Durbin-Watson:                   3.048
Prob(Omnibus):                  0.025   Jarque-Bera (JB):                2.497
Skew:                           1.173   Prob(JB):                        0.287
Kurtosis:                       4.076   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                     117.4
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00847
Time:                        01:24:22   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -28.50
Df Residuals:                       2   BIC:                            -27.12
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.8469     90.702     -4.276      0.051    -778.107       2.413
Boudin                             0.4843      0.116      4.190      0.053      -0.013       0.982
Year                               0.1974      0.045      4.361      0.049       0.003       0.392
Before_COVID                       0.0626      0.228      0.275      0.809      -0.916       1.042
Med_Arrest_To_Close               -0.0044      0.001     -4.114      0.054      -0.009       0.000
Med_Arrest_To_Close_Conviction    -0.0088      0.003     -2.784      0.108      -0.022       0.005
Med_Arrest_To_Close_Dismissal      0.0005      0.001      0.480      0.679      -0.004       0.005
==============================================================================
Omnibus:                        7.408   Durbin-Watson:                   3.048
Prob(Omnibus):                  0.025   Jarque-Bera (JB):                2.497
Skew:                           1.173   Prob(JB):                        0.287
Kurtosis:                       4.076   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.829
Model:                            GLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     12.10
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0121
Time:                        01:24:27   Log-Likelihood:                 9.4643
No. Observations:                   8   AIC:                            -12.93
Df Residuals:                       5   BIC:                            -12.69
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -84.1583     54.595     -1.542      0.184    -224.499      56.182
Boudin        -0.5002      0.128     -3.905      0.011      -0.829      -0.171
Year           0.0460      0.027      1.701      0.150      -0.024       0.116
==============================================================================
Omnibus:                        0.282   Durbin-Watson:                   2.069
Prob(Omnibus):                  0.869   Jarque-Bera (JB):                0.318
Skew:                           0.314   Prob(JB):                        0.853
Kurtosis:                       2.251   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.895
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     21.28
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00358
Time:                        01:24:28   Log-Likelihood:                 4.8666
No. Observations:                   8   AIC:                            -3.733
Df Residuals:                       5   BIC:                            -3.495
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     57.7411     96.994      0.595      0.578    -191.590     307.072
Boudin        -0.6928      0.228     -3.044      0.029      -1.278      -0.108
Year          -0.0246      0.048     -0.512      0.631      -0.148       0.099
==============================================================================
Omnibus:                        0.324   Durbin-Watson:                   2.057
Prob(Omnibus):                  0.851   Jarque-Bera (JB):                0.318
Skew:                           0.333   Prob(JB):                        0.853
Kurtosis:                       2.285   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.911
Model:                              GLS   Adj. R-squared:                  0.876
Method:                   Least Squares   F-statistic:                     25.68
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00234
Time:                          01:24:28   Log-Likelihood:                -50.209
No. Observations:                     8   AIC:                             106.4
Df Residuals:                         5   BIC:                             106.7
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.249e+05   9.48e+04     -3.429      0.019   -5.69e+05   -8.14e+04
Boudin       101.7333    222.341      0.458      0.666    -469.814     673.280
Year         161.4167     46.978      3.436      0.019      40.655     282.178
==============================================================================
Omnibus:                        0.561   Durbin-Watson:                   1.687
Prob(Omnibus):                  0.756   Jarque-Bera (JB):                0.493
Skew:                           0.146   Prob(JB):                        0.782
Kurtosis:                       1.820   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.956
Model:                             GLS   Adj. R-squared:                  0.939
Method:                  Least Squares   F-statistic:                     54.88
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):           0.000396
Time:                         01:24:28   Log-Likelihood:                -35.439
No. Observations:                    8   AIC:                             76.88
Df Residuals:                        5   BIC:                             77.12
Df Model:                            2
Covariance Type:             nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.065e+04    1.5e+04     -2.718      0.042   -7.91e+04   -2204.808
Boudin       108.7333     35.095      3.098      0.027      18.518     198.948
Year          20.2500      7.415      2.731      0.041       1.189      39.311
==============================================================================
Omnibus:                        2.024   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.364   Jarque-Bera (JB):                0.056
Skew:                          -0.063   Prob(JB):                        0.972
Kurtosis:                       3.389   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.992
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     305.1
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           5.95e-06
Time:                                    01:24:28   Log-Likelihood:                -26.088
No. Observations:                               8   AIC:                             58.18
Df Residuals:                                   5   BIC:                             58.41
Df Model:                                       2
Covariance Type:                        nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.109e+04   4646.890     -6.692      0.001    -4.3e+04   -1.91e+04
Boudin        76.5333     10.904      7.019      0.001      48.504     104.563
Year          15.5000      2.304      6.728      0.001       9.578      21.422
==============================================================================
Omnibus:                        0.987   Durbin-Watson:                   1.710
Prob(Omnibus):                  0.610   Jarque-Bera (JB):                0.701
Skew:                           0.589   Prob(JB):                        0.704
Kurtosis:                       2.155   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.807
Model:                                       GLS   Adj. R-squared:                  0.742
Method:                            Least Squares   F-statistic:                     12.51
Date:                           Thu, 21 Sep 2023   Prob (F-statistic):            0.00724
Time:                                   01:24:28   Log-Likelihood:                -42.790
No. Observations:                              9   AIC:                             91.58
Df Residuals:                                  6   BIC:                             92.17
Df Model:                                      2
Covariance Type:                       nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.481e+04   1.07e+04     -4.182      0.006    -7.1e+04   -1.86e+04
Boudin        -0.9286     29.077     -0.032      0.976     -72.077      70.220
Year          22.3095      5.309      4.202      0.006       9.320      35.299
==============================================================================
Omnibus:                        0.411   Durbin-Watson:                   2.320
Prob(Omnibus):                  0.814   Jarque-Bera (JB):                0.475
Skew:                          -0.246   Prob(JB):                        0.789
Kurtosis:                       1.988   Cond. No.                     1.89e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.89e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                     59.24
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00338
Time:                        01:24:28   Log-Likelihood:                 22.334
No. Observations:                   9   AIC:                            -32.67
Df Residuals:                       3   BIC:                            -31.48
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -426.5880     54.207     -7.870      0.004    -599.098    -254.078
Boudin                             0.4582      0.082      5.577      0.011       0.197       0.720
Year                               0.2168      0.027      8.035      0.004       0.131       0.303
Med_Arrest_To_Close               -0.0027      0.001     -3.643      0.036      -0.005      -0.000
Med_Arrest_To_Close_Conviction    -0.0075      0.002     -3.653      0.035      -0.014      -0.001
Med_Arrest_To_Close_Dismissal     -0.0008      0.001     -1.491      0.233      -0.003       0.001
==============================================================================
Omnibus:                        1.552   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.460   Jarque-Bera (JB):                0.559
Skew:                           0.601   Prob(JB):                        0.756
Kurtosis:                       2.788   Cond. No.                     9.58e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.58e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     203.6
Date:                Thu, 21 Sep 2023   Prob (F-statistic):           0.000539
Time:                        01:24:28   Log-Likelihood:                 21.081
No. Observations:                   9   AIC:                            -30.16
Df Residuals:                       3   BIC:                            -28.98
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -401.9264     62.308     -6.451      0.008    -600.217    -203.636
Boudin                             0.4784      0.094      5.065      0.015       0.178       0.779
Year                               0.2045      0.031      6.593      0.007       0.106       0.303
Med_Arrest_To_Close               -0.0045      0.001     -5.243      0.014      -0.007      -0.002
Med_Arrest_To_Close_Conviction    -0.0091      0.002     -3.844      0.031      -0.017      -0.002
Med_Arrest_To_Close_Dismissal      0.0003      0.001      0.479      0.665      -0.002       0.002
==============================================================================
Omnibus:                        5.962   Durbin-Watson:                   2.974
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                2.014
Skew:                           1.107   Prob(JB):                        0.365
Kurtosis:                       3.682   Cond. No.                     9.58e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.58e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

### 2023 Inclusive

In [ ]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_violent = sf_case_resolutions_violent.copy()
sf_cr_violent["Conviction"] = sf_cr_violent["Conviction"].astype(int)

sf_cr_violent['Log_Conviction'] = np.log(sf_cr_violent['Conviction'])
sf_cr_violent['Log_Total'] = np.log(sf_cr_violent['Total'])
sf_cr_violent['Boudin'] = sf_cr_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_violent['Before_COVID'] = sf_cr_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_violent_proj = sf_cr_violent.copy() #Creates defensive copy
sf_cr_violent_proj.iloc[8, 1] = sf_cr_violent_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_violent_proj = sf_cr_violent_proj.drop(9)

# Drops '2023*' Row
sf_cr_violent = sf_cr_violent.drop(9)

# Addresses type issues
sf_cr_violent["Year"] = sf_cr_violent["Year"].astype(int)
sf_cr_violent["Med_Arrest_To_Close"] = sf_cr_violent["Med_Arrest_To_Close"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Conviction"] = sf_cr_violent["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_violent_proj["Year"] = sf_cr_violent_proj["Year"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close"] = sf_cr_violent_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_violent_no2023 = sf_cr_violent[sf_cr_violent["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [ ]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.833
Model:                            GLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     8.307
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0218
Time:                        01:26:44   Log-Likelihood:                 10.557
No. Observations:                   9   AIC:                            -13.11
Df Residuals:                       5   BIC:                            -12.32
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -103.5084     58.666     -1.764      0.138    -254.314      47.297
Boudin           0.2378      0.130      1.833      0.126      -0.096       0.571
Year             0.0546      0.029      1.884      0.118      -0.020       0.129
Before_COVID     0.7266      0.206      3.530      0.017       0.197       1.256
==============================================================================
Omnibus:                        1.157   Durbin-Watson:                   1.532
Prob(Omnibus):                  0.561   Jarque-Bera (JB):                0.853
Skew:                           0.597   Prob(JB):                        0.653
Kurtosis:                       2.079   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.833
Model:                            GLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     8.307
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0218
Time:                        01:27:09   Log-Likelihood:                 10.557
No. Observations:                   9   AIC:                            -13.11
Df Residuals:                       5   BIC:                            -12.32
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -103.5084     58.666     -1.764      0.138    -254.314      47.297
Boudin           0.2378      0.130      1.833      0.126      -0.096       0.571
Year             0.0546      0.029      1.884      0.118      -0.020       0.129
Before_COVID     0.7266      0.206      3.530      0.017       0.197       1.256
==============================================================================
Omnibus:                        1.157   Durbin-Watson:                   1.532
Prob(Omnibus):                  0.561   Jarque-Bera (JB):                0.853
Skew:                           0.597   Prob(JB):                        0.653
Kurtosis:                       2.079   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.874
Method:                 Least Squares   F-statistic:                     19.48
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00345
Time:                        01:27:36   Log-Likelihood:                 7.4034
No. Observations:                   9   AIC:                            -6.807
Df Residuals:                       5   BIC:                            -6.018
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.8333     83.283      0.346      0.743    -185.251     242.918
Boudin           0.2396      0.184      1.301      0.250      -0.234       0.713
Year            -0.0113      0.041     -0.274      0.795      -0.117       0.095
Before_COVID     0.8437      0.292      2.887      0.034       0.092       1.595
==============================================================================
Omnibus:                        0.166   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.920   Jarque-Bera (JB):                0.188
Skew:                           0.200   Prob(JB):                        0.910
Kurtosis:                       2.416   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.874
Method:                 Least Squares   F-statistic:                     19.48
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00345
Time:                        01:27:59   Log-Likelihood:                 7.4034
No. Observations:                   9   AIC:                            -6.807
Df Residuals:                       5   BIC:                            -6.018
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.8333     83.283      0.346      0.743    -185.251     242.918
Boudin           0.2396      0.184      1.301      0.250      -0.234       0.713
Year            -0.0113      0.041     -0.274      0.795      -0.117       0.095
Before_COVID     0.8437      0.292      2.887      0.034       0.092       1.595
==============================================================================
Omnibus:                        0.166   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.920   Jarque-Bera (JB):                0.188
Skew:                           0.200   Prob(JB):                        0.910
Kurtosis:                       2.416   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.939
Model:                              GLS   Adj. R-squared:                  0.903
Method:                   Least Squares   F-statistic:                     25.79
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00181
Time:                          01:28:11   Log-Likelihood:                -44.154
No. Observations:                     9   AIC:                             96.31
Df Residuals:                         5   BIC:                             97.10
Df Model:                             3
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.035e+05   2.56e+04     -4.039      0.010   -1.69e+05   -3.76e+04
Boudin         126.6667     56.620      2.237      0.075     -18.880     272.213
Year            51.3333     12.661      4.055      0.010      18.788      83.878
Before_COVID    96.8000     89.881      1.077      0.331    -134.248     327.848
==============================================================================
Omnibus:                        0.657   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.576
Skew:                           0.288   Prob(JB):                        0.750
Kurtosis:                       1.903   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.939
Model:                              GLS   Adj. R-squared:                  0.903
Method:                   Least Squares   F-statistic:                     25.79
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00181
Time:                          01:28:49   Log-Likelihood:                -44.154
No. Observations:                     9   AIC:                             96.31
Df Residuals:                         5   BIC:                             97.10
Df Model:                             3
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.035e+05   2.56e+04     -4.039      0.010   -1.69e+05   -3.76e+04
Boudin         126.6667     56.620      2.237      0.075     -18.880     272.213
Year            51.3333     12.661      4.055      0.010      18.788      83.878
Before_COVID    96.8000     89.881      1.077      0.331    -134.248     327.848
==============================================================================
Omnibus:                        0.657   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.576
Skew:                           0.288   Prob(JB):                        0.750
Kurtosis:                       1.903   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.942
Model:                             GLS   Adj. R-squared:                  0.907
Method:                  Least Squares   F-statistic:                     26.89
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):            0.00164
Time:                         01:29:03   Log-Likelihood:                -43.566
No. Observations:                    9   AIC:                             95.13
Df Residuals:                        5   BIC:                             95.92
Df Model:                            3
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.225e+04    2.4e+04     -1.761      0.139   -1.04e+05    1.94e+04
Boudin          92.1667     53.038      1.738      0.143     -44.172     228.505
Year            21.0833     11.860      1.778      0.136      -9.403      51.570
Before_COVID   -76.9000     84.195     -0.913      0.403    -293.331     139.531
==============================================================================
Omnibus:                        2.997   Durbin-Watson:                   3.394
Prob(Omnibus):                  0.223   Jarque-Bera (JB):                0.860
Skew:                           0.749   Prob(JB):                        0.651
Kurtosis:                       3.223   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.942
Model:                             GLS   Adj. R-squared:                  0.907
Method:                  Least Squares   F-statistic:                     26.89
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):            0.00164
Time:                         01:29:19   Log-Likelihood:                -43.566
No. Observations:                    9   AIC:                             95.13
Df Residuals:                        5   BIC:                             95.92
Df Model:                            3
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.225e+04    2.4e+04     -1.761      0.139   -1.04e+05    1.94e+04
Boudin          92.1667     53.038      1.738      0.143     -44.172     228.505
Year            21.0833     11.860      1.778      0.136      -9.403      51.570
Before_COVID   -76.9000     84.195     -0.913      0.403    -293.331     139.531
==============================================================================
Omnibus:                        2.997   Durbin-Watson:                   3.394
Prob(Omnibus):                  0.223   Jarque-Bera (JB):                0.860
Skew:                           0.749   Prob(JB):                        0.651
Kurtosis:                       3.223   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.953
Model:                                        GLS   Adj. R-squared:                  0.924
Method:                             Least Squares   F-statistic:                     33.60
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           0.000972
Time:                                    01:29:31   Log-Likelihood:                -41.987
No. Observations:                               9   AIC:                             91.97
Df Residuals:                                   5   BIC:                             92.76
Df Model:                                       3
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.773e+04   2.01e+04     -1.874      0.120   -8.95e+04     1.4e+04
Boudin          90.6667     44.506      2.037      0.097     -23.741     205.074
Year            18.8333      9.952      1.892      0.117      -6.749      44.416
Before_COVID   -73.2000     70.652     -1.036      0.348    -254.816     108.416
==============================================================================
Omnibus:                        2.270   Durbin-Watson:                   2.996
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                0.140
Skew:                           0.078   Prob(JB):                        0.932
Kurtosis:                       3.592   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.953
Model:                                        GLS   Adj. R-squared:                  0.924
Method:                             Least Squares   F-statistic:                     33.60
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           0.000972
Time:                                    01:29:42   Log-Likelihood:                -41.987
No. Observations:                               9   AIC:                             91.97
Df Residuals:                                   5   BIC:                             92.76
Df Model:                                       3
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.773e+04   2.01e+04     -1.874      0.120   -8.95e+04     1.4e+04
Boudin          90.6667     44.506      2.037      0.097     -23.741     205.074
Year            18.8333      9.952      1.892      0.117      -6.749      44.416
Before_COVID   -73.2000     70.652     -1.036      0.348    -254.816     108.416
==============================================================================
Omnibus:                        2.270   Durbin-Watson:                   2.996
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                0.140
Skew:                           0.078   Prob(JB):                        0.932
Kurtosis:                       3.592   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.909
Model:                                       GLS   Adj. R-squared:                  0.855
Method:                            Least Squares   F-statistic:                     16.74
Date:                           Thu, 21 Sep 2023   Prob (F-statistic):            0.00486
Time:                                   01:29:55   Log-Likelihood:                -43.266
No. Observations:                              9   AIC:                             94.53
Df Residuals:                                  5   BIC:                             95.32
Df Model:                                      3
Covariance Type:                       nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.626e+04   2.32e+04     -1.132      0.309   -8.59e+04    3.34e+04
Boudin         -14.6667     51.299     -0.286      0.786    -146.536     117.202
Year            13.1667     11.471      1.148      0.303     -16.320      42.654
Before_COVID  -136.6000     81.435     -1.677      0.154    -345.936      72.736
==============================================================================
Omnibus:                        2.568   Durbin-Watson:                   2.466
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                1.209
Skew:                          -0.883   Prob(JB):                        0.546
Kurtosis:                       2.674   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     9.685
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0965
Time:                        01:30:27   Log-Likelihood:                 17.819
No. Observations:                   9   AIC:                            -21.64
Df Residuals:                       2   BIC:                            -20.26
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -196.9036     64.578     -3.049      0.093    -474.762      80.955
Boudin                             0.1195      0.131      0.914      0.457      -0.443       0.682
Year                               0.1016      0.032      3.157      0.087      -0.037       0.240
Before_COVID                       0.0161      0.322      0.050      0.965      -1.368       1.400
Med_Arrest_To_Close                0.0099      0.005      1.941      0.192      -0.012       0.032
Med_Arrest_To_Close_Conviction    -0.0096      0.005     -1.845      0.206      -0.032       0.013
Med_Arrest_To_Close_Dismissal     -0.0056      0.002     -2.571      0.124      -0.015       0.004
==============================================================================
Omnibus:                        3.691   Durbin-Watson:                   2.801
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                0.915
Skew:                          -0.734   Prob(JB):                        0.633
Kurtosis:                       3.537   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     9.685
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0965
Time:                        01:30:57   Log-Likelihood:                 17.819
No. Observations:                   9   AIC:                            -21.64
Df Residuals:                       2   BIC:                            -20.26
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -196.9036     64.578     -3.049      0.093    -474.762      80.955
Boudin                             0.1195      0.131      0.914      0.457      -0.443       0.682
Year                               0.1016      0.032      3.157      0.087      -0.037       0.240
Before_COVID                       0.0161      0.322      0.050      0.965      -1.368       1.400
Med_Arrest_To_Close                0.0099      0.005      1.941      0.192      -0.012       0.032
Med_Arrest_To_Close_Conviction    -0.0096      0.005     -1.845      0.206      -0.032       0.013
Med_Arrest_To_Close_Dismissal     -0.0056      0.002     -2.571      0.124      -0.015       0.004
==============================================================================
Omnibus:                        3.691   Durbin-Watson:                   2.801
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                0.915
Skew:                          -0.734   Prob(JB):                        0.633
Kurtosis:                       3.537   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.992
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     43.61
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0226
Time:                        01:31:10   Log-Likelihood:                 17.937
No. Observations:                   9   AIC:                            -21.87
Df Residuals:                       2   BIC:                            -20.49
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -154.4127     63.740     -2.423      0.136    -428.663     119.838
Boudin                             0.1800      0.129      1.395      0.298      -0.375       0.735
Year                               0.0808      0.032      2.541      0.126      -0.056       0.217
Before_COVID                      -0.2949      0.318     -0.929      0.451      -1.661       1.071
Med_Arrest_To_Close                0.0151      0.005      3.008      0.095      -0.007       0.037
Med_Arrest_To_Close_Conviction    -0.0160      0.005     -3.110      0.090      -0.038       0.006
Med_Arrest_To_Close_Dismissal     -0.0082      0.002     -3.839      0.062      -0.017       0.001
==============================================================================
Omnibus:                        1.803   Durbin-Watson:                   3.003
Prob(Omnibus):                  0.406   Jarque-Bera (JB):                0.712
Skew:                          -0.679   Prob(JB):                        0.700
Kurtosis:                       2.765   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.992
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     43.61
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0226
Time:                        01:31:35   Log-Likelihood:                 17.937
No. Observations:                   9   AIC:                            -21.87
Df Residuals:                       2   BIC:                            -20.49
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -154.4127     63.740     -2.423      0.136    -428.663     119.838
Boudin                             0.1800      0.129      1.395      0.298      -0.375       0.735
Year                               0.0808      0.032      2.541      0.126      -0.056       0.217
Before_COVID                      -0.2949      0.318     -0.929      0.451      -1.661       1.071
Med_Arrest_To_Close                0.0151      0.005      3.008      0.095      -0.007       0.037
Med_Arrest_To_Close_Conviction    -0.0160      0.005     -3.110      0.090      -0.038       0.006
Med_Arrest_To_Close_Dismissal     -0.0082      0.002     -3.839      0.062      -0.017       0.001
==============================================================================
Omnibus:                        1.803   Durbin-Watson:                   3.003
Prob(Omnibus):                  0.406   Jarque-Bera (JB):                0.712
Skew:                          -0.679   Prob(JB):                        0.700
Kurtosis:                       2.765   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.774
Model:                            GLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     8.564
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0243
Time:                        01:32:16   Log-Likelihood:                 8.9127
No. Observations:                   8   AIC:                            -11.83
Df Residuals:                       5   BIC:                            -11.59
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -102.7817     58.492     -1.757      0.139    -253.140      47.576
Boudin        -0.4889      0.137     -3.562      0.016      -0.842      -0.136
Year           0.0546      0.029      1.884      0.118      -0.020       0.129
==============================================================================
Omnibus:                        1.316   Durbin-Watson:                   1.444
Prob(Omnibus):                  0.518   Jarque-Bera (JB):                0.865
Skew:                           0.563   Prob(JB):                        0.649
Kurtosis:                       1.848   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.886
Model:                            GLS   Adj. R-squared:                  0.841
Method:                 Least Squares   F-statistic:                     19.47
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00437
Time:                        01:32:43   Log-Likelihood:                 6.1097
No. Observations:                   8   AIC:                            -6.219
Df Residuals:                       5   BIC:                            -5.981
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     29.6771     83.035      0.357      0.735    -183.772     243.126
Boudin        -0.6041      0.195     -3.101      0.027      -1.105      -0.103
Year          -0.0113      0.041     -0.274      0.795      -0.117       0.095
==============================================================================
Omnibus:                        0.115   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.944   Jarque-Bera (JB):                0.289
Skew:                           0.189   Prob(JB):                        0.865
Kurtosis:                       2.148   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.934
Model:                              GLS   Adj. R-squared:                  0.907
Method:                   Least Squares   F-statistic:                     35.18
Date:                  Thu, 21 Sep 2023   Prob (F-statistic):            0.00113
Time:                          01:33:00   Log-Likelihood:                -39.719
No. Observations:                     8   AIC:                             85.44
Df Residuals:                         5   BIC:                             85.68
Df Model:                             2
Covariance Type:              nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1.034e+05   2.55e+04     -4.048      0.010   -1.69e+05   -3.77e+04
Boudin        29.8667     59.921      0.498      0.639    -124.165     183.898
Year          51.3333     12.661      4.055      0.010      18.788      83.878
==============================================================================
Omnibus:                        1.154   Durbin-Watson:                   1.323
Prob(Omnibus):                  0.562   Jarque-Bera (JB):                0.669
Skew:                           0.271   Prob(JB):                        0.716
Kurtosis:                       1.691   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.937
Model:                             GLS   Adj. R-squared:                  0.912
Method:                  Least Squares   F-statistic:                     37.25
Date:                 Thu, 21 Sep 2023   Prob (F-statistic):           0.000992
Time:                         01:33:12   Log-Likelihood:                -39.196
No. Observations:                    8   AIC:                             84.39
Df Residuals:                        5   BIC:                             84.63
Df Model:                            2
Covariance Type:             nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.233e+04   2.39e+04     -1.769      0.137   -1.04e+05    1.92e+04
Boudin       169.0667     56.130      3.012      0.030      24.779     313.354
Year          21.0833     11.860      1.778      0.136      -9.403      51.570
==============================================================================
Omnibus:                        2.151   Durbin-Watson:                   3.153
Prob(Omnibus):                  0.341   Jarque-Bera (JB):                0.671
Skew:                           0.706   Prob(JB):                        0.715
Kurtosis:                       2.865   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.949
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     46.92
Date:                            Thu, 21 Sep 2023   Prob (F-statistic):           0.000575
Time:                                    01:33:38   Log-Likelihood:                -37.793
No. Observations:                               8   AIC:                             81.59
Df Residuals:                                   5   BIC:                             81.82
Df Model:                                       2
Covariance Type:                        nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -3.78e+04   2.01e+04     -1.883      0.118   -8.94e+04    1.38e+04
Boudin       163.8667     47.101      3.479      0.018      42.789     284.944
Year          18.8333      9.952      1.892      0.117      -6.749      44.416
==============================================================================
Omnibus:                        1.518   Durbin-Watson:                   2.561
Prob(Omnibus):                  0.468   Jarque-Bera (JB):                0.020
Skew:                           0.074   Prob(JB):                        0.990
Kurtosis:                       3.193   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.858
Model:                                       GLS   Adj. R-squared:                  0.811
Method:                            Least Squares   F-statistic:                     18.20
Date:                           Thu, 21 Sep 2023   Prob (F-statistic):            0.00284
Time:                                   01:33:54   Log-Likelihood:                -45.275
No. Observations:                              9   AIC:                             96.55
Df Residuals:                                  6   BIC:                             97.14
Df Model:                                      2
Covariance Type:                       nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -5.919e+04   1.41e+04     -4.192      0.006   -9.37e+04   -2.46e+04
Boudin        50.3810     38.324      1.315      0.237     -43.396     144.158
Year          29.4286      6.997      4.206      0.006      12.307      46.550
==============================================================================
Omnibus:                        1.186   Durbin-Watson:                   1.205
Prob(Omnibus):                  0.553   Jarque-Bera (JB):                0.767
Skew:                          -0.381   Prob(JB):                        0.681
Kurtosis:                       1.789   Cond. No.                     1.89e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.89e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                     17.41
Date:                Thu, 21 Sep 2023   Prob (F-statistic):             0.0200
Time:                        01:34:18   Log-Likelihood:                 17.813
No. Observations:                   9   AIC:                            -23.63
Df Residuals:                       3   BIC:                            -22.44
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -198.0056     49.589     -3.993      0.028    -355.820     -40.191
Boudin                             0.1171      0.099      1.180      0.323      -0.199       0.433
Year                               0.1022      0.025      4.146      0.025       0.024       0.181
Med_Arrest_To_Close                0.0101      0.002      4.145      0.026       0.002       0.018
Med_Arrest_To_Close_Conviction    -0.0099      0.002     -4.091      0.026      -0.018      -0.002
Med_Arrest_To_Close_Dismissal     -0.0057      0.001     -6.425      0.008      -0.009      -0.003
==============================================================================
Omnibus:                        4.205   Durbin-Watson:                   2.849
Prob(Omnibus):                  0.122   Jarque-Bera (JB):                1.101
Skew:                          -0.797   Prob(JB):                        0.577
Kurtosis:                       3.630   Cond. No.                     5.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [ ]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.989
Model:                            GLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     54.66
Date:                Thu, 21 Sep 2023   Prob (F-statistic):            0.00380
Time:                        01:34:51   Log-Likelihood:                 16.323
No. Observations:                   9   AIC:                            -20.65
Df Residuals:                       3   BIC:                            -19.46
Df Model:                           5
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -134.1947     58.522     -2.293      0.106    -320.436      52.047
Boudin                             0.2243      0.117      1.916      0.151      -0.148       0.597
Year                               0.0705      0.029      2.422      0.094      -0.022       0.163
Med_Arrest_To_Close                0.0113      0.003      3.945      0.029       0.002       0.020
Med_Arrest_To_Close_Conviction    -0.0121      0.003     -4.249      0.024      -0.021      -0.003
Med_Arrest_To_Close_Dismissal     -0.0065      0.001     -6.237      0.008      -0.010      -0.003
==============================================================================
Omnibus:                        2.440   Durbin-Watson:                   2.096
Prob(Omnibus):                  0.295   Jarque-Bera (JB):                0.893
Skew:                           0.194   Prob(JB):                        0.640
Kurtosis:                       1.507   Cond. No.                     5.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# This is a test to see if anything  changed