<a href="https://colab.research.google.com/github/jgte29/ucbhonorsthesis2023-2024/blob/main/SF_DA_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install firebase-admin

# Load in Data & Libraries

In [3]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from scipy import stats
import warnings
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.diagnostic import linear_lm
import sklearn
from sklearn.model_selection import train_test_split
from datetime import datetime
# Initialize the Firebase app with your service account key
cred = credentials.Certificate(r'PRIVATE-KEY-sf-da-analysis-firebase.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://sf-da-analysis-6f156-default-rtdb.firebaseio.com/'
})

In [4]:
# For sf_prosecutions
# Get a reference to the Firebase Realtime Database
ref = db.reference('/District_Attorney_Cases_Prosecuted_2014_2023')

# Load data from the collection
sf_prosecutions = ref.get()

# Process the loaded data & converts it to a df
sf_prosecutions = pd.json_normalize(sf_prosecutions)
sf_prosecutions = sf_prosecutions.drop('id', axis=1)

# For sf_case_resolutions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_All_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_all = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_all = pd.json_normalize(sf_case_resolutions_all)
sf_case_resolutions_all = sf_case_resolutions_all.drop('id', axis=1)

# For sf_case_resolutions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_Violent_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_violent = pd.json_normalize(sf_case_resolutions_violent)
sf_case_resolutions_violent = sf_case_resolutions_violent.drop('id', axis=1)

# For sf_da_actions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_All_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_all = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_all = pd.json_normalize(sf_da_actions_all)
sf_da_actions_all = sf_da_actions_all.drop('id', axis=1)

# For sf_da_actions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_Violent_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_violent = pd.json_normalize(sf_da_actions_violent)
sf_da_actions_violent = sf_da_actions_violent.drop('id', axis=1)

# For sfpd_incidents_outcomes_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Outcomes_of_SFPD_Incidents_All_Crimes_2015_2023')

# Load data from the collection
sfpd_incidents_outcomes_all = ref.get()

# Process the loaded data & converts it to a df
sfpd_incidents_outcomes_all = pd.json_normalize(sfpd_incidents_outcomes_all)
sfpd_incidents_outcomes_all = sfpd_incidents_outcomes_all.drop('id', axis=1)

# For fed_off_by_crime_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_all = pd.json_normalize(fed_off_by_crime_all)
fed_off_by_crime_all = fed_off_by_crime_all.drop('id', axis=1)

# For fed_off_by_crime_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_violent = pd.json_normalize(fed_off_by_crime_violent)
fed_off_by_crime_violent = fed_off_by_crime_violent.drop('id', axis=1)

# For fed_off_by_dist_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_all = pd.json_normalize(fed_off_by_dist_all)
fed_off_by_dist_all = fed_off_by_dist_all.drop('id', axis=1)

# For fed_off_by_dist_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_violent = pd.json_normalize(fed_off_by_dist_violent)
fed_off_by_dist_violent = fed_off_by_dist_violent.drop('id', axis=1)

In [5]:
fed_off_by_dist_all

          Circuit              District  Fiscal_Year      N    Pct
0     Grand Total                 Total         2022  64157  1.000
1      DC Circuit  District of Columbia         2022    312  0.005
2     1st Circuit                 Maine         2022    180  0.003
3     1st Circuit         Massachusetts         2022    466  0.007
4     1st Circuit         New Hampshire         2022    180  0.003
..            ...                   ...          ...    ...    ...
755  11th Circuit     Florida, Northern         2015    255  0.004
756  11th Circuit     Florida, Southern         2015   2238  0.032
757  11th Circuit       Georgia, Middle         2015    377  0.005
758  11th Circuit     Georgia, Northern         2015    592  0.008
759  11th Circuit     Georgia, Southern         2015    420  0.006

[760 rows x 5 columns]

In [6]:
date_format = "%Y-%m-%dT%H:%M:%S.%fZ"

sf_prosecutions['arrest_date'] = pd.to_datetime(sf_prosecutions['arrest_date'], format = date_format)
sf_prosecutions['data_as_of'] = pd.to_datetime(sf_prosecutions['data_as_of'], format = date_format)
sf_prosecutions['data_loaded_at'] = pd.to_datetime(sf_prosecutions['data_loaded_at'], format = date_format)

In [7]:
boudin_start_date = datetime(2020, 1, 8, 0, 0, 0)
boudin_end_date = datetime(2022, 7, 9, 0, 0, 0)
sf_prosecutions_boudin = sf_prosecutions[(sf_prosecutions["arrest_date"] >= boudin_start_date) &
                                         (sf_prosecutions["arrest_date"] < boudin_end_date)]

sf_prosecutions_boudin

,arrest_date,case_status,court_number,crime_type,da_action_taken,data_as_of,data_loaded_at,dv_case,filed_case_type,incident_number,list_of_filed_charges
9383,2020-01-09 08:00:00,Filed Motion to Revoke,2506152,"Forgery, Checks, Access Cards",New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20171107-02506152,470D/F/0
9384,2020-01-30 08:00:00,Filed Motion to Revoke,2520522,Theft,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20200115-02520522,"487C/F/0, 245A4/M/0"
9385,2020-01-14 08:00:00,Filed Motion to Revoke,14005420,Assault,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,Yes,MTR,140153084,"591.5/M/0, 273.5A/F/0, 273.5A/F/0, 273.5A/F/0,..."
9386,2020-01-22 08:00:00,Filed Motion to Revoke,15018930,Robbery,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150735638,"242/M/0, 245A4/F/0, 243B/M/0, 211/F/2"
9387,2020-01-16 08:00:00,Filed Motion to Revoke,15026261,Narcotics,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150025953,"11378/F/0, 11377/M/0, 23123A/I/0"
...,...,...,...,...,...,...,...,...,...,...,...
99090,2022-06-24 07:00:00,,2530936,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,23-00344,
99091,2022-06-13 07:00:00,Pending,2530799,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,Z20220613-02530799,
99092,2022-07-06 07:00:00,Fugitive Status,22006648,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,Felony,220445185,"664/1085A/F/0, 664/496DA/F/0"
99096,2022-07-04 07:00:00,Pled Guilty to Other Case or Other DA Action,22006556,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220438726,
99097,2022-07-04 07:00:00,,22006565,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220437825,

# PART I - Boudin v National Trends (Fixed Effects)

## All Crimes

In [9]:
def year_marker(year, start, end=9999, mode = 'range'):
  # Default of 9999 is used to indicate ongoing
  if mode == 'before':
    try:
      if year < start:
        return 1
      else:
        return 0
    except:
      return 0

  if mode == 'after':
    start += 1 #Increments start by 1

  # Used for both 'after' and 'range' modes
  else:
    try:
      if year >= start and year <= end:
        return 1
      else:
        return 0
    except:
      return 0

In [10]:
fed_off_totals_all = fed_off_by_dist_all[fed_off_by_dist_all["District"] == "Total"].reset_index(drop=True)
fed_off_totals_all = fed_off_totals_all.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_all.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_all.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_all['Log_Total'] = np.log(fed_off_totals_all['Total'])
fed_off_totals_all['Boudin'] = 0
fed_off_totals_all['SF'] = 0
fed_off_totals_all['Before_COVID'] = fed_off_totals_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_all

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022  64157  11.069088       0   0             0
1  2021  57304  10.956126       0   0             0
2  2020  64591  11.075830       0   0             0
3  2019  76593  11.246261       0   0             1
4  2018  69470  11.148650       0   0             1
5  2017  66899  11.110939       0   0             1
6  2016  67794  11.124229       0   0             1
7  2015  71030  11.170858       0   0             1

In [11]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions = sf_case_resolutions_all[["Year", "Conviction"]]
sfda_convictions["Conviction"] = sfda_convictions["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions['Log_Total'] = np.log(sfda_convictions['Total'])
sfda_convictions['Boudin'] = sfda_convictions.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions['SF'] = 1
sfda_convictions['Before_COVID'] = sfda_convictions.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_proj = sfda_convictions.copy() #Creates defensive copy
sfda_convictions_proj.iloc[8, 1] = sfda_convictions_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_proj = sfda_convictions_proj.drop(9)

# Drops '2023*' Row
sfda_convictions = sfda_convictions.drop(9)

sfda_convictions["Year"] = sfda_convictions["Year"].astype(int)
sfda_convictions_proj["Year"] = sfda_convictions_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

In [12]:
# Concatenate vertically (along rows)
sf_fed_off_totals = pd.concat([fed_off_totals_all, sfda_convictions], axis=0)
sf_fed_off_totals_proj = pd.concat([fed_off_totals_all, sfda_convictions_proj], axis=0)

# Reset the index
sf_fed_off_totals = sf_fed_off_totals.reset_index(drop=True)
sf_fed_off_totals_proj = sf_fed_off_totals_proj.reset_index(drop=True)

sf_fed_off_totals

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0
16  2023   1342   7.201916       0   1             0

### 2023 Inclusive

In [13]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     526.9
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           2.29e-13
Time:                        23:19:25   Log-Likelihood:                -156.76
No. Observations:                  17   AIC:                             323.5
Df Residuals:                      12   BIC:                             327.7
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.418e+06   1.15e+06     -1.236      0.240   -3.92e+06    1.08e+06
Year           732.9386    567.576      1.291      0.221    -503.703    1969.580
Boudin        4473.8070   2577.032      1.736      0.108   -1141.063    1.01e+04
SF           -6.588e+04   1635.928    -40.272      0.000   -6.94e+04   -6.23e+04
Before_COVID  9774.9474   3160.914      3.092      0.009    2887.908    1.67e+04
==============================================================================
Omnibus:                        1.133   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.568   Jarque-Bera (JB):                0.112
Skew:                          -0.032   Prob(JB):                        0.945
Kurtosis:                       3.393   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [14]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     306.0
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           5.81e-12
Time:                        23:19:59   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     78.971      1.143      0.275     -81.799     262.326
Year            -0.0393      0.039     -1.005      0.335      -0.124       0.046
Boudin          -0.3656      0.177     -2.061      0.062      -0.752       0.021
SF              -3.2094      0.113    -28.502      0.000      -3.455      -2.964
Before_COVID     0.1870      0.218      0.859      0.407      -0.287       0.661
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [15]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     508.3
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           2.84e-13
Time:                        23:20:23   Log-Likelihood:                -157.04
No. Observations:                  17   AIC:                             324.1
Df Residuals:                      12   BIC:                             328.3
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -1.47e+06   1.17e+06     -1.260      0.232   -4.01e+06    1.07e+06
Year           758.6404    577.177      1.314      0.213    -498.920    2016.201
Boudin        4247.6316   2620.624      1.621      0.131   -1462.217    9957.480
SF           -6.576e+04   1663.601    -39.528      0.000   -6.94e+04   -6.21e+04
Before_COVID  9713.2632   3214.383      3.022      0.011    2709.725    1.67e+04
==============================================================================
Omnibus:                        1.053   Durbin-Watson:                   1.975
Prob(Omnibus):                  0.591   Jarque-Bera (JB):                0.091
Skew:                          -0.028   Prob(JB):                        0.956
Kurtosis:                       3.353   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [16]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     306.0
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           5.81e-12
Time:                        23:20:42   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     78.971      1.143      0.275     -81.799     262.326
Year            -0.0393      0.039     -1.005      0.335      -0.124       0.046
Boudin          -0.3656      0.177     -2.061      0.062      -0.752       0.021
SF              -3.2094      0.113    -28.502      0.000      -3.455      -2.964
Before_COVID     0.1870      0.218      0.859      0.407      -0.287       0.661
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [17]:
# Drops '2023' Row
sf_fed_off_totals_no2023 = sf_fed_off_totals[sf_fed_off_totals["Year"] != 2023]
sf_fed_off_totals_no2023

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0

In [18]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.995
Model:                            GLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     533.0
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           1.65e-12
Time:                        23:21:33   Log-Likelihood:                -146.75
No. Observations:                  16   AIC:                             303.5
Df Residuals:                      11   BIC:                             307.4
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -9.466e+05   1.16e+06     -0.817      0.431    -3.5e+06     1.6e+06
Year           499.0833    573.186      0.871      0.403    -762.491    1760.658
Boudin        6531.7333   2900.118      2.252      0.046     148.616    1.29e+04
SF           -6.701e+04   1775.953    -37.729      0.000   -7.09e+04   -6.31e+04
Before_COVID  1.034e+04   3076.040      3.360      0.006    3565.882    1.71e+04
==============================================================================
Omnibus:                        0.910   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.634   Jarque-Bera (JB):                0.078
Skew:                           0.127   Prob(JB):                        0.962
Kurtosis:                       3.229   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [19]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.996
Model:                            GLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                     740.7
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           2.73e-13
Time:                        23:21:50   Log-Likelihood:                 13.855
No. Observations:                  16   AIC:                            -17.71
Df Residuals:                      11   BIC:                            -13.85
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       21.7086     50.642      0.429      0.676     -89.753     133.170
Year            -0.0053      0.025     -0.211      0.837      -0.060       0.050
Boudin          -0.6647      0.127     -5.243      0.000      -0.944      -0.386
SF              -3.0463      0.078    -39.236      0.000      -3.217      -2.875
Before_COVID     0.1054      0.134      0.784      0.450      -0.191       0.401
==============================================================================
Omnibus:                        3.222   Durbin-Watson:                   2.141
Prob(Omnibus):                  0.200   Jarque-Bera (JB):                1.170
Skew:                           0.498   Prob(JB):                        0.557
Kurtosis:                       3.874   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

In [20]:
fed_off_totals_violent = fed_off_by_dist_violent[fed_off_by_dist_violent["District"] == "Total"].reset_index(drop=True)
fed_off_totals_violent = fed_off_totals_violent.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_violent.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_violent.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_violent['Log_Total'] = np.log(fed_off_totals_violent['Total'])
fed_off_totals_violent['Boudin'] = 0
fed_off_totals_violent['SF'] = 0
fed_off_totals_violent['Before_COVID'] = fed_off_totals_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_violent

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022   4417   8.393216       0   0             0
1  2021   3438   8.142645       0   0             0
2  2020   3219   8.076826       0   0             0
3  2019   4326   8.372399       0   0             1
4  2018   3973   8.287277       0   0             1
5  2017   3927   8.275631       0   0             1
6  2016   3816   8.246958       0   0             1
7  2015   3835   8.251925       0   0             1

In [21]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions_violent = sf_case_resolutions_violent[["Year", "Conviction"]]
sfda_convictions_violent["Conviction"] = sfda_convictions_violent["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions_violent.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions_violent['Log_Total'] = np.log(sfda_convictions_violent['Total'])
sfda_convictions_violent['Boudin'] = sfda_convictions_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions_violent['SF'] = 1
sfda_convictions_violent['Before_COVID'] = sfda_convictions_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_violent_proj = sfda_convictions_violent.copy() #Creates defensive copy
sfda_convictions_violent_proj.iloc[8, 1] = sfda_convictions_violent_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_violent_proj = sfda_convictions_violent_proj.drop(9)

# Drops '2023*' Row
sfda_convictions_violent = sfda_convictions_violent.drop(9)

sfda_convictions_violent["Year"] = sfda_convictions_violent["Year"].astype(int)
sfda_convictions_violent_proj["Year"] = sfda_convictions_violent_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

In [22]:
# Concatenate vertically (along rows)
sf_fed_off_totals_violent = pd.concat([fed_off_totals_violent, sfda_convictions_violent], axis=0)
sf_fed_off_totals_violent_proj = pd.concat([fed_off_totals_violent, sfda_convictions_violent_proj], axis=0)

# Reset the index
sf_fed_off_totals_violent = sf_fed_off_totals_violent.reset_index(drop=True)
sf_fed_off_totals_violent_proj = sf_fed_off_totals_violent_proj.reset_index(drop=True)

sf_fed_off_totals_violent

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0
16  2023    397   5.983936       0   1             0

### 2023 Inclusive

In [23]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.978
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     132.0
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           8.27e-10
Time:                        23:22:50   Log-Likelihood:                -116.98
No. Observations:                  17   AIC:                             244.0
Df Residuals:                      12   BIC:                             248.1
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.469e+05   1.11e+05     -1.330      0.208   -3.88e+05    9.38e+04
Year            74.4883     54.669      1.363      0.198     -44.624     193.601
Boudin           9.6696    248.218      0.039      0.970    -531.152     550.491
SF           -3090.4561    157.572    -19.613      0.000   -3433.775   -2747.137
Before_COVID   723.1614    304.457      2.375      0.035      59.806    1386.517
==============================================================================
Omnibus:                       16.100   Durbin-Watson:                   1.503
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               14.752
Skew:                           1.665   Prob(JB):                     0.000626
Kurtosis:                       6.120   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [24]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     68.70
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           3.62e-08
Time:                        23:23:09   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     84.854      0.542      0.597    -138.857     230.905
Year            -0.0188      0.042     -0.448      0.662      -0.110       0.073
Boudin          -0.2319      0.191     -1.217      0.247      -0.647       0.183
SF              -1.5740      0.121    -13.009      0.000      -1.838      -1.310
Before_COVID     0.2509      0.234      1.073      0.304      -0.258       0.760
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [25]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     141.7
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           5.46e-10
Time:                        23:23:26   Log-Likelihood:                -116.27
No. Observations:                  17   AIC:                             242.5
Df Residuals:                      12   BIC:                             246.7
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.622e+05   1.06e+05     -1.531      0.152   -3.93e+05    6.87e+04
Year            82.0760     52.426      1.566      0.143     -32.151     196.303
Boudin         -57.1023    238.037     -0.240      0.814    -575.740     461.535
SF           -3054.0351    151.108    -20.211      0.000   -3383.272   -2724.798
Before_COVID   704.9509    291.969      2.414      0.033      68.805    1341.097
==============================================================================
Omnibus:                       15.300   Durbin-Watson:                   1.621
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               13.494
Skew:                           1.612   Prob(JB):                      0.00117
Kurtosis:                       5.942   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [27]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     68.70
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           3.62e-08
Time:                        23:23:57   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     84.854      0.542      0.597    -138.857     230.905
Year            -0.0188      0.042     -0.448      0.662      -0.110       0.073
Boudin          -0.2319      0.191     -1.217      0.247      -0.647       0.183
SF              -1.5740      0.121    -13.009      0.000      -1.838      -1.310
Before_COVID     0.2509      0.234      1.073      0.304      -0.258       0.760
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [28]:
# Drops '2023' Row
sf_fed_off_totals_violent_no2023 = sf_fed_off_totals_violent[sf_fed_off_totals_violent["Year"] != 2023]
sf_fed_off_totals_violent_no2023

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0

In [29]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     129.2
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           3.62e-09
Time:                        23:25:03   Log-Likelihood:                -109.36
No. Observations:                  16   AIC:                             228.7
Df Residuals:                      11   BIC:                             232.6
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.914e+05   1.12e+05     -1.709      0.115   -4.38e+05     5.5e+04
Year            96.5417     55.406      1.742      0.109     -25.406     218.489
Boudin        -184.4000    280.334     -0.658      0.524    -801.411     432.611
SF           -2984.6000    171.669    -17.386      0.000   -3362.441   -2606.759
Before_COVID   670.2333    297.339      2.254      0.046      15.794    1324.672
==============================================================================
Omnibus:                        8.179   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                4.835
Skew:                           1.094   Prob(JB):                       0.0892
Kurtosis:                       4.569   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [30]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.986
Model:                            GLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     190.4
Date:                Sun, 24 Sep 2023   Prob (F-statistic):           4.48e-10
Time:                        23:25:19   Log-Likelihood:                 14.123
No. Observations:                  16   AIC:                            -18.25
Df Residuals:                      11   BIC:                            -14.38
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -30.7100     49.803     -0.617      0.550    -140.325      78.905
Year             0.0193      0.025      0.781      0.451      -0.035       0.073
Boudin          -0.5667      0.125     -4.545      0.001      -0.841      -0.292
SF              -1.3914      0.076    -18.224      0.000      -1.559      -1.223
Before_COVID     0.1596      0.132      1.207      0.253      -0.131       0.451
==============================================================================
Omnibus:                        1.663   Durbin-Watson:                   2.070
Prob(Omnibus):                  0.435   Jarque-Bera (JB):                0.790
Skew:                           0.544   Prob(JB):                        0.674
Kurtosis:                       2.994   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# PART II - SF Before & After Boudin Takes Office (DID)

## All Crimes

### 2023 Inclusive

In [32]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_all = sf_case_resolutions_all.copy()
sf_cr_all["Conviction"] = sf_cr_all["Conviction"].astype(int)

sf_cr_all['Log_Conviction'] = np.log(sf_cr_all['Conviction'])
sf_cr_all['Log_Total'] = np.log(sf_cr_all['Total'])
sf_cr_all['Boudin'] = sf_cr_all.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_all['Before_COVID'] = sf_cr_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_all_proj = sf_cr_all.copy() #Creates defensive copy
sf_cr_all_proj.iloc[8, 1] = sf_cr_all_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_all_proj = sf_cr_all_proj.drop(9)

# Drops '2023*' Row
sf_cr_all = sf_cr_all.drop(9)

# Addresses type issues
sf_cr_all["Year"] = sf_cr_all["Year"].astype(int)
sf_cr_all["Med_Arrest_To_Close"] = sf_cr_all["Med_Arrest_To_Close"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Conviction"] = sf_cr_all["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Dismissal"] = sf_cr_all["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_all_proj["Year"] = sf_cr_all_proj["Year"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close"] = sf_cr_all_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_all_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_all_no2023 = sf_cr_all[sf_cr_all["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [39]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.926
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     12.56
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0155
Time:                        23:33:18   Log-Likelihood:                 13.356
No. Observations:                   9   AIC:                            -16.71
Df Residuals:                       4   BIC:                            -15.73
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -118.8283     52.645     -2.257      0.087    -264.994      27.337
Boudin         203.6139    128.846      1.580      0.189    -154.121     561.349
Year             0.0628      0.026      2.413      0.073      -0.009       0.135
Before_COVID     0.8483      0.180      4.705      0.009       0.348       1.349
Boudin:Year     -0.1006      0.064     -1.578      0.190      -0.278       0.076
==============================================================================
Omnibus:                        2.481   Durbin-Watson:                   2.729
Prob(Omnibus):                  0.289   Jarque-Bera (JB):                1.405
Skew:                          -0.920   Prob(JB):                        0.495
Kurtosis:                       2.399   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [36]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.926
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     12.56
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0155
Time:                        23:31:58   Log-Likelihood:                 13.356
No. Observations:                   9   AIC:                            -16.71
Df Residuals:                       4   BIC:                            -15.73
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -118.8283     52.645     -2.257      0.087    -264.994      27.337
Boudin         203.6139    128.846      1.580      0.189    -154.121     561.349
Year             0.0628      0.026      2.413      0.073      -0.009       0.135
Before_COVID     0.8483      0.180      4.705      0.009       0.348       1.349
Boudin:Year     -0.1006      0.064     -1.578      0.190      -0.278       0.076
==============================================================================
Omnibus:                        2.481   Durbin-Watson:                   2.729
Prob(Omnibus):                  0.289   Jarque-Bera (JB):                1.405
Skew:                          -0.920   Prob(JB):                        0.495
Kurtosis:                       2.399   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [40]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.948
Model:                            GLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     18.34
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00774
Time:                        23:33:31   Log-Likelihood:                 8.1767
No. Observations:                   9   AIC:                            -6.353
Df Residuals:                       4   BIC:                            -5.367
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -3.2153     93.601     -0.034      0.974    -263.095     256.664
Boudin         360.9264    229.087      1.576      0.190    -275.120     996.973
Year             0.0051      0.046      0.111      0.917      -0.123       0.134
Before_COVID     0.9429      0.321      2.941      0.042       0.053       1.833
Boudin:Year     -0.1785      0.113     -1.575      0.190      -0.493       0.136
==============================================================================
Omnibus:                        2.677   Durbin-Watson:                   2.723
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.506
Skew:                          -0.957   Prob(JB):                        0.471
Kurtosis:                       2.408   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [41]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.948
Model:                            GLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     18.34
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00774
Time:                        23:33:41   Log-Likelihood:                 8.1767
No. Observations:                   9   AIC:                            -6.353
Df Residuals:                       4   BIC:                            -5.367
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -3.2153     93.601     -0.034      0.974    -263.095     256.664
Boudin         360.9264    229.087      1.576      0.190    -275.120     996.973
Year             0.0051      0.046      0.111      0.917      -0.123       0.134
Before_COVID     0.9429      0.321      2.941      0.042       0.053       1.833
Boudin:Year     -0.1785      0.113     -1.575      0.190      -0.493       0.136
==============================================================================
Omnibus:                        2.677   Durbin-Watson:                   2.723
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.506
Skew:                          -0.957   Prob(JB):                        0.471
Kurtosis:                       2.408   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [42]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.923
Model:                              GLS   Adj. R-squared:                  0.846
Method:                   Least Squares   F-statistic:                     12.01
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):             0.0168
Time:                          23:34:00   Log-Likelihood:                -55.406
No. Observations:                     9   AIC:                             120.8
Df Residuals:                         4   BIC:                             121.8
Df Model:                             4
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.932e+05    1.1e+05     -2.678      0.055   -5.97e+05    1.08e+04
Boudin       -1.924e+05   2.68e+05     -0.718      0.512   -9.37e+05    5.52e+05
Year           145.5000     54.133      2.688      0.055      -4.798     295.798
Before_COVID   402.6000    375.047      1.073      0.344    -638.697    1443.897
Boudin:Year     95.5000    132.599      0.720      0.511    -272.654     463.654
==============================================================================
Omnibus:                        0.017   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.175
Skew:                           0.059   Prob(JB):                        0.916
Kurtosis:                       2.327   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [43]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.923
Model:                              GLS   Adj. R-squared:                  0.846
Method:                   Least Squares   F-statistic:                     12.01
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):             0.0168
Time:                          23:34:39   Log-Likelihood:                -55.406
No. Observations:                     9   AIC:                             120.8
Df Residuals:                         4   BIC:                             121.8
Df Model:                             4
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.932e+05    1.1e+05     -2.678      0.055   -5.97e+05    1.08e+04
Boudin       -1.924e+05   2.68e+05     -0.718      0.512   -9.37e+05    5.52e+05
Year           145.5000     54.133      2.688      0.055      -4.798     295.798
Before_COVID   402.6000    375.047      1.073      0.344    -638.697    1443.897
Boudin:Year     95.5000    132.599      0.720      0.511    -272.654     463.654
==============================================================================
Omnibus:                        0.017   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.175
Skew:                           0.059   Prob(JB):                        0.916
Kurtosis:                       2.327   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [50]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.974
Model:                             GLS   Adj. R-squared:                  0.947
Method:                  Least Squares   F-statistic:                     36.94
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00205
Time:                         23:35:42   Log-Likelihood:                -37.837
No. Observations:                    9   AIC:                             85.67
Df Residuals:                        4   BIC:                             86.66
Df Model:                            4
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.259e+04   1.55e+04     -2.096      0.104   -7.58e+04    1.06e+04
Boudin       -4.787e+04   3.81e+04     -1.258      0.277   -1.54e+05    5.78e+04
Year            16.3000      7.686      2.121      0.101      -5.040      37.640
Before_COVID   -98.6000     53.250     -1.852      0.138    -246.446      49.246
Boudin:Year     23.7000     18.827      1.259      0.277     -28.571      75.971
==============================================================================
Omnibus:                        7.138   Durbin-Watson:                   3.174
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                2.355
Skew:                           1.135   Prob(JB):                        0.308
Kurtosis:                       4.060   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [51]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.974
Model:                             GLS   Adj. R-squared:                  0.947
Method:                  Least Squares   F-statistic:                     36.94
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00205
Time:                         23:36:00   Log-Likelihood:                -37.837
No. Observations:                    9   AIC:                             85.67
Df Residuals:                        4   BIC:                             86.66
Df Model:                            4
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.259e+04   1.55e+04     -2.096      0.104   -7.58e+04    1.06e+04
Boudin       -4.787e+04   3.81e+04     -1.258      0.277   -1.54e+05    5.78e+04
Year            16.3000      7.686      2.121      0.101      -5.040      37.640
Before_COVID   -98.6000     53.250     -1.852      0.138    -246.446      49.246
Boudin:Year     23.7000     18.827      1.259      0.277     -28.571      75.971
==============================================================================
Omnibus:                        7.138   Durbin-Watson:                   3.174
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                2.355
Skew:                           1.135   Prob(JB):                        0.308
Kurtosis:                       4.060   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [52]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.995
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     188.5
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):           8.33e-05
Time:                                    23:36:15   Log-Likelihood:                -27.654
No. Observations:                               9   AIC:                             65.31
Df Residuals:                                   4   BIC:                             66.30
Df Model:                                       4
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.882e+04   5015.523     -5.746      0.005   -4.27e+04   -1.49e+04
Boudin       -1.331e+04   1.23e+04     -1.085      0.339   -4.74e+04    2.08e+04
Year            14.4000      2.479      5.808      0.004       7.517      21.283
Before_COVID   -56.8000     17.177     -3.307      0.030    -104.490      -9.110
Boudin:Year      6.6000      6.073      1.087      0.338     -10.261      23.461
==============================================================================
Omnibus:                        5.942   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                1.946
Skew:                           1.077   Prob(JB):                        0.378
Kurtosis:                       3.742   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [53]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.995
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     188.5
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):           8.33e-05
Time:                                    23:36:35   Log-Likelihood:                -27.654
No. Observations:                               9   AIC:                             65.31
Df Residuals:                                   4   BIC:                             66.30
Df Model:                                       4
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.882e+04   5015.523     -5.746      0.005   -4.27e+04   -1.49e+04
Boudin       -1.331e+04   1.23e+04     -1.085      0.339   -4.74e+04    2.08e+04
Year            14.4000      2.479      5.808      0.004       7.517      21.283
Before_COVID   -56.8000     17.177     -3.307      0.030    -104.490      -9.110
Boudin:Year      6.6000      6.073      1.087      0.338     -10.261      23.461
==============================================================================
Omnibus:                        5.942   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                1.946
Skew:                           1.077   Prob(JB):                        0.378
Kurtosis:                       3.742   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [54]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.975
Model:                                       GLS   Adj. R-squared:                  0.950
Method:                            Least Squares   F-statistic:                     38.98
Date:                           Sun, 24 Sep 2023   Prob (F-statistic):            0.00185
Time:                                   23:36:54   Log-Likelihood:                -33.584
No. Observations:                              9   AIC:                             77.17
Df Residuals:                                  4   BIC:                             78.15
Df Model:                                      4
Covariance Type:                       nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.291e+04   9693.011     -2.363      0.077   -4.98e+04    4006.613
Boudin        6.563e+04   2.37e+04      2.766      0.051    -239.078    1.31e+05
Year            11.5000      4.791      2.400      0.074      -1.803      24.803
Before_COVID  -103.8000     33.196     -3.127      0.035    -195.966     -11.634
Boudin:Year    -32.5000     11.736     -2.769      0.050     -65.086       0.086
==============================================================================
Omnibus:                        6.078   Durbin-Watson:                   3.337
Prob(Omnibus):                  0.048   Jarque-Bera (JB):                1.719
Skew:                          -0.909   Prob(JB):                        0.423
Kurtosis:                       4.131   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [57]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       1.000
Model:                            GLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                     1879.
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0178
Time:                        23:38:32   Log-Likelihood:                 44.303
No. Observations:                   9   AIC:                            -72.61
Df Residuals:                       1   BIC:                            -71.03
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -354.2417     10.513    -33.696      0.019    -487.819    -220.664
Boudin                            61.0517     19.869      3.073      0.200    -191.403     313.506
Year                               0.1805      0.005     34.416      0.018       0.114       0.247
Before_COVID                       0.2701      0.025     10.861      0.058      -0.046       0.586
Med_Arrest_To_Close               -0.0024      0.000    -20.087      0.032      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0051      0.000    -11.238      0.056      -0.011       0.001
Med_Arrest_To_Close_Dismissal     -0.0006      0.000     -2.572      0.236      -0.003       0.002
Boudin:Year                       -0.0300      0.010     -3.048      0.202      -0.155       0.095
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                          -1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [58]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       1.000
Model:                            GLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                     1879.
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0178
Time:                        23:39:02   Log-Likelihood:                 44.303
No. Observations:                   9   AIC:                            -72.61
Df Residuals:                       1   BIC:                            -71.03
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -354.2417     10.513    -33.696      0.019    -487.819    -220.664
Boudin                            61.0517     19.869      3.073      0.200    -191.403     313.506
Year                               0.1805      0.005     34.416      0.018       0.114       0.247
Before_COVID                       0.2701      0.025     10.861      0.058      -0.046       0.586
Med_Arrest_To_Close               -0.0024      0.000    -20.087      0.032      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0051      0.000    -11.238      0.056      -0.011       0.001
Med_Arrest_To_Close_Dismissal     -0.0006      0.000     -2.572      0.236      -0.003       0.002
Boudin:Year                       -0.0300      0.010     -3.048      0.202      -0.155       0.095
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                          -1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [59]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     50.31
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.108
Time:                        23:39:20   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -26.50
Df Residuals:                       1   BIC:                            -24.92
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.9988    136.221     -2.848      0.215   -2118.856    1342.859
Boudin                            -0.3685    257.452     -0.001      0.999   -3271.606    3270.869
Year                               0.1975      0.068      2.906      0.211      -0.666       1.061
Before_COVID                       0.0627      0.322      0.195      0.878      -4.031       4.157
Med_Arrest_To_Close               -0.0044      0.002     -2.909      0.211      -0.024       0.015
Med_Arrest_To_Close_Conviction    -0.0088      0.006     -1.503      0.374      -0.083       0.065
Med_Arrest_To_Close_Dismissal      0.0005      0.003      0.177      0.888      -0.036       0.037
Boudin:Year                        0.0004      0.127      0.003      0.998      -1.620       1.620
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                           1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [60]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     50.31
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.108
Time:                        23:39:54   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -26.50
Df Residuals:                       1   BIC:                            -24.92
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.9988    136.221     -2.848      0.215   -2118.856    1342.859
Boudin                            -0.3685    257.452     -0.001      0.999   -3271.606    3270.869
Year                               0.1975      0.068      2.906      0.211      -0.666       1.061
Before_COVID                       0.0627      0.322      0.195      0.878      -4.031       4.157
Med_Arrest_To_Close               -0.0044      0.002     -2.909      0.211      -0.024       0.015
Med_Arrest_To_Close_Conviction    -0.0088      0.006     -1.503      0.374      -0.083       0.065
Med_Arrest_To_Close_Dismissal      0.0005      0.003      0.177      0.888      -0.036       0.037
Boudin:Year                        0.0004      0.127      0.003      0.998      -1.620       1.620
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                           1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [69]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.894
Model:                            GLS   Adj. R-squared:                  0.815
Method:                 Least Squares   F-statistic:                     11.30
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0201
Time:                        23:43:40   Log-Likelihood:                 11.401
No. Observations:                   8   AIC:                            -14.80
Df Residuals:                       4   BIC:                            -14.48
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    -117.9801     52.489     -2.248      0.088    -263.712      27.751
Boudin        202.7657    128.783      1.574      0.190    -154.792     560.324
Year            0.0628      0.026      2.413      0.073      -0.009       0.135
Boudin:Year    -0.1006      0.064     -1.578      0.190      -0.278       0.076
==============================================================================
Omnibus:                        2.111   Durbin-Watson:                   2.625
Prob(Omnibus):                  0.348   Jarque-Bera (JB):                1.254
Skew:                          -0.868   Prob(JB):                        0.534
Kurtosis:                       2.133   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [62]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.935
Model:                            GLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                     19.22
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00772
Time:                        23:40:43   Log-Likelihood:                 6.7971
No. Observations:                   8   AIC:                            -5.594
Df Residuals:                       4   BIC:                            -5.276
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -2.2724     93.324     -0.024      0.982    -261.381     256.836
Boudin        359.9835    228.973      1.572      0.191    -275.749     995.716
Year            0.0051      0.046      0.111      0.917      -0.123       0.134
Boudin:Year    -0.1785      0.113     -1.575      0.190      -0.493       0.136
==============================================================================
Omnibus:                        2.275   Durbin-Watson:                   2.623
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                1.333
Skew:                          -0.903   Prob(JB):                        0.514
Kurtosis:                       2.140   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [63]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.921
Model:                              GLS   Adj. R-squared:                  0.863
Method:                   Least Squares   F-statistic:                     15.64
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):             0.0113
Time:                          23:40:58   Log-Likelihood:                -49.721
No. Observations:                     8   AIC:                             107.4
Df Residuals:                         4   BIC:                             107.8
Df Model:                             3
Covariance Type:              nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -2.928e+05   1.09e+05     -2.682      0.055   -5.96e+05    1.03e+04
Boudin      -1.928e+05   2.68e+05     -0.720      0.511   -9.37e+05    5.51e+05
Year          145.5000     54.133      2.688      0.055      -4.798     295.798
Boudin:Year    95.5000    132.599      0.720      0.511    -272.654     463.654
==============================================================================
Omnibus:                        0.071   Durbin-Watson:                   1.655
Prob(Omnibus):                  0.965   Jarque-Bera (JB):                0.294
Skew:                           0.056   Prob(JB):                        0.863
Kurtosis:                       2.068   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [66]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.969
Model:                             GLS   Adj. R-squared:                  0.945
Method:                  Least Squares   F-statistic:                     41.39
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00181
Time:                         23:41:43   Log-Likelihood:                -34.104
No. Observations:                    8   AIC:                             76.21
Df Residuals:                        4   BIC:                             76.53
Df Model:                            3
Covariance Type:             nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -3.268e+04   1.55e+04     -2.108      0.103   -7.57e+04    1.04e+04
Boudin      -4.777e+04    3.8e+04     -1.256      0.277   -1.53e+05    5.78e+04
Year           16.3000      7.686      2.121      0.101      -5.040      37.640
Boudin:Year    23.7000     18.827      1.259      0.277     -28.571      75.971
==============================================================================
Omnibus:                        5.766   Durbin-Watson:                   3.016
Prob(Omnibus):                  0.056   Jarque-Bera (JB):                1.651
Skew:                           1.070   Prob(JB):                        0.438
Kurtosis:                       3.609   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [70]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.994
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     211.2
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):           7.37e-05
Time:                                    23:44:25   Log-Likelihood:                -25.053
No. Observations:                               8   AIC:                             58.11
Df Residuals:                                   4   BIC:                             58.42
Df Model:                                       3
Covariance Type:                        nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -2.888e+04   5000.643     -5.774      0.004   -4.28e+04    -1.5e+04
Boudin      -1.326e+04   1.23e+04     -1.081      0.341   -4.73e+04    2.08e+04
Year           14.4000      2.479      5.808      0.004       7.517      21.283
Boudin:Year     6.6000      6.073      1.087      0.338     -10.261      23.461
==============================================================================
Omnibus:                        4.686   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                1.410
Skew:                           1.015   Prob(JB):                        0.494
Kurtosis:                       3.327   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [71]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.914
Model:                                       GLS   Adj. R-squared:                  0.862
Method:                            Least Squares   F-statistic:                     17.68
Date:                           Sun, 24 Sep 2023   Prob (F-statistic):            0.00430
Time:                                   23:44:36   Log-Likelihood:                -39.150
No. Observations:                              9   AIC:                             86.30
Df Residuals:                                  5   BIC:                             87.09
Df Model:                                      3
Covariance Type:                       nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -4.918e+04   8025.173     -6.128      0.002   -6.98e+04   -2.85e+04
Boudin        9.19e+04   3.68e+04      2.495      0.055   -2771.855    1.87e+05
Year           24.4750      3.977      6.154      0.002      14.252      34.698
Boudin:Year   -45.4750     18.224     -2.495      0.055     -92.321       1.371
==============================================================================
Omnibus:                        3.700   Durbin-Watson:                   1.328
Prob(Omnibus):                  0.157   Jarque-Bera (JB):                1.427
Skew:                          -0.975   Prob(JB):                        0.490
Kurtosis:                       3.046   Cond. No.                     9.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [72]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.991
Model:                            GLS   Adj. R-squared:                  0.964
Method:                 Least Squares   F-statistic:                     36.52
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0269
Time:                        23:44:56   Log-Likelihood:                 22.798
No. Observations:                   9   AIC:                            -31.60
Df Residuals:                       2   BIC:                            -30.22
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -412.8776     69.574     -5.934      0.027    -712.230    -113.525
Boudin                            71.8064    153.049      0.469      0.685    -586.712     730.325
Year                               0.2099      0.035      6.063      0.026       0.061       0.359
Med_Arrest_To_Close               -0.0027      0.001     -3.114      0.089      -0.006       0.001
Med_Arrest_To_Close_Conviction    -0.0065      0.003     -1.947      0.191      -0.021       0.008
Med_Arrest_To_Close_Dismissal     -0.0015      0.002     -0.955      0.441      -0.008       0.005
Boudin:Year                       -0.0353      0.076     -0.466      0.687      -0.361       0.291
==============================================================================
Omnibus:                        1.917   Durbin-Watson:                   2.634
Prob(Omnibus):                  0.383   Jarque-Bera (JB):                1.134
Skew:                           0.808   Prob(JB):                        0.567
Kurtosis:                       2.354   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [73]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     113.1
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00879
Time:                        23:45:09   Log-Likelihood:                 21.081
No. Observations:                   9   AIC:                            -28.16
Df Residuals:                       2   BIC:                            -26.78
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -401.6094     84.202     -4.770      0.041    -763.903     -39.316
Boudin                             2.1279    185.229      0.011      0.992    -794.850     799.106
Year                               0.2043      0.042      4.875      0.040       0.024       0.385
Med_Arrest_To_Close               -0.0045      0.001     -4.278      0.051      -0.009    2.54e-05
Med_Arrest_To_Close_Conviction    -0.0091      0.004     -2.261      0.152      -0.026       0.008
Med_Arrest_To_Close_Dismissal      0.0003      0.002      0.153      0.892      -0.008       0.008
Boudin:Year                       -0.0008      0.092     -0.009      0.994      -0.395       0.394
==============================================================================
Omnibus:                        5.932   Durbin-Watson:                   2.974
Prob(Omnibus):                  0.052   Jarque-Bera (JB):                2.009
Skew:                           1.108   Prob(JB):                        0.366
Kurtosis:                       3.670   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

### 2023 Inclusive

In [75]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_violent = sf_case_resolutions_violent.copy()
sf_cr_violent["Conviction"] = sf_cr_violent["Conviction"].astype(int)

sf_cr_violent['Log_Conviction'] = np.log(sf_cr_violent['Conviction'])
sf_cr_violent['Log_Total'] = np.log(sf_cr_violent['Total'])
sf_cr_violent['Boudin'] = sf_cr_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_violent['Before_COVID'] = sf_cr_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_violent_proj = sf_cr_violent.copy() #Creates defensive copy
sf_cr_violent_proj.iloc[8, 1] = sf_cr_violent_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_violent_proj = sf_cr_violent_proj.drop(9)

# Drops '2023*' Row
sf_cr_violent = sf_cr_violent.drop(9)

# Addresses type issues
sf_cr_violent["Year"] = sf_cr_violent["Year"].astype(int)
sf_cr_violent["Med_Arrest_To_Close"] = sf_cr_violent["Med_Arrest_To_Close"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Conviction"] = sf_cr_violent["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_violent_proj["Year"] = sf_cr_violent_proj["Year"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close"] = sf_cr_violent_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_violent_no2023 = sf_cr_violent[sf_cr_violent["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [78]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.918
Model:                            GLS   Adj. R-squared:                  0.837
Method:                 Least Squares   F-statistic:                     11.23
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0190
Time:                        23:50:13   Log-Likelihood:                 13.774
No. Observations:                   9   AIC:                            -17.55
Df Residuals:                       4   BIC:                            -16.56
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -145.4370     50.255     -2.894      0.044    -284.966      -5.908
Boudin         251.6020    122.997      2.046      0.110     -89.891     593.095
Year             0.0754      0.025      3.034      0.039       0.006       0.144
Before_COVID     0.8510      0.172      4.945      0.008       0.373       1.329
Boudin:Year     -0.1244      0.061     -2.044      0.110      -0.293       0.045
==============================================================================
Omnibus:                        1.268   Durbin-Watson:                   2.030
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.740
Skew:                          -0.295   Prob(JB):                        0.691
Kurtosis:                       1.726   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [79]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.918
Model:                            GLS   Adj. R-squared:                  0.837
Method:                 Least Squares   F-statistic:                     11.23
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0190
Time:                        23:50:21   Log-Likelihood:                 13.774
No. Observations:                   9   AIC:                            -17.55
Df Residuals:                       4   BIC:                            -16.56
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -145.4370     50.255     -2.894      0.044    -284.966      -5.908
Boudin         251.6020    122.997      2.046      0.110     -89.891     593.095
Year             0.0754      0.025      3.034      0.039       0.006       0.144
Before_COVID     0.8510      0.172      4.945      0.008       0.373       1.329
Boudin:Year     -0.1244      0.061     -2.044      0.110      -0.293       0.045
==============================================================================
Omnibus:                        1.268   Durbin-Watson:                   2.030
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.740
Skew:                          -0.295   Prob(JB):                        0.691
Kurtosis:                       1.726   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [80]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.945
Model:                            GLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     17.34
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00860
Time:                        23:50:32   Log-Likelihood:                 9.0607
No. Observations:                   9   AIC:                            -8.121
Df Residuals:                       4   BIC:                            -7.135
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -17.3922     84.846     -0.205      0.848    -252.961     218.177
Boudin         277.3642    207.657      1.336      0.253    -299.184     853.912
Year             0.0116      0.042      0.276      0.797      -0.105       0.128
Before_COVID     0.9808      0.291      3.375      0.028       0.174       1.788
Boudin:Year     -0.1371      0.103     -1.335      0.253      -0.422       0.148
==============================================================================
Omnibus:                        2.005   Durbin-Watson:                   2.499
Prob(Omnibus):                  0.367   Jarque-Bera (JB):                1.242
Skew:                          -0.830   Prob(JB):                        0.537
Kurtosis:                       2.252   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [81]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.945
Model:                            GLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     17.34
Date:                Sun, 24 Sep 2023   Prob (F-statistic):            0.00860
Time:                        23:50:41   Log-Likelihood:                 9.0607
No. Observations:                   9   AIC:                            -8.121
Df Residuals:                       4   BIC:                            -7.135
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -17.3922     84.846     -0.205      0.848    -252.961     218.177
Boudin         277.3642    207.657      1.336      0.253    -299.184     853.912
Year             0.0116      0.042      0.276      0.797      -0.105       0.128
Before_COVID     0.9808      0.291      3.375      0.028       0.174       1.788
Boudin:Year     -0.1371      0.103     -1.335      0.253      -0.422       0.148
==============================================================================
Omnibus:                        2.005   Durbin-Watson:                   2.499
Prob(Omnibus):                  0.367   Jarque-Bera (JB):                1.242
Skew:                          -0.830   Prob(JB):                        0.537
Kurtosis:                       2.252   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [82]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.957
Model:                              GLS   Adj. R-squared:                  0.914
Method:                   Least Squares   F-statistic:                     22.34
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):            0.00535
Time:                          23:50:52   Log-Likelihood:                -42.586
No. Observations:                     9   AIC:                             95.17
Df Residuals:                         4   BIC:                             96.16
Df Model:                             4
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.174e+05   2.64e+04     -4.453      0.011   -1.91e+05   -4.42e+04
Boudin        8.341e+04   6.45e+04      1.293      0.266   -9.57e+04    2.62e+05
Year            58.2000     13.027      4.468      0.011      22.030      94.370
Before_COVID   138.0000     90.256      1.529      0.201    -112.590     388.590
Boudin:Year    -41.2000     31.910     -1.291      0.266    -129.797      47.397
==============================================================================
Omnibus:                        0.257   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.276
Skew:                           0.283   Prob(JB):                        0.871
Kurtosis:                       2.357   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [83]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.957
Model:                              GLS   Adj. R-squared:                  0.914
Method:                   Least Squares   F-statistic:                     22.34
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):            0.00535
Time:                          23:51:06   Log-Likelihood:                -42.586
No. Observations:                     9   AIC:                             95.17
Df Residuals:                         4   BIC:                             96.16
Df Model:                             4
Covariance Type:              nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.174e+05   2.64e+04     -4.453      0.011   -1.91e+05   -4.42e+04
Boudin        8.341e+04   6.45e+04      1.293      0.266   -9.57e+04    2.62e+05
Year            58.2000     13.027      4.468      0.011      22.030      94.370
Before_COVID   138.0000     90.256      1.529      0.201    -112.590     388.590
Boudin:Year    -41.2000     31.910     -1.291      0.266    -129.797      47.397
==============================================================================
Omnibus:                        0.257   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.276
Skew:                           0.283   Prob(JB):                        0.871
Kurtosis:                       2.357   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [84]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.944
Model:                             GLS   Adj. R-squared:                  0.888
Method:                  Least Squares   F-statistic:                     16.82
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00910
Time:                         23:51:15   Log-Likelihood:                -43.391
No. Observations:                    9   AIC:                             96.78
Df Residuals:                        4   BIC:                             97.77
Df Model:                            4
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.694e+04   2.88e+04     -1.629      0.179   -1.27e+05    3.31e+04
Boudin        2.819e+04   7.05e+04      0.400      0.710   -1.68e+05    2.24e+05
Year            23.4000     14.245      1.643      0.176     -16.151      62.951
Before_COVID   -63.0000     98.694     -0.638      0.558    -337.019     211.019
Boudin:Year    -13.9000     34.894     -0.398      0.711    -110.780      82.980
==============================================================================
Omnibus:                        3.483   Durbin-Watson:                   3.459
Prob(Omnibus):                  0.175   Jarque-Bera (JB):                1.108
Skew:                           0.852   Prob(JB):                        0.575
Kurtosis:                       3.232   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [85]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.944
Model:                             GLS   Adj. R-squared:                  0.888
Method:                  Least Squares   F-statistic:                     16.82
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00910
Time:                         23:51:36   Log-Likelihood:                -43.391
No. Observations:                    9   AIC:                             96.78
Df Residuals:                        4   BIC:                             97.77
Df Model:                            4
Covariance Type:             nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.694e+04   2.88e+04     -1.629      0.179   -1.27e+05    3.31e+04
Boudin        2.819e+04   7.05e+04      0.400      0.710   -1.68e+05    2.24e+05
Year            23.4000     14.245      1.643      0.176     -16.151      62.951
Before_COVID   -63.0000     98.694     -0.638      0.558    -337.019     211.019
Boudin:Year    -13.9000     34.894     -0.398      0.711    -110.780      82.980
==============================================================================
Omnibus:                        3.483   Durbin-Watson:                   3.459
Prob(Omnibus):                  0.175   Jarque-Bera (JB):                1.108
Skew:                           0.852   Prob(JB):                        0.575
Kurtosis:                       3.232   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [86]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.965
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     27.18
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):            0.00369
Time:                                    23:52:00   Log-Likelihood:                -40.698
No. Observations:                               9   AIC:                             91.40
Df Residuals:                                   4   BIC:                             92.38
Df Model:                                       4
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.777e+04   2.14e+04     -2.236      0.089   -1.07e+05    1.16e+04
Boudin        6.033e+04   5.23e+04      1.154      0.313   -8.49e+04    2.06e+05
Year            23.8000     10.562      2.253      0.087      -5.525      53.125
Before_COVID   -43.4000     73.177     -0.593      0.585    -246.572     159.772
Boudin:Year    -29.8000     25.872     -1.152      0.314    -101.632      42.032
==============================================================================
Omnibus:                        5.860   Durbin-Watson:                   3.412
Prob(Omnibus):                  0.053   Jarque-Bera (JB):                1.899
Skew:                           1.062   Prob(JB):                        0.387
Kurtosis:                       3.744   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [87]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.965
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     27.18
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):            0.00369
Time:                                    23:52:10   Log-Likelihood:                -40.698
No. Observations:                               9   AIC:                             91.40
Df Residuals:                                   4   BIC:                             92.38
Df Model:                                       4
Covariance Type:                        nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.777e+04   2.14e+04     -2.236      0.089   -1.07e+05    1.16e+04
Boudin        6.033e+04   5.23e+04      1.154      0.313   -8.49e+04    2.06e+05
Year            23.8000     10.562      2.253      0.087      -5.525      53.125
Before_COVID   -43.4000     73.177     -0.593      0.585    -246.572     159.772
Boudin:Year    -29.8000     25.872     -1.152      0.314    -101.632      42.032
==============================================================================
Omnibus:                        5.860   Durbin-Watson:                   3.412
Prob(Omnibus):                  0.053   Jarque-Bera (JB):                1.899
Skew:                           1.062   Prob(JB):                        0.387
Kurtosis:                       3.744   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [88]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.954
Model:                                       GLS   Adj. R-squared:                  0.908
Method:                            Least Squares   F-statistic:                     20.84
Date:                           Sun, 24 Sep 2023   Prob (F-statistic):            0.00610
Time:                                   23:52:21   Log-Likelihood:                -40.196
No. Observations:                              9   AIC:                             90.39
Df Residuals:                                  4   BIC:                             91.38
Df Model:                                      4
Covariance Type:                       nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -9945.3000   2.02e+04     -0.492      0.648    -6.6e+04    4.62e+04
Boudin       -9.785e+04   4.95e+04     -1.979      0.119   -2.35e+05    3.95e+04
Year             5.1000      9.988      0.511      0.637     -22.632      32.832
Before_COVID  -185.0000     69.201     -2.673      0.056    -377.132       7.132
Boudin:Year     48.4000     24.466      1.978      0.119     -19.529     116.329
==============================================================================
Omnibus:                        0.183   Durbin-Watson:                   3.393
Prob(Omnibus):                  0.913   Jarque-Bera (JB):                0.241
Skew:                           0.236   Prob(JB):                        0.886
Kurtosis:                       2.353   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [89]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.969
Model:                            GLS   Adj. R-squared:                  0.751
Method:                 Least Squares   F-statistic:                     4.447
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.350
Time:                        23:52:43   Log-Likelihood:                 18.120
No. Observations:                   9   AIC:                            -20.24
Df Residuals:                       1   BIC:                            -18.66
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -226.4209    142.833     -1.585      0.358   -2041.284    1588.442
Boudin                           223.3978    849.092      0.263      0.836   -1.06e+04     1.1e+04
Year                               0.1160      0.070      1.652      0.347      -0.777       1.009
Before_COVID                       0.3649      1.398      0.261      0.837     -17.393      18.122
Med_Arrest_To_Close                0.0070      0.013      0.543      0.683      -0.157       0.171
Med_Arrest_To_Close_Conviction    -0.0079      0.010     -0.820      0.563      -0.131       0.115
Med_Arrest_To_Close_Dismissal     -0.0032      0.010     -0.324      0.801      -0.127       0.121
Boudin:Year                       -0.1104      0.420     -0.263      0.836      -5.444       5.224
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [90]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.969
Model:                            GLS   Adj. R-squared:                  0.751
Method:                 Least Squares   F-statistic:                     4.447
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.350
Time:                        23:52:54   Log-Likelihood:                 18.120
No. Observations:                   9   AIC:                            -20.24
Df Residuals:                       1   BIC:                            -18.66
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -226.4209    142.833     -1.585      0.358   -2041.284    1588.442
Boudin                           223.3978    849.092      0.263      0.836   -1.06e+04     1.1e+04
Year                               0.1160      0.070      1.652      0.347      -0.777       1.009
Before_COVID                       0.3649      1.398      0.261      0.837     -17.393      18.122
Med_Arrest_To_Close                0.0070      0.013      0.543      0.683      -0.157       0.171
Med_Arrest_To_Close_Conviction    -0.0079      0.010     -0.820      0.563      -0.131       0.115
Med_Arrest_To_Close_Dismissal     -0.0032      0.010     -0.324      0.801      -0.127       0.121
Boudin:Year                       -0.1104      0.420     -0.263      0.836      -5.444       5.224
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [91]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     22.70
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.160
Time:                        23:53:04   Log-Likelihood:                 18.805
No. Observations:                   9   AIC:                            -21.61
Df Residuals:                       1   BIC:                            -20.03
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -202.3983    132.367     -1.529      0.369   -1884.274    1479.478
Boudin                           363.1586    786.873      0.462      0.725   -9635.012    1.04e+04
Year                               0.1042      0.065      1.600      0.356      -0.723       0.931
Before_COVID                       0.2721      1.295      0.210      0.868     -16.184      16.728
Med_Arrest_To_Close                0.0105      0.012      0.873      0.543      -0.142       0.163
Med_Arrest_To_Close_Conviction    -0.0133      0.009     -1.479      0.378      -0.127       0.101
Med_Arrest_To_Close_Dismissal     -0.0043      0.009     -0.474      0.718      -0.119       0.110
Boudin:Year                       -0.1795      0.389     -0.461      0.725      -5.123       4.764
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [92]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     22.70
Date:                Sun, 24 Sep 2023   Prob (F-statistic):              0.160
Time:                        23:53:16   Log-Likelihood:                 18.805
No. Observations:                   9   AIC:                            -21.61
Df Residuals:                       1   BIC:                            -20.03
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -202.3983    132.367     -1.529      0.369   -1884.274    1479.478
Boudin                           363.1586    786.873      0.462      0.725   -9635.012    1.04e+04
Year                               0.1042      0.065      1.600      0.356      -0.723       0.931
Before_COVID                       0.2721      1.295      0.210      0.868     -16.184      16.728
Med_Arrest_To_Close                0.0105      0.012      0.873      0.543      -0.142       0.163
Med_Arrest_To_Close_Conviction    -0.0133      0.009     -1.479      0.378      -0.127       0.101
Med_Arrest_To_Close_Dismissal     -0.0043      0.009     -0.474      0.718      -0.119       0.110
Boudin:Year                       -0.1795      0.389     -0.461      0.725      -5.123       4.764
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [93]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.889
Model:                            GLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     10.73
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0220
Time:                        23:53:55   Log-Likelihood:                 11.773
No. Observations:                   8   AIC:                            -15.55
Df Residuals:                       4   BIC:                            -15.23
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    -144.5860     50.105     -2.886      0.045    -283.701      -5.471
Boudin        250.7510    122.936      2.040      0.111     -90.573     592.075
Year            0.0754      0.025      3.034      0.039       0.006       0.144
Boudin:Year    -0.1244      0.061     -2.044      0.110      -0.293       0.045
==============================================================================
Omnibus:                        1.991   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.370   Jarque-Bera (JB):                0.820
Skew:                          -0.278   Prob(JB):                        0.664
Kurtosis:                       1.534   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [94]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.862
Method:                 Least Squares   F-statistic:                     15.60
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0113
Time:                        23:54:05   Log-Likelihood:                 7.5828
No. Observations:                   8   AIC:                            -7.166
Df Residuals:                       4   BIC:                            -6.848
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     -16.4114     84.594     -0.194      0.856    -251.281     218.459
Boudin        276.3834    207.554      1.332      0.254    -299.879     852.646
Year            0.0116      0.042      0.276      0.797      -0.105       0.128
Boudin:Year    -0.1371      0.103     -1.335      0.253      -0.422       0.148
==============================================================================
Omnibus:                        1.840   Durbin-Watson:                   2.404
Prob(Omnibus):                  0.399   Jarque-Bera (JB):                1.148
Skew:                          -0.782   Prob(JB):                        0.563
Kurtosis:                       2.002   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [95]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.953
Model:                              GLS   Adj. R-squared:                  0.918
Method:                   Least Squares   F-statistic:                     27.14
Date:                  Sun, 24 Sep 2023   Prob (F-statistic):            0.00405
Time:                          23:54:16   Log-Likelihood:                -38.326
No. Observations:                     8   AIC:                             84.65
Df Residuals:                         4   BIC:                             84.97
Df Model:                             3
Covariance Type:              nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -1.172e+05   2.63e+04     -4.461      0.011    -1.9e+05   -4.43e+04
Boudin       8.327e+04   6.45e+04      1.292      0.266   -9.57e+04    2.62e+05
Year           58.2000     13.027      4.468      0.011      22.030      94.370
Boudin:Year   -41.2000     31.910     -1.291      0.266    -129.797      47.397
==============================================================================
Omnibus:                        0.244   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.885   Jarque-Bera (JB):                0.368
Skew:                           0.267   Prob(JB):                        0.832
Kurtosis:                       2.095   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [96]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.940
Model:                             GLS   Adj. R-squared:                  0.894
Method:                  Least Squares   F-statistic:                     20.71
Date:                 Sun, 24 Sep 2023   Prob (F-statistic):            0.00672
Time:                         23:54:25   Log-Likelihood:                -39.041
No. Observations:                    8   AIC:                             86.08
Df Residuals:                        4   BIC:                             86.40
Df Model:                            3
Covariance Type:             nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     -4.7e+04   2.87e+04     -1.636      0.177   -1.27e+05    3.28e+04
Boudin       2.825e+04   7.05e+04      0.401      0.709   -1.67e+05    2.24e+05
Year           23.4000     14.245      1.643      0.176     -16.151      62.951
Boudin:Year   -13.9000     34.894     -0.398      0.711    -110.780      82.980
==============================================================================
Omnibus:                        2.570   Durbin-Watson:                   3.321
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                0.865
Skew:                           0.803   Prob(JB):                        0.649
Kurtosis:                       2.873   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [97]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.962
Model:                                        GLS   Adj. R-squared:                  0.934
Method:                             Least Squares   F-statistic:                     33.77
Date:                            Sun, 24 Sep 2023   Prob (F-statistic):            0.00267
Time:                                    23:54:33   Log-Likelihood:                -36.648
No. Observations:                               8   AIC:                             81.30
Df Residuals:                                   4   BIC:                             81.61
Df Model:                                       3
Covariance Type:                        nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -4.782e+04   2.13e+04     -2.245      0.088   -1.07e+05    1.13e+04
Boudin       6.037e+04   5.23e+04      1.155      0.312   -8.48e+04    2.05e+05
Year           23.8000     10.562      2.253      0.087      -5.525      53.125
Boudin:Year   -29.8000     25.872     -1.152      0.314    -101.632      42.032
==============================================================================
Omnibus:                        4.614   Durbin-Watson:                   3.261
Prob(Omnibus):                  0.100   Jarque-Bera (JB):                1.372
Skew:                           1.001   Prob(JB):                        0.504
Kurtosis:                       3.328   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [98]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit()
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.872
Model:                                       GLS   Adj. R-squared:                  0.796
Method:                            Least Squares   F-statistic:                     11.40
Date:                           Sun, 24 Sep 2023   Prob (F-statistic):             0.0113
Time:                                   23:54:45   Log-Likelihood:                -44.808
No. Observations:                              9   AIC:                             97.62
Df Residuals:                                  5   BIC:                             98.40
Df Model:                                      3
Covariance Type:                       nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -5.677e+04    1.5e+04     -3.772      0.013   -9.54e+04   -1.81e+04
Boudin      -5.103e+04   6.91e+04     -0.739      0.493   -2.29e+05    1.26e+05
Year           28.2250      7.457      3.785      0.013       9.057      47.393
Boudin:Year    25.2750     34.171      0.740      0.493     -62.565     113.115
==============================================================================
Omnibus:                        0.568   Durbin-Watson:                   1.447
Prob(Omnibus):                  0.753   Jarque-Bera (JB):                0.540
Skew:                          -0.268   Prob(JB):                        0.763
Kurtosis:                       1.927   Cond. No.                     9.47e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [99]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     9.694
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0965
Time:                        23:54:58   Log-Likelihood:                 17.823
No. Observations:                   9   AIC:                            -21.65
Df Residuals:                       2   BIC:                            -20.27
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -201.0829     76.590     -2.625      0.120    -530.622     128.456
Boudin                            12.9738    195.305      0.066      0.953    -827.356     853.304
Year                               0.1037      0.038      2.724      0.112      -0.060       0.268
Med_Arrest_To_Close                0.0102      0.003      3.090      0.091      -0.004       0.024
Med_Arrest_To_Close_Conviction    -0.0100      0.004     -2.554      0.125      -0.027       0.007
Med_Arrest_To_Close_Dismissal     -0.0057      0.001     -4.986      0.038      -0.011      -0.001
Boudin:Year                       -0.0064      0.097     -0.066      0.954      -0.422       0.409
==============================================================================
Omnibus:                        4.996   Durbin-Watson:                   2.889
Prob(Omnibus):                  0.082   Jarque-Bera (JB):                1.384
Skew:                          -0.875   Prob(JB):                        0.501
Kurtosis:                       3.793   Cond. No.                     1.89e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.89e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [100]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.993
Model:                            GLS   Adj. R-squared:                  0.974
Method:                 Least Squares   F-statistic:                     50.71
Date:                Sun, 24 Sep 2023   Prob (F-statistic):             0.0195
Time:                        23:55:07   Log-Likelihood:                 18.610
No. Observations:                   9   AIC:                            -23.22
Df Residuals:                       2   BIC:                            -21.84
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -183.5002     70.175     -2.615      0.120    -485.439     118.439
Boudin                           206.2158    178.948      1.152      0.368    -563.734     976.166
Year                               0.0950      0.035      2.722      0.113      -0.055       0.245
Med_Arrest_To_Close                0.0128      0.003      4.246      0.051      -0.000       0.026
Med_Arrest_To_Close_Conviction    -0.0148      0.004     -4.119      0.054      -0.030       0.001
Med_Arrest_To_Close_Dismissal     -0.0062      0.001     -5.910      0.027      -0.011      -0.002
Boudin:Year                       -0.1019      0.088     -1.151      0.369      -0.483       0.279
==============================================================================
Omnibus:                        5.313   Durbin-Watson:                   2.816
Prob(Omnibus):                  0.070   Jarque-Bera (JB):                1.439
Skew:                          -0.860   Prob(JB):                        0.487
Kurtosis:                       3.938   Cond. No.                     1.89e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.89e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "