In [ ]:
# !pip install firebase-admin

# Load in Data & Libraries

In [10]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from scipy import stats
import warnings
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.diagnostic import linear_lm
import sklearn
from sklearn.model_selection import train_test_split
from datetime import datetime
# Initialize the Firebase app with your service account key
cred = credentials.Certificate(r'PRIVATE-KEY-sf-da-analysis-firebase.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://sf-da-analysis-6f156-default-rtdb.firebaseio.com/'
})

In [ ]:
# For sf_prosecutions
# Get a reference to the Firebase Realtime Database
ref = db.reference('/District_Attorney_Cases_Prosecuted_2014_2023')

# Load data from the collection
sf_prosecutions = ref.get()

# Process the loaded data & converts it to a df
sf_prosecutions = pd.json_normalize(sf_prosecutions)
sf_prosecutions = sf_prosecutions.drop('id', axis=1)

# For sf_case_resolutions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_All_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_all = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_all = pd.json_normalize(sf_case_resolutions_all)
sf_case_resolutions_all = sf_case_resolutions_all.drop('id', axis=1)

# For sf_case_resolutions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_Violent_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_violent = pd.json_normalize(sf_case_resolutions_violent)
sf_case_resolutions_violent = sf_case_resolutions_violent.drop('id', axis=1)

# For sf_da_actions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_All_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_all = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_all = pd.json_normalize(sf_da_actions_all)
sf_da_actions_all = sf_da_actions_all.drop('id', axis=1)

# For sf_da_actions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_Violent_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_violent = pd.json_normalize(sf_da_actions_violent)
sf_da_actions_violent = sf_da_actions_violent.drop('id', axis=1)

# For sfpd_incidents_outcomes_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Outcomes_of_SFPD_Incidents_All_Crimes_2015_2023')

# Load data from the collection
sfpd_incidents_outcomes_all = ref.get()

# Process the loaded data & converts it to a df
sfpd_incidents_outcomes_all = pd.json_normalize(sfpd_incidents_outcomes_all)
sfpd_incidents_outcomes_all = sfpd_incidents_outcomes_all.drop('id', axis=1)

# For fed_off_by_crime_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_all = pd.json_normalize(fed_off_by_crime_all)
fed_off_by_crime_all = fed_off_by_crime_all.drop('id', axis=1)

# For fed_off_by_crime_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_violent = pd.json_normalize(fed_off_by_crime_violent)
fed_off_by_crime_violent = fed_off_by_crime_violent.drop('id', axis=1)

# For fed_off_by_dist_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_all = pd.json_normalize(fed_off_by_dist_all)
fed_off_by_dist_all = fed_off_by_dist_all.drop('id', axis=1)

# For fed_off_by_dist_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_violent = pd.json_normalize(fed_off_by_dist_violent)
fed_off_by_dist_violent = fed_off_by_dist_violent.drop('id', axis=1)

In [11]:
fed_off_by_dist_all

          Circuit              District  Fiscal_Year      N    Pct
0     Grand Total                 Total         2022  64157  1.000
1      DC Circuit  District of Columbia         2022    312  0.005
2     1st Circuit                 Maine         2022    180  0.003
3     1st Circuit         Massachusetts         2022    466  0.007
4     1st Circuit         New Hampshire         2022    180  0.003
..            ...                   ...          ...    ...    ...
755  11th Circuit     Florida, Northern         2015    255  0.004
756  11th Circuit     Florida, Southern         2015   2238  0.032
757  11th Circuit       Georgia, Middle         2015    377  0.005
758  11th Circuit     Georgia, Northern         2015    592  0.008
759  11th Circuit     Georgia, Southern         2015    420  0.006

[760 rows x 5 columns]

In [12]:
date_format = "%Y-%m-%dT%H:%M:%S.%fZ"

sf_prosecutions['arrest_date'] = pd.to_datetime(sf_prosecutions['arrest_date'], format = date_format)
sf_prosecutions['data_as_of'] = pd.to_datetime(sf_prosecutions['data_as_of'], format = date_format)
sf_prosecutions['data_loaded_at'] = pd.to_datetime(sf_prosecutions['data_loaded_at'], format = date_format)

In [13]:
boudin_start_date = datetime(2020, 1, 8, 0, 0, 0)
boudin_end_date = datetime(2022, 7, 9, 0, 0, 0)
sf_prosecutions_boudin = sf_prosecutions[(sf_prosecutions["arrest_date"] >= boudin_start_date) &
                                         (sf_prosecutions["arrest_date"] < boudin_end_date)]

sf_prosecutions_boudin

,arrest_date,case_status,court_number,crime_type,da_action_taken,data_as_of,data_loaded_at,dv_case,filed_case_type,incident_number,list_of_filed_charges
9383,2020-01-09 08:00:00,Filed Motion to Revoke,2506152,"Forgery, Checks, Access Cards",New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20171107-02506152,470D/F/0
9384,2020-01-30 08:00:00,Filed Motion to Revoke,2520522,Theft,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20200115-02520522,"487C/F/0, 245A4/M/0"
9385,2020-01-14 08:00:00,Filed Motion to Revoke,14005420,Assault,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,Yes,MTR,140153084,"591.5/M/0, 273.5A/F/0, 273.5A/F/0, 273.5A/F/0,..."
9386,2020-01-22 08:00:00,Filed Motion to Revoke,15018930,Robbery,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150735638,"242/M/0, 245A4/F/0, 243B/M/0, 211/F/2"
9387,2020-01-16 08:00:00,Filed Motion to Revoke,15026261,Narcotics,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150025953,"11378/F/0, 11377/M/0, 23123A/I/0"
...,...,...,...,...,...,...,...,...,...,...,...
99090,2022-06-24 07:00:00,,2530936,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,23-00344,
99091,2022-06-13 07:00:00,Pending,2530799,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,Z20220613-02530799,
99092,2022-07-06 07:00:00,Fugitive Status,22006648,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,Felony,220445185,"664/1085A/F/0, 664/496DA/F/0"
99096,2022-07-04 07:00:00,Pled Guilty to Other Case or Other DA Action,22006556,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220438726,
99097,2022-07-04 07:00:00,,22006565,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220437825,

# PART I - Boudin v National Trends (Fixed Effects)

## All Crimes

In [67]:
def year_marker(year, start, end=9999, mode = 'range'):
  # Default of 9999 is used to indicate ongoing
  if mode == 'before':
    try:
      if year < start:
        return 1
      else:
        return 0
    except:
      return 0

  if mode == 'after':
    start += 1 #Increments start by 1

  # Used for both 'after' and 'range' modes
  else:
    try:
      if year >= start and year <= end:
        return 1
      else:
        return 0
    except:
      return 0

In [68]:
fed_off_totals_all = fed_off_by_dist_all[fed_off_by_dist_all["District"] == "Total"].reset_index(drop=True)
fed_off_totals_all = fed_off_totals_all.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_all.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_all.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_all['Log_Total'] = np.log(fed_off_totals_all['Total'])
fed_off_totals_all['Boudin'] = 0
fed_off_totals_all['SF'] = 0
fed_off_totals_all['Before_COVID'] = fed_off_totals_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_all

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022  64157  11.069088       0   0             0
1  2021  57304  10.956126       0   0             0
2  2020  64591  11.075830       0   0             0
3  2019  76593  11.246261       0   0             1
4  2018  69470  11.148650       0   0             1
5  2017  66899  11.110939       0   0             1
6  2016  67794  11.124229       0   0             1
7  2015  71030  11.170858       0   0             1

In [69]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions = sf_case_resolutions_all[["Year", "Conviction"]]
sfda_convictions["Conviction"] = sfda_convictions["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions['Log_Total'] = np.log(sfda_convictions['Total'])
sfda_convictions['Boudin'] = sfda_convictions.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions['SF'] = 1
sfda_convictions['Before_COVID'] = sfda_convictions.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_proj = sfda_convictions.copy() #Creates defensive copy
sfda_convictions_proj.iloc[8, 1] = sfda_convictions_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_proj = sfda_convictions_proj.drop(9)

# Drops '2023*' Row
sfda_convictions = sfda_convictions.drop(9)

sfda_convictions["Year"] = sfda_convictions["Year"].astype(int)
sfda_convictions_proj["Year"] = sfda_convictions_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [70]:
# Concatenate vertically (along rows)
sf_fed_off_totals = pd.concat([fed_off_totals_all, sfda_convictions], axis=0)
sf_fed_off_totals_proj = pd.concat([fed_off_totals_all, sfda_convictions_proj], axis=0)

# Reset the index
sf_fed_off_totals = sf_fed_off_totals.reset_index(drop=True)
sf_fed_off_totals_proj = sf_fed_off_totals_proj.reset_index(drop=True)

sf_fed_off_totals

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0
16  2023   1342   7.201916       0   1             0

### 2023 Inclusive

In [101]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     552.8
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.72e-13
Time:                        00:48:11   Log-Likelihood:                -156.76
No. Observations:                  17   AIC:                             323.5
Df Residuals:                      12   BIC:                             327.7
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.418e+06   1.33e+06     -1.066      0.286   -4.02e+06    1.19e+06
Year           732.9386    657.868      1.114      0.265    -556.459    2022.337
Boudin        4473.8070   2477.889      1.805      0.071    -382.765    9330.379
SF           -6.588e+04   1731.803    -38.043      0.000   -6.93e+04   -6.25e+04
Before_COVID  9774.9474   4367.214      2.238      0.025    1215.366    1.83e+04
==============================================================================
Omnibus:                        1.133   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.568   Jarque-Bera (JB):                0.112
Skew:                          -0.032   Prob(JB):                        0.945
Kurtosis:                       3.393   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [102]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     410.1
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.02e-12
Time:                        00:48:16   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     74.539      1.211      0.226     -55.831     236.358
Year            -0.0393      0.037     -1.064      0.287      -0.112       0.033
Boudin          -0.3656      0.231     -1.586      0.113      -0.817       0.086
SF              -3.2094      0.125    -25.748      0.000      -3.454      -2.965
Before_COVID     0.1870      0.174      1.075      0.282      -0.154       0.528
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [105]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     536.0
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           2.07e-13
Time:                        00:48:41   Log-Likelihood:                -157.04
No. Observations:                  17   AIC:                             324.1
Df Residuals:                      12   BIC:                             328.3
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -1.47e+06   1.35e+06     -1.091      0.275   -4.11e+06    1.17e+06
Year           758.6404    666.387      1.138      0.255    -547.454    2064.735
Boudin        4247.6316   2565.171      1.656      0.098    -780.011    9275.274
SF           -6.576e+04   1770.582    -37.140      0.000   -6.92e+04   -6.23e+04
Before_COVID  9713.2632   4389.363      2.213      0.027    1110.269    1.83e+04
==============================================================================
Omnibus:                        1.053   Durbin-Watson:                   1.975
Prob(Omnibus):                  0.591   Jarque-Bera (JB):                0.091
Skew:                          -0.028   Prob(JB):                        0.956
Kurtosis:                       3.353   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [108]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     410.1
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.02e-12
Time:                        00:49:04   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     74.539      1.211      0.226     -55.831     236.358
Year            -0.0393      0.037     -1.064      0.287      -0.112       0.033
Boudin          -0.3656      0.231     -1.586      0.113      -0.817       0.086
SF              -3.2094      0.125    -25.748      0.000      -3.454      -2.965
Before_COVID     0.1870      0.174      1.075      0.282      -0.154       0.528
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [75]:
# Drops '2023' Row
sf_fed_off_totals_no2023 = sf_fed_off_totals[sf_fed_off_totals["Year"] != 2023]
sf_fed_off_totals_no2023

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0

In [76]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.995
Model:                            GLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     533.0
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.65e-12
Time:                        00:34:37   Log-Likelihood:                -146.75
No. Observations:                  16   AIC:                             303.5
Df Residuals:                      11   BIC:                             307.4
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -9.466e+05   1.16e+06     -0.817      0.431    -3.5e+06     1.6e+06
Year           499.0833    573.186      0.871      0.403    -762.491    1760.658
Boudin        6531.7333   2900.118      2.252      0.046     148.616    1.29e+04
SF           -6.701e+04   1775.953    -37.729      0.000   -7.09e+04   -6.31e+04
Before_COVID  1.034e+04   3076.040      3.360      0.006    3565.882    1.71e+04
==============================================================================
Omnibus:                        0.910   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.634   Jarque-Bera (JB):                0.078
Skew:                           0.127   Prob(JB):                        0.962
Kurtosis:                       3.229   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [77]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.996
Model:                            GLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                     740.7
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           2.73e-13
Time:                        00:34:37   Log-Likelihood:                 13.855
No. Observations:                  16   AIC:                            -17.71
Df Residuals:                      11   BIC:                            -13.85
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       21.7086     50.642      0.429      0.676     -89.753     133.170
Year            -0.0053      0.025     -0.211      0.837      -0.060       0.050
Boudin          -0.6647      0.127     -5.243      0.000      -0.944      -0.386
SF              -3.0463      0.078    -39.236      0.000      -3.217      -2.875
Before_COVID     0.1054      0.134      0.784      0.450      -0.191       0.401
==============================================================================
Omnibus:                        3.222   Durbin-Watson:                   2.141
Prob(Omnibus):                  0.200   Jarque-Bera (JB):                1.170
Skew:                           0.498   Prob(JB):                        0.557
Kurtosis:                       3.874   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

In [109]:
fed_off_totals_violent = fed_off_by_dist_violent[fed_off_by_dist_violent["District"] == "Total"].reset_index(drop=True)
fed_off_totals_violent = fed_off_totals_violent.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_violent.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_violent.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_violent['Log_Total'] = np.log(fed_off_totals_violent['Total'])
fed_off_totals_violent['Boudin'] = 0
fed_off_totals_violent['SF'] = 0
fed_off_totals_violent['Before_COVID'] = fed_off_totals_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_violent

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022   4417   8.393216       0   0             0
1  2021   3438   8.142645       0   0             0
2  2020   3219   8.076826       0   0             0
3  2019   4326   8.372399       0   0             1
4  2018   3973   8.287277       0   0             1
5  2017   3927   8.275631       0   0             1
6  2016   3816   8.246958       0   0             1
7  2015   3835   8.251925       0   0             1

In [110]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions_violent = sf_case_resolutions_violent[["Year", "Conviction"]]
sfda_convictions_violent["Conviction"] = sfda_convictions_violent["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions_violent.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions_violent['Log_Total'] = np.log(sfda_convictions_violent['Total'])
sfda_convictions_violent['Boudin'] = sfda_convictions_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions_violent['SF'] = 1
sfda_convictions_violent['Before_COVID'] = sfda_convictions_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_violent_proj = sfda_convictions_violent.copy() #Creates defensive copy
sfda_convictions_violent_proj.iloc[8, 1] = sfda_convictions_violent_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_violent_proj = sfda_convictions_violent_proj.drop(9)

# Drops '2023*' Row
sfda_convictions_violent = sfda_convictions_violent.drop(9)

sfda_convictions_violent["Year"] = sfda_convictions_violent["Year"].astype(int)
sfda_convictions_violent_proj["Year"] = sfda_convictions_violent_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [111]:
# Concatenate vertically (along rows)
sf_fed_off_totals_violent = pd.concat([fed_off_totals_violent, sfda_convictions_violent], axis=0)
sf_fed_off_totals_violent_proj = pd.concat([fed_off_totals_violent, sfda_convictions_violent_proj], axis=0)

# Reset the index
sf_fed_off_totals_violent = sf_fed_off_totals_violent.reset_index(drop=True)
sf_fed_off_totals_violent_proj = sf_fed_off_totals_violent_proj.reset_index(drop=True)

sf_fed_off_totals_violent

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0
16  2023    397   5.983936       0   1             0

### 2023 Inclusive

In [119]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.978
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     256.9
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.64e-11
Time:                        00:49:42   Log-Likelihood:                -116.98
No. Observations:                  17   AIC:                             244.0
Df Residuals:                      12   BIC:                             248.1
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.469e+05   9.21e+04     -1.595      0.111   -3.28e+05    3.36e+04
Year            74.4883     45.623      1.633      0.103     -14.931     163.908
Boudin           9.6696    245.857      0.039      0.969    -472.202     491.541
SF           -3090.4561    133.479    -23.153      0.000   -3352.070   -2828.842
Before_COVID   723.1614    266.602      2.713      0.007     200.630    1245.692
==============================================================================
Omnibus:                       16.100   Durbin-Watson:                   1.503
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               14.752
Skew:                           1.665   Prob(JB):                     0.000626
Kurtosis:                       6.120   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [120]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     85.70
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.02e-08
Time:                        00:49:50   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     76.498      0.602      0.547    -103.910     195.958
Year            -0.0188      0.038     -0.496      0.620      -0.093       0.055
Boudin          -0.2319      0.247     -0.940      0.347      -0.715       0.251
SF              -1.5740      0.137    -11.514      0.000      -1.842      -1.306
Before_COVID     0.2509      0.155      1.616      0.106      -0.053       0.555
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [121]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     362.7
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           2.12e-12
Time:                        00:49:57   Log-Likelihood:                -116.27
No. Observations:                  17   AIC:                             242.5
Df Residuals:                      12   BIC:                             246.7
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.622e+05   8.96e+04     -1.810      0.070   -3.38e+05    1.34e+04
Year            82.0760     44.363      1.850      0.064      -4.873     169.025
Boudin         -57.1023    227.927     -0.251      0.802    -503.830     389.626
SF           -3054.0351    120.200    -25.408      0.000   -3289.624   -2818.447
Before_COVID   704.9509    274.136      2.572      0.010     167.655    1242.247
==============================================================================
Omnibus:                       15.300   Durbin-Watson:                   1.621
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               13.494
Skew:                           1.612   Prob(JB):                      0.00117
Kurtosis:                       5.942   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [122]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     85.70
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.02e-08
Time:                        00:50:05   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     76.498      0.602      0.547    -103.910     195.958
Year            -0.0188      0.038     -0.496      0.620      -0.093       0.055
Boudin          -0.2319      0.247     -0.940      0.347      -0.715       0.251
SF              -1.5740      0.137    -11.514      0.000      -1.842      -1.306
Before_COVID     0.2509      0.155      1.616      0.106      -0.053       0.555
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [123]:
# Drops '2023' Row
sf_fed_off_totals_violent_no2023 = sf_fed_off_totals_violent[sf_fed_off_totals_violent["Year"] != 2023]
sf_fed_off_totals_violent_no2023

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0

In [126]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     468.8
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           3.33e-12
Time:                        00:50:29   Log-Likelihood:                -109.36
No. Observations:                  16   AIC:                             228.7
Df Residuals:                      11   BIC:                             232.6
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.914e+05   1.02e+05     -1.882      0.060   -3.91e+05    7899.103
Year            96.5417     50.369      1.917      0.055      -2.181     195.264
Boudin        -184.4000    340.899     -0.541      0.589    -852.550     483.750
SF           -2984.6000     91.138    -32.748      0.000   -3163.227   -2805.973
Before_COVID   670.2333    322.479      2.078      0.038      38.186    1302.281
==============================================================================
Omnibus:                        8.179   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                4.835
Skew:                           1.094   Prob(JB):                       0.0892
Kurtosis:                       4.569   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [127]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.986
Model:                            GLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     365.5
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           1.30e-11
Time:                        00:50:39   Log-Likelihood:                 14.123
No. Observations:                  16   AIC:                            -18.25
Df Residuals:                      11   BIC:                            -14.38
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -30.7100     39.446     -0.779      0.436    -108.023      46.603
Year             0.0193      0.020      0.986      0.324      -0.019       0.058
Boudin          -0.5667      0.150     -3.785      0.000      -0.860      -0.273
SF              -1.3914      0.044    -31.383      0.000      -1.478      -1.305
Before_COVID     0.1596      0.105      1.515      0.130      -0.047       0.366
==============================================================================
Omnibus:                        1.663   Durbin-Watson:                   2.070
Prob(Omnibus):                  0.435   Jarque-Bera (JB):                0.790
Skew:                           0.544   Prob(JB):                        0.674
Kurtosis:                       2.994   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# PART II - SF Before & After Boudin Takes Office (DID)

## All Crimes

### 2023 Inclusive

In [129]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_all = sf_case_resolutions_all.copy()
sf_cr_all["Conviction"] = sf_cr_all["Conviction"].astype(int)

sf_cr_all['Log_Conviction'] = np.log(sf_cr_all['Conviction'])
sf_cr_all['Log_Total'] = np.log(sf_cr_all['Total'])
sf_cr_all['Boudin'] = sf_cr_all.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_all['Before_COVID'] = sf_cr_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_all_proj = sf_cr_all.copy() #Creates defensive copy
sf_cr_all_proj.iloc[8, 1] = sf_cr_all_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_all_proj = sf_cr_all_proj.drop(9)

# Drops '2023*' Row
sf_cr_all = sf_cr_all.drop(9)

# Addresses type issues
sf_cr_all["Year"] = sf_cr_all["Year"].astype(int)
sf_cr_all["Med_Arrest_To_Close"] = sf_cr_all["Med_Arrest_To_Close"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Conviction"] = sf_cr_all["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Dismissal"] = sf_cr_all["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_all_proj["Year"] = sf_cr_all_proj["Year"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close"] = sf_cr_all_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_all_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_all_no2023 = sf_cr_all[sf_cr_all["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [130]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.926
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     73.89
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000530
Time:                        00:51:36   Log-Likelihood:                 13.356
No. Observations:                   9   AIC:                            -16.71
Df Residuals:                       4   BIC:                            -15.73
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -118.8283     31.709     -3.747      0.000    -180.977     -56.680
Boudin         203.6139    118.080      1.724      0.085     -27.819     435.047
Year             0.0628      0.016      4.007      0.000       0.032       0.094
Before_COVID     0.8483      0.094      9.066      0.000       0.665       1.032
Boudin:Year     -0.1006      0.058     -1.722      0.085      -0.215       0.014
==============================================================================
Omnibus:                        2.481   Durbin-Watson:                   2.729
Prob(Omnibus):                  0.289   Jarque-Bera (JB):                1.405
Skew:                          -0.920   Prob(JB):                        0.495
Kurtosis:                       2.399   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [145]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.926
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     73.89
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000530
Time:                        00:51:47   Log-Likelihood:                 13.356
No. Observations:                   9   AIC:                            -16.71
Df Residuals:                       4   BIC:                            -15.73
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -118.8283     31.709     -3.747      0.000    -180.977     -56.680
Boudin         203.6139    118.080      1.724      0.085     -27.819     435.047
Year             0.0628      0.016      4.007      0.000       0.032       0.094
Before_COVID     0.8483      0.094      9.066      0.000       0.665       1.032
Boudin:Year     -0.1006      0.058     -1.722      0.085      -0.215       0.014
==============================================================================
Omnibus:                        2.481   Durbin-Watson:                   2.729
Prob(Omnibus):                  0.289   Jarque-Bera (JB):                1.405
Skew:                          -0.920   Prob(JB):                        0.495
Kurtosis:                       2.399   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [146]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.948
Model:                            GLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     70.03
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000589
Time:                        00:51:56   Log-Likelihood:                 8.1767
No. Observations:                   9   AIC:                            -6.353
Df Residuals:                       4   BIC:                            -5.367
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -3.2153     54.282     -0.059      0.953    -109.606     103.176
Boudin         360.9264    206.046      1.752      0.080     -42.915     764.768
Year             0.0051      0.027      0.192      0.848      -0.047       0.058
Before_COVID     0.9429      0.177      5.318      0.000       0.595       1.290
Boudin:Year     -0.1785      0.102     -1.751      0.080      -0.378       0.021
==============================================================================
Omnibus:                        2.677   Durbin-Watson:                   2.723
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.506
Skew:                          -0.957   Prob(JB):                        0.471
Kurtosis:                       2.408   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [155]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.948
Model:                            GLS   Adj. R-squared:                  0.897
Method:                 Least Squares   F-statistic:                     70.03
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000589
Time:                        00:53:26   Log-Likelihood:                 8.1767
No. Observations:                   9   AIC:                            -6.353
Df Residuals:                       4   BIC:                            -5.367
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -3.2153     54.282     -0.059      0.953    -109.606     103.176
Boudin         360.9264    206.046      1.752      0.080     -42.915     764.768
Year             0.0051      0.027      0.192      0.848      -0.047       0.058
Before_COVID     0.9429      0.177      5.318      0.000       0.595       1.290
Boudin:Year     -0.1785      0.102     -1.751      0.080      -0.378       0.021
==============================================================================
Omnibus:                        2.677   Durbin-Watson:                   2.723
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.506
Skew:                          -0.957   Prob(JB):                        0.471
Kurtosis:                       2.408   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [159]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.923
Model:                              GLS   Adj. R-squared:                  0.846
Method:                   Least Squares   F-statistic:                     30.43
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):            0.00297
Time:                          00:54:21   Log-Likelihood:                -55.406
No. Observations:                     9   AIC:                             120.8
Df Residuals:                         4   BIC:                             121.8
Df Model:                             4
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.932e+05   1.51e+05     -1.945      0.052   -5.89e+05    2186.166
Boudin       -1.924e+05   1.66e+05     -1.156      0.248   -5.19e+05    1.34e+05
Year           145.5000     74.505      1.953      0.051      -0.527     291.527
Before_COVID   402.6000    464.269      0.867      0.386    -507.350    1312.550
Boudin:Year     95.5000     82.317      1.160      0.246     -65.838     256.838
==============================================================================
Omnibus:                        0.017   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.175
Skew:                           0.059   Prob(JB):                        0.916
Kurtosis:                       2.327   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [160]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.923
Model:                              GLS   Adj. R-squared:                  0.846
Method:                   Least Squares   F-statistic:                     30.43
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):            0.00297
Time:                          00:54:29   Log-Likelihood:                -55.406
No. Observations:                     9   AIC:                             120.8
Df Residuals:                         4   BIC:                             121.8
Df Model:                             4
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.932e+05   1.51e+05     -1.945      0.052   -5.89e+05    2186.166
Boudin       -1.924e+05   1.66e+05     -1.156      0.248   -5.19e+05    1.34e+05
Year           145.5000     74.505      1.953      0.051      -0.527     291.527
Before_COVID   402.6000    464.269      0.867      0.386    -507.350    1312.550
Boudin:Year     95.5000     82.317      1.160      0.246     -65.838     256.838
==============================================================================
Omnibus:                        0.017   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.175
Skew:                           0.059   Prob(JB):                        0.916
Kurtosis:                       2.327   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [163]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.974
Model:                             GLS   Adj. R-squared:                  0.947
Method:                  Least Squares   F-statistic:                     1432.
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):           1.46e-06
Time:                         00:54:56   Log-Likelihood:                -37.837
No. Observations:                    9   AIC:                             85.67
Df Residuals:                        4   BIC:                             86.66
Df Model:                            4
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.259e+04   4362.298     -7.470      0.000   -4.11e+04    -2.4e+04
Boudin       -4.787e+04   4.17e+04     -1.149      0.251    -1.3e+05    3.38e+04
Year            16.3000      2.156      7.559      0.000      12.074      20.526
Before_COVID   -98.6000     14.953     -6.594      0.000    -127.907     -69.293
Boudin:Year     23.7000     20.619      1.149      0.250     -16.713      64.113
==============================================================================
Omnibus:                        7.138   Durbin-Watson:                   3.174
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                2.355
Skew:                           1.135   Prob(JB):                        0.308
Kurtosis:                       4.060   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [164]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.974
Model:                             GLS   Adj. R-squared:                  0.947
Method:                  Least Squares   F-statistic:                     1432.
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):           1.46e-06
Time:                         00:55:05   Log-Likelihood:                -37.837
No. Observations:                    9   AIC:                             85.67
Df Residuals:                        4   BIC:                             86.66
Df Model:                            4
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.259e+04   4362.298     -7.470      0.000   -4.11e+04    -2.4e+04
Boudin       -4.787e+04   4.17e+04     -1.149      0.251    -1.3e+05    3.38e+04
Year            16.3000      2.156      7.559      0.000      12.074      20.526
Before_COVID   -98.6000     14.953     -6.594      0.000    -127.907     -69.293
Boudin:Year     23.7000     20.619      1.149      0.250     -16.713      64.113
==============================================================================
Omnibus:                        7.138   Durbin-Watson:                   3.174
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                2.355
Skew:                           1.135   Prob(JB):                        0.308
Kurtosis:                       4.060   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [165]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.995
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     300.1
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):           3.30e-05
Time:                                    00:55:16   Log-Likelihood:                -27.654
No. Observations:                               9   AIC:                             65.31
Df Residuals:                                   4   BIC:                             66.30
Df Model:                                       4
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.882e+04   5006.833     -5.756      0.000   -3.86e+04    -1.9e+04
Boudin       -1.331e+04   5765.177     -2.309      0.021   -2.46e+04   -2014.928
Year            14.4000      2.475      5.818      0.000       9.549      19.251
Before_COVID   -56.8000     14.444     -3.932      0.000     -85.110     -28.490
Boudin:Year      6.6000      2.851      2.315      0.021       1.013      12.187
==============================================================================
Omnibus:                        5.942   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                1.946
Skew:                           1.077   Prob(JB):                        0.378
Kurtosis:                       3.742   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [166]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.995
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     300.1
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):           3.30e-05
Time:                                    00:55:34   Log-Likelihood:                -27.654
No. Observations:                               9   AIC:                             65.31
Df Residuals:                                   4   BIC:                             66.30
Df Model:                                       4
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.882e+04   5006.833     -5.756      0.000   -3.86e+04    -1.9e+04
Boudin       -1.331e+04   5765.177     -2.309      0.021   -2.46e+04   -2014.928
Year            14.4000      2.475      5.818      0.000       9.549      19.251
Before_COVID   -56.8000     14.444     -3.932      0.000     -85.110     -28.490
Boudin:Year      6.6000      2.851      2.315      0.021       1.013      12.187
==============================================================================
Omnibus:                        5.942   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                1.946
Skew:                           1.077   Prob(JB):                        0.378
Kurtosis:                       3.742   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [167]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.975
Model:                                       GLS   Adj. R-squared:                  0.950
Method:                            Least Squares   F-statistic:                     1411.
Date:                           Tue, 26 Sep 2023   Prob (F-statistic):           1.50e-06
Time:                                   00:55:49   Log-Likelihood:                -33.584
No. Observations:                              9   AIC:                             77.17
Df Residuals:                                  4   BIC:                             78.15
Df Model:                                      4
Covariance Type:                             HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.291e+04   9427.972     -2.430      0.015   -4.14e+04   -4427.014
Boudin        6.563e+04   9668.591      6.788      0.000    4.67e+04    8.46e+04
Year            11.5000      4.660      2.468      0.014       2.366      20.634
Before_COVID  -103.8000     35.578     -2.918      0.004    -173.531     -34.069
Boudin:Year    -32.5000      4.780     -6.800      0.000     -41.868     -23.132
==============================================================================
Omnibus:                        6.078   Durbin-Watson:                   3.337
Prob(Omnibus):                  0.048   Jarque-Bera (JB):                1.719
Skew:                          -0.909   Prob(JB):                        0.423
Kurtosis:                       4.131   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [171]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       1.000
Model:                            GLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                 2.383e+04
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00496
Time:                        00:57:01   Log-Likelihood:                 44.303
No. Observations:                   9   AIC:                            -72.61
Df Residuals:                       1   BIC:                            -71.03
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -354.2417     12.264    -28.884      0.000    -378.280    -330.204
Boudin                            61.0517     12.447      4.905      0.000      36.656      85.447
Year                               0.1805      0.006     29.500      0.000       0.169       0.192
Before_COVID                       0.2701      0.024     11.360      0.000       0.223       0.317
Med_Arrest_To_Close               -0.0024    5.9e-05    -39.847      0.000      -0.002      -0.002
Med_Arrest_To_Close_Conviction    -0.0051      0.000    -10.163      0.000      -0.006      -0.004
Med_Arrest_To_Close_Dismissal     -0.0006      0.000     -4.117      0.000      -0.001      -0.000
Boudin:Year                       -0.0300      0.006     -4.865      0.000      -0.042      -0.018
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                          -1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [173]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       1.000
Model:                            GLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                 2.383e+04
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00496
Time:                        00:57:40   Log-Likelihood:                 44.303
No. Observations:                   9   AIC:                            -72.61
Df Residuals:                       1   BIC:                            -71.03
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -354.2417     12.264    -28.884      0.000    -378.280    -330.204
Boudin                            61.0517     12.447      4.905      0.000      36.656      85.447
Year                               0.1805      0.006     29.500      0.000       0.169       0.192
Before_COVID                       0.2701      0.024     11.360      0.000       0.223       0.317
Med_Arrest_To_Close               -0.0024    5.9e-05    -39.847      0.000      -0.002      -0.002
Med_Arrest_To_Close_Conviction    -0.0051      0.000    -10.163      0.000      -0.006      -0.004
Med_Arrest_To_Close_Dismissal     -0.0006      0.000     -4.117      0.000      -0.001      -0.000
Boudin:Year                       -0.0300      0.006     -4.865      0.000      -0.042      -0.018
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                          -1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [174]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     457.9
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0358
Time:                        00:57:46   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -26.50
Df Residuals:                       1   BIC:                            -24.92
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.9988    158.920     -2.441      0.015    -699.476     -76.522
Boudin                            -0.3685    161.282     -0.002      0.998    -316.476     315.739
Year                               0.1975      0.079      2.491      0.013       0.042       0.353
Before_COVID                       0.0627      0.308      0.204      0.839      -0.541       0.666
Med_Arrest_To_Close               -0.0044      0.001     -5.770      0.000      -0.006      -0.003
Med_Arrest_To_Close_Conviction    -0.0088      0.006     -1.360      0.174      -0.021       0.004
Med_Arrest_To_Close_Dismissal      0.0005      0.002      0.284      0.776      -0.003       0.004
Boudin:Year                        0.0004      0.080      0.005      0.996      -0.156       0.157
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                           1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '

In [175]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     457.9
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0358
Time:                        00:57:56   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -26.50
Df Residuals:                       1   BIC:                            -24.92
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.9988    158.920     -2.441      0.015    -699.476     -76.522
Boudin                            -0.3685    161.282     -0.002      0.998    -316.476     315.739
Year                               0.1975      0.079      2.491      0.013       0.042       0.353
Before_COVID                       0.0627      0.308      0.204      0.839      -0.541       0.666
Med_Arrest_To_Close               -0.0044      0.001     -5.770      0.000      -0.006      -0.003
Med_Arrest_To_Close_Conviction    -0.0088      0.006     -1.360      0.174      -0.021       0.004
Med_Arrest_To_Close_Dismissal      0.0005      0.002      0.284      0.776      -0.003       0.004
Boudin:Year                        0.0004      0.080      0.005      0.996      -0.156       0.157
==============================================================================
Omnibus:                        7.428   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                2.504
Skew:                           1.174   Prob(JB):                        0.286
Kurtosis:                       4.081   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 6
  warnings.warn('covariance of constraints does not have full '

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [184]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.894
Model:                            GLS   Adj. R-squared:                  0.815
Method:                 Least Squares   F-statistic:                     14.55
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0128
Time:                        00:58:27   Log-Likelihood:                 11.401
No. Observations:                   8   AIC:                            -14.80
Df Residuals:                       4   BIC:                            -14.48
Df Model:                           3
Covariance Type:                  HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    -117.9801     29.812     -3.957      0.000    -176.411     -59.550
Boudin        202.7657    111.305      1.822      0.068     -15.387     420.919
Year            0.0628      0.015      4.250      0.000       0.034       0.092
Boudin:Year    -0.1006      0.055     -1.827      0.068      -0.209       0.007
==============================================================================
Omnibus:                        2.111   Durbin-Watson:                   2.625
Prob(Omnibus):                  0.348   Jarque-Bera (JB):                1.254
Skew:                          -0.868   Prob(JB):                        0.534
Kurtosis:                       2.133   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [189]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.935
Model:                            GLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                     15.89
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0109
Time:                        00:59:10   Log-Likelihood:                 6.7971
No. Observations:                   8   AIC:                            -5.594
Df Residuals:                       4   BIC:                            -5.276
Df Model:                           3
Covariance Type:                  HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -2.2724     51.019     -0.045      0.964    -102.267      97.723
Boudin        359.9835    194.220      1.853      0.064     -20.680     740.647
Year            0.0051      0.025      0.204      0.839      -0.044       0.055
Boudin:Year    -0.1785      0.096     -1.857      0.063      -0.367       0.010
==============================================================================
Omnibus:                        2.275   Durbin-Watson:                   2.623
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                1.333
Skew:                          -0.903   Prob(JB):                        0.514
Kurtosis:                       2.140   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [190]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.921
Model:                              GLS   Adj. R-squared:                  0.863
Method:                   Least Squares   F-statistic:                     37.95
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):            0.00214
Time:                          00:59:20   Log-Likelihood:                -49.721
No. Observations:                     8   AIC:                             107.4
Df Residuals:                         4   BIC:                             107.8
Df Model:                             3
Covariance Type:                    HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -2.928e+05   1.42e+05     -2.067      0.039   -5.71e+05   -1.51e+04
Boudin      -1.928e+05   1.57e+05     -1.232      0.218      -5e+05    1.14e+05
Year          145.5000     70.244      2.071      0.038       7.825     283.175
Boudin:Year    95.5000     77.609      1.231      0.219     -56.611     247.611
==============================================================================
Omnibus:                        0.071   Durbin-Watson:                   1.655
Prob(Omnibus):                  0.965   Jarque-Bera (JB):                0.294
Skew:                           0.056   Prob(JB):                        0.863
Kurtosis:                       2.068   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [191]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.969
Model:                             GLS   Adj. R-squared:                  0.945
Method:                  Least Squares   F-statistic:                     50.04
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):            0.00125
Time:                         00:59:27   Log-Likelihood:                -34.104
No. Observations:                    8   AIC:                             76.21
Df Residuals:                        4   BIC:                             76.53
Df Model:                            3
Covariance Type:                   HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -3.268e+04   4098.964     -7.974      0.000   -4.07e+04   -2.47e+04
Boudin      -4.777e+04   3.93e+04     -1.216      0.224   -1.25e+05    2.92e+04
Year           16.3000      2.033      8.018      0.000      12.315      20.285
Boudin:Year    23.7000     19.440      1.219      0.223     -14.402      61.802
==============================================================================
Omnibus:                        5.766   Durbin-Watson:                   3.016
Prob(Omnibus):                  0.056   Jarque-Bera (JB):                1.651
Skew:                           1.070   Prob(JB):                        0.438
Kurtosis:                       3.609   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [192]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.994
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     384.8
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):           2.23e-05
Time:                                    00:59:38   Log-Likelihood:                -25.053
No. Observations:                               8   AIC:                             58.11
Df Residuals:                                   4   BIC:                             58.42
Df Model:                                       3
Covariance Type:                              HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -2.888e+04   4707.538     -6.134      0.000   -3.81e+04   -1.96e+04
Boudin      -1.326e+04   5424.218     -2.444      0.015   -2.39e+04   -2626.394
Year           14.4000      2.333      6.171      0.000       9.827      18.973
Boudin:Year     6.6000      2.687      2.456      0.014       1.333      11.867
==============================================================================
Omnibus:                        4.686   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                1.410
Skew:                           1.015   Prob(JB):                        0.494
Kurtosis:                       3.327   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [193]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.914
Model:                                       GLS   Adj. R-squared:                  0.862
Method:                            Least Squares   F-statistic:                     188.2
Date:                           Tue, 26 Sep 2023   Prob (F-statistic):           1.47e-05
Time:                                   00:59:55   Log-Likelihood:                -39.150
No. Observations:                              9   AIC:                             86.30
Df Residuals:                                  5   BIC:                             87.09
Df Model:                                      3
Covariance Type:                             HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -4.918e+04   8548.134     -5.753      0.000   -6.59e+04   -3.24e+04
Boudin        9.19e+04   8760.513     10.490      0.000    7.47e+04    1.09e+05
Year           24.4750      4.237      5.776      0.000      16.170      32.780
Boudin:Year   -45.4750      4.342    -10.473      0.000     -53.985     -36.965
==============================================================================
Omnibus:                        3.700   Durbin-Watson:                   1.328
Prob(Omnibus):                  0.157   Jarque-Bera (JB):                1.427
Skew:                          -0.975   Prob(JB):                        0.490
Kurtosis:                       3.046   Cond. No.                     9.47e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [194]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.991
Model:                            GLS   Adj. R-squared:                  0.964
Method:                 Least Squares   F-statistic:                     57.11
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0173
Time:                        01:00:19   Log-Likelihood:                 22.798
No. Observations:                   9   AIC:                            -31.60
Df Residuals:                       2   BIC:                            -30.22
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -412.8776     82.535     -5.002      0.000    -574.643    -251.112
Boudin                            71.8064    141.357      0.508      0.611    -205.247     348.860
Year                               0.2099      0.041      5.111      0.000       0.129       0.290
Med_Arrest_To_Close               -0.0027      0.001     -3.055      0.002      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0065      0.004     -1.622      0.105      -0.014       0.001
Med_Arrest_To_Close_Dismissal     -0.0015      0.002     -0.942      0.346      -0.005       0.002
Boudin:Year                       -0.0353      0.070     -0.505      0.614      -0.173       0.102
==============================================================================
Omnibus:                        1.917   Durbin-Watson:                   2.634
Prob(Omnibus):                  0.383   Jarque-Bera (JB):                1.134
Skew:                           0.808   Prob(JB):                        0.567
Kurtosis:                       2.354   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [195]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     439.5
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00227
Time:                        01:00:31   Log-Likelihood:                 21.081
No. Observations:                   9   AIC:                            -28.16
Df Residuals:                       2   BIC:                            -26.78
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -401.6094     85.448     -4.700      0.000    -569.085    -234.134
Boudin                             2.1279    145.893      0.015      0.988    -283.818     288.074
Year                               0.2043      0.043      4.806      0.000       0.121       0.288
Med_Arrest_To_Close               -0.0045      0.001     -6.170      0.000      -0.006      -0.003
Med_Arrest_To_Close_Conviction    -0.0091      0.004     -2.282      0.022      -0.017      -0.001
Med_Arrest_To_Close_Dismissal      0.0003      0.002      0.174      0.862      -0.003       0.004
Boudin:Year                       -0.0008      0.072     -0.011      0.991      -0.142       0.141
==============================================================================
Omnibus:                        5.932   Durbin-Watson:                   2.974
Prob(Omnibus):                  0.052   Jarque-Bera (JB):                2.009
Skew:                           1.108   Prob(JB):                        0.366
Kurtosis:                       3.670   Cond. No.                     2.53e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 2.53e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 6, but rank is 5
  warnings.warn('covariance of constraints does not have full '

## Violent Crimes

### 2023 Inclusive

In [196]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_violent = sf_case_resolutions_violent.copy()
sf_cr_violent["Conviction"] = sf_cr_violent["Conviction"].astype(int)

sf_cr_violent['Log_Conviction'] = np.log(sf_cr_violent['Conviction'])
sf_cr_violent['Log_Total'] = np.log(sf_cr_violent['Total'])
sf_cr_violent['Boudin'] = sf_cr_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_violent['Before_COVID'] = sf_cr_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_violent_proj = sf_cr_violent.copy() #Creates defensive copy
sf_cr_violent_proj.iloc[8, 1] = sf_cr_violent_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_violent_proj = sf_cr_violent_proj.drop(9)

# Drops '2023*' Row
sf_cr_violent = sf_cr_violent.drop(9)

# Addresses type issues
sf_cr_violent["Year"] = sf_cr_violent["Year"].astype(int)
sf_cr_violent["Med_Arrest_To_Close"] = sf_cr_violent["Med_Arrest_To_Close"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Conviction"] = sf_cr_violent["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_violent_proj["Year"] = sf_cr_violent_proj["Year"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close"] = sf_cr_violent_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_violent_no2023 = sf_cr_violent[sf_cr_violent["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [220]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.918
Model:                            GLS   Adj. R-squared:                  0.837
Method:                 Least Squares   F-statistic:                     36.53
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00209
Time:                        01:01:06   Log-Likelihood:                 13.774
No. Observations:                   9   AIC:                            -17.55
Df Residuals:                       4   BIC:                            -16.56
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -145.4370     56.073     -2.594      0.009    -255.338     -35.536
Boudin         251.6020     97.464      2.581      0.010      60.576     442.628
Year             0.0754      0.028      2.719      0.007       0.021       0.130
Before_COVID     0.8510      0.161      5.270      0.000       0.535       1.167
Boudin:Year     -0.1244      0.048     -2.579      0.010      -0.219      -0.030
==============================================================================
Omnibus:                        1.268   Durbin-Watson:                   2.030
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.740
Skew:                          -0.295   Prob(JB):                        0.691
Kurtosis:                       1.726   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [221]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.918
Model:                            GLS   Adj. R-squared:                  0.837
Method:                 Least Squares   F-statistic:                     36.53
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00209
Time:                        01:01:20   Log-Likelihood:                 13.774
No. Observations:                   9   AIC:                            -17.55
Df Residuals:                       4   BIC:                            -16.56
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -145.4370     56.073     -2.594      0.009    -255.338     -35.536
Boudin         251.6020     97.464      2.581      0.010      60.576     442.628
Year             0.0754      0.028      2.719      0.007       0.021       0.130
Before_COVID     0.8510      0.161      5.270      0.000       0.535       1.167
Boudin:Year     -0.1244      0.048     -2.579      0.010      -0.219      -0.030
==============================================================================
Omnibus:                        1.268   Durbin-Watson:                   2.030
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.740
Skew:                          -0.295   Prob(JB):                        0.691
Kurtosis:                       1.726   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [222]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.945
Model:                            GLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     79.04
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000464
Time:                        01:01:26   Log-Likelihood:                 9.0607
No. Observations:                   9   AIC:                            -8.121
Df Residuals:                       4   BIC:                            -7.135
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -17.3922     63.221     -0.275      0.783    -141.303     106.519
Boudin         277.3642    186.705      1.486      0.137     -88.571     643.300
Year             0.0116      0.031      0.370      0.712      -0.050       0.073
Before_COVID     0.9808      0.195      5.042      0.000       0.600       1.362
Boudin:Year     -0.1371      0.092     -1.484      0.138      -0.318       0.044
==============================================================================
Omnibus:                        2.005   Durbin-Watson:                   2.499
Prob(Omnibus):                  0.367   Jarque-Bera (JB):                1.242
Skew:                          -0.830   Prob(JB):                        0.537
Kurtosis:                       2.252   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [223]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.945
Model:                            GLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     79.04
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           0.000464
Time:                        01:01:37   Log-Likelihood:                 9.0607
No. Observations:                   9   AIC:                            -8.121
Df Residuals:                       4   BIC:                            -7.135
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -17.3922     63.221     -0.275      0.783    -141.303     106.519
Boudin         277.3642    186.705      1.486      0.137     -88.571     643.300
Year             0.0116      0.031      0.370      0.712      -0.050       0.073
Before_COVID     0.9808      0.195      5.042      0.000       0.600       1.362
Boudin:Year     -0.1371      0.092     -1.484      0.138      -0.318       0.044
==============================================================================
Omnibus:                        2.005   Durbin-Watson:                   2.499
Prob(Omnibus):                  0.367   Jarque-Bera (JB):                1.242
Skew:                          -0.830   Prob(JB):                        0.537
Kurtosis:                       2.252   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [224]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.957
Model:                              GLS   Adj. R-squared:                  0.914
Method:                   Least Squares   F-statistic:                     113.1
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):           0.000254
Time:                          01:01:50   Log-Likelihood:                -42.586
No. Observations:                     9   AIC:                             95.17
Df Residuals:                         4   BIC:                             96.16
Df Model:                             4
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.174e+05   3.86e+04     -3.044      0.002   -1.93e+05   -4.18e+04
Boudin        8.341e+04   3.86e+04      2.160      0.031    7722.828    1.59e+05
Year            58.2000     19.058      3.054      0.002      20.847      95.553
Before_COVID   138.0000    117.107      1.178      0.239     -91.526     367.526
Boudin:Year    -41.2000     19.088     -2.158      0.031     -78.611      -3.789
==============================================================================
Omnibus:                        0.257   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.276
Skew:                           0.283   Prob(JB):                        0.871
Kurtosis:                       2.357   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 4, but rank is 3
  warnings.warn('covariance of constraints does not have full '

In [225]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.957
Model:                              GLS   Adj. R-squared:                  0.914
Method:                   Least Squares   F-statistic:                     113.1
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):           0.000254
Time:                          01:02:00   Log-Likelihood:                -42.586
No. Observations:                     9   AIC:                             95.17
Df Residuals:                         4   BIC:                             96.16
Df Model:                             4
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.174e+05   3.86e+04     -3.044      0.002   -1.93e+05   -4.18e+04
Boudin        8.341e+04   3.86e+04      2.160      0.031    7722.828    1.59e+05
Year            58.2000     19.058      3.054      0.002      20.847      95.553
Before_COVID   138.0000    117.107      1.178      0.239     -91.526     367.526
Boudin:Year    -41.2000     19.088     -2.158      0.031     -78.611      -3.789
==============================================================================
Omnibus:                        0.257   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.879   Jarque-Bera (JB):                0.276
Skew:                           0.283   Prob(JB):                        0.871
Kurtosis:                       2.357   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 4, but rank is 3
  warnings.warn('covariance of constraints does not have full '

In [226]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.944
Model:                             GLS   Adj. R-squared:                  0.888
Method:                  Least Squares   F-statistic:                     406.1
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):           1.81e-05
Time:                         01:02:08   Log-Likelihood:                -43.391
No. Observations:                    9   AIC:                             96.78
Df Residuals:                        4   BIC:                             97.77
Df Model:                            4
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.694e+04   1.59e+04     -2.948      0.003   -7.81e+04   -1.57e+04
Boudin        2.819e+04   7.36e+04      0.383      0.702   -1.16e+05    1.72e+05
Year            23.4000      7.870      2.973      0.003       7.975      38.825
Before_COVID   -63.0000     57.063     -1.104      0.270    -174.841      48.841
Boudin:Year    -13.9000     36.393     -0.382      0.703     -85.229      57.429
==============================================================================
Omnibus:                        3.483   Durbin-Watson:                   3.459
Prob(Omnibus):                  0.175   Jarque-Bera (JB):                1.108
Skew:                           0.852   Prob(JB):                        0.575
Kurtosis:                       3.232   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [227]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.944
Model:                             GLS   Adj. R-squared:                  0.888
Method:                  Least Squares   F-statistic:                     406.1
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):           1.81e-05
Time:                         01:02:20   Log-Likelihood:                -43.391
No. Observations:                    9   AIC:                             96.78
Df Residuals:                        4   BIC:                             97.77
Df Model:                            4
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.694e+04   1.59e+04     -2.948      0.003   -7.81e+04   -1.57e+04
Boudin        2.819e+04   7.36e+04      0.383      0.702   -1.16e+05    1.72e+05
Year            23.4000      7.870      2.973      0.003       7.975      38.825
Before_COVID   -63.0000     57.063     -1.104      0.270    -174.841      48.841
Boudin:Year    -13.9000     36.393     -0.382      0.703     -85.229      57.429
==============================================================================
Omnibus:                        3.483   Durbin-Watson:                   3.459
Prob(Omnibus):                  0.175   Jarque-Bera (JB):                1.108
Skew:                           0.852   Prob(JB):                        0.575
Kurtosis:                       3.232   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [228]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.965
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     381.0
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):           2.05e-05
Time:                                    01:02:30   Log-Likelihood:                -40.698
No. Observations:                               9   AIC:                             91.40
Df Residuals:                                   4   BIC:                             92.38
Df Model:                                       4
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.777e+04   5302.653     -9.010      0.000   -5.82e+04   -3.74e+04
Boudin        6.033e+04    5.6e+04      1.078      0.281   -4.94e+04     1.7e+05
Year            23.8000      2.621      9.080      0.000      18.663      28.937
Before_COVID   -43.4000     19.041     -2.279      0.023     -80.719      -6.081
Boudin:Year    -29.8000     27.701     -1.076      0.282     -84.094      24.494
==============================================================================
Omnibus:                        5.860   Durbin-Watson:                   3.412
Prob(Omnibus):                  0.053   Jarque-Bera (JB):                1.899
Skew:                           1.062   Prob(JB):                        0.387
Kurtosis:                       3.744   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [229]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.965
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     381.0
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):           2.05e-05
Time:                                    01:02:40   Log-Likelihood:                -40.698
No. Observations:                               9   AIC:                             91.40
Df Residuals:                                   4   BIC:                             92.38
Df Model:                                       4
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.777e+04   5302.653     -9.010      0.000   -5.82e+04   -3.74e+04
Boudin        6.033e+04    5.6e+04      1.078      0.281   -4.94e+04     1.7e+05
Year            23.8000      2.621      9.080      0.000      18.663      28.937
Before_COVID   -43.4000     19.041     -2.279      0.023     -80.719      -6.081
Boudin:Year    -29.8000     27.701     -1.076      0.282     -84.094      24.494
==============================================================================
Omnibus:                        5.860   Durbin-Watson:                   3.412
Prob(Omnibus):                  0.053   Jarque-Bera (JB):                1.899
Skew:                           1.062   Prob(JB):                        0.387
Kurtosis:                       3.744   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [230]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.954
Model:                                       GLS   Adj. R-squared:                  0.908
Method:                            Least Squares   F-statistic:                     396.9
Date:                           Tue, 26 Sep 2023   Prob (F-statistic):           1.89e-05
Time:                                   01:02:55   Log-Likelihood:                -40.196
No. Observations:                              9   AIC:                             90.39
Df Residuals:                                  4   BIC:                             91.38
Df Model:                                      4
Covariance Type:                             HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -9945.3000   1.77e+04     -0.561      0.575   -4.47e+04    2.48e+04
Boudin       -9.785e+04   4.54e+04     -2.155      0.031   -1.87e+05   -8846.380
Year             5.1000      8.770      0.582      0.561     -12.089      22.289
Before_COVID  -185.0000     63.936     -2.894      0.004    -310.312     -59.688
Boudin:Year     48.4000     22.465      2.154      0.031       4.369      92.431
==============================================================================
Omnibus:                        0.183   Durbin-Watson:                   3.393
Prob(Omnibus):                  0.913   Jarque-Bera (JB):                0.241
Skew:                           0.236   Prob(JB):                        0.886
Kurtosis:                       2.353   Cond. No.                     1.03e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.03e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [208]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.969
Model:                            GLS   Adj. R-squared:                  0.751
Method:                 Least Squares   F-statistic:                     4.447
Date:                Tue, 26 Sep 2023   Prob (F-statistic):              0.350
Time:                        01:00:58   Log-Likelihood:                 18.120
No. Observations:                   9   AIC:                            -20.24
Df Residuals:                       1   BIC:                            -18.66
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -226.4209    142.833     -1.585      0.358   -2041.284    1588.442
Boudin                           223.3978    849.092      0.263      0.836   -1.06e+04     1.1e+04
Year                               0.1160      0.070      1.652      0.347      -0.777       1.009
Before_COVID                       0.3649      1.398      0.261      0.837     -17.393      18.122
Med_Arrest_To_Close                0.0070      0.013      0.543      0.683      -0.157       0.171
Med_Arrest_To_Close_Conviction    -0.0079      0.010     -0.820      0.563      -0.131       0.115
Med_Arrest_To_Close_Dismissal     -0.0032      0.010     -0.324      0.801      -0.127       0.121
Boudin:Year                       -0.1104      0.420     -0.263      0.836      -5.444       5.224
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [231]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.969
Model:                            GLS   Adj. R-squared:                  0.751
Method:                 Least Squares   F-statistic:                     33.46
Date:                Tue, 26 Sep 2023   Prob (F-statistic):              0.130
Time:                        01:03:17   Log-Likelihood:                 18.120
No. Observations:                   9   AIC:                            -20.24
Df Residuals:                       1   BIC:                            -18.66
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -226.4209     99.734     -2.270      0.023    -421.895     -30.947
Boudin                           223.3978    303.283      0.737      0.461    -371.026     817.821
Year                               0.1160      0.049      2.365      0.018       0.020       0.212
Before_COVID                       0.3649      0.662      0.551      0.581      -0.932       1.662
Med_Arrest_To_Close                0.0070      0.007      1.072      0.284      -0.006       0.020
Med_Arrest_To_Close_Conviction    -0.0079      0.006     -1.241      0.215      -0.020       0.005
Med_Arrest_To_Close_Dismissal     -0.0032      0.003     -0.961      0.337      -0.010       0.003
Boudin:Year                       -0.1104      0.150     -0.736      0.462      -0.404       0.183
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '

In [232]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     26.62
Date:                Tue, 26 Sep 2023   Prob (F-statistic):              0.146
Time:                        01:03:42   Log-Likelihood:                 18.805
No. Observations:                   9   AIC:                            -21.61
Df Residuals:                       1   BIC:                            -20.03
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -202.3983     92.425     -2.190      0.029    -383.549     -21.248
Boudin                           363.1586    281.059      1.292      0.196    -187.708     914.025
Year                               0.1042      0.045      2.291      0.022       0.015       0.193
Before_COVID                       0.2721      0.613      0.444      0.657      -0.930       1.474
Med_Arrest_To_Close                0.0105      0.006      1.724      0.085      -0.001       0.022
Med_Arrest_To_Close_Conviction    -0.0133      0.006     -2.239      0.025      -0.025      -0.002
Med_Arrest_To_Close_Dismissal     -0.0043      0.003     -1.407      0.159      -0.010       0.002
Boudin:Year                       -0.1795      0.139     -1.292      0.197      -0.452       0.093
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '

In [233]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     26.62
Date:                Tue, 26 Sep 2023   Prob (F-statistic):              0.146
Time:                        01:04:03   Log-Likelihood:                 18.805
No. Observations:                   9   AIC:                            -21.61
Df Residuals:                       1   BIC:                            -20.03
Df Model:                           7
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -202.3983     92.425     -2.190      0.029    -383.549     -21.248
Boudin                           363.1586    281.059      1.292      0.196    -187.708     914.025
Year                               0.1042      0.045      2.291      0.022       0.015       0.193
Before_COVID                       0.2721      0.613      0.444      0.657      -0.930       1.474
Med_Arrest_To_Close                0.0105      0.006      1.724      0.085      -0.001       0.022
Med_Arrest_To_Close_Conviction    -0.0133      0.006     -2.239      0.025      -0.025      -0.002
Med_Arrest_To_Close_Dismissal     -0.0043      0.003     -1.407      0.159      -0.010       0.002
Boudin:Year                       -0.1795      0.139     -1.292      0.197      -0.452       0.093
==============================================================================
Omnibus:                        5.445   Durbin-Watson:                   2.513
Prob(Omnibus):                  0.066   Jarque-Bera (JB):                1.317
Skew:                          -0.699   Prob(JB):                        0.518
Kurtosis:                       4.247   Cond. No.                     5.86e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:1888: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 7, but rank is 5
  warnings.warn('covariance of constraints does not have full '

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [234]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.889
Model:                            GLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     12.79
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0162
Time:                        01:04:42   Log-Likelihood:                 11.773
No. Observations:                   8   AIC:                            -15.55
Df Residuals:                       4   BIC:                            -15.23
Df Model:                           3
Covariance Type:                  HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept    -144.5860     52.718     -2.743      0.006    -247.912     -41.260
Boudin        250.7510     91.805      2.731      0.006      70.817     430.685
Year            0.0754      0.026      2.884      0.004       0.024       0.127
Boudin:Year    -0.1244      0.045     -2.736      0.006      -0.213      -0.035
==============================================================================
Omnibus:                        1.991   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.370   Jarque-Bera (JB):                0.820
Skew:                          -0.278   Prob(JB):                        0.664
Kurtosis:                       1.534   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [235]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.862
Method:                 Least Squares   F-statistic:                     13.20
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0153
Time:                        01:04:49   Log-Likelihood:                 7.5828
No. Observations:                   8   AIC:                            -7.166
Df Residuals:                       4   BIC:                            -6.848
Df Model:                           3
Covariance Type:                  HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     -16.4114     59.429     -0.276      0.782    -132.889     100.067
Boudin        276.3834    175.968      1.571      0.116     -68.507     621.274
Year            0.0116      0.029      0.392      0.695      -0.046       0.069
Boudin:Year    -0.1371      0.087     -1.574      0.115      -0.308       0.034
==============================================================================
Omnibus:                        1.840   Durbin-Watson:                   2.404
Prob(Omnibus):                  0.399   Jarque-Bera (JB):                1.148
Skew:                          -0.782   Prob(JB):                        0.563
Kurtosis:                       2.002   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [236]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.953
Model:                              GLS   Adj. R-squared:                  0.918
Method:                   Least Squares   F-statistic:                     133.8
Date:                  Tue, 26 Sep 2023   Prob (F-statistic):           0.000182
Time:                          01:04:55   Log-Likelihood:                -38.326
No. Observations:                     8   AIC:                             84.65
Df Residuals:                         4   BIC:                             84.97
Df Model:                             3
Covariance Type:                    HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -1.172e+05   3.62e+04     -3.234      0.001   -1.88e+05   -4.62e+04
Boudin       8.327e+04   3.63e+04      2.294      0.022    1.21e+04    1.54e+05
Year           58.2000     17.968      3.239      0.001      22.983      93.417
Boudin:Year   -41.2000     17.996     -2.289      0.022     -76.472      -5.928
==============================================================================
Omnibus:                        0.244   Durbin-Watson:                   1.708
Prob(Omnibus):                  0.885   Jarque-Bera (JB):                0.368
Skew:                           0.267   Prob(JB):                        0.832
Kurtosis:                       2.095   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [237]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.940
Model:                             GLS   Adj. R-squared:                  0.894
Method:                  Least Squares   F-statistic:                     20.69
Date:                 Tue, 26 Sep 2023   Prob (F-statistic):            0.00673
Time:                         01:05:02   Log-Likelihood:                -39.041
No. Observations:                    8   AIC:                             86.08
Df Residuals:                        4   BIC:                             86.40
Df Model:                            3
Covariance Type:                   HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     -4.7e+04    1.5e+04     -3.142      0.002   -7.63e+04   -1.77e+04
Boudin       2.825e+04   6.93e+04      0.407      0.684   -1.08e+05    1.64e+05
Year           23.4000      7.420      3.154      0.002       8.858      37.942
Boudin:Year   -13.9000     34.312     -0.405      0.685     -81.150      53.350
==============================================================================
Omnibus:                        2.570   Durbin-Watson:                   3.321
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                0.865
Skew:                           0.803   Prob(JB):                        0.649
Kurtosis:                       2.873   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [238]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.962
Model:                                        GLS   Adj. R-squared:                  0.934
Method:                             Least Squares   F-statistic:                     55.56
Date:                            Tue, 26 Sep 2023   Prob (F-statistic):            0.00102
Time:                                    01:05:08   Log-Likelihood:                -36.648
No. Observations:                               8   AIC:                             81.30
Df Residuals:                                   4   BIC:                             81.61
Df Model:                                       3
Covariance Type:                              HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -4.782e+04   4982.208     -9.598      0.000   -5.76e+04   -3.81e+04
Boudin       6.037e+04   5.28e+04      1.144      0.253   -4.31e+04    1.64e+05
Year           23.8000      2.471      9.631      0.000      18.956      28.644
Boudin:Year   -29.8000     26.117     -1.141      0.254     -80.989      21.389
==============================================================================
Omnibus:                        4.614   Durbin-Watson:                   3.261
Prob(Omnibus):                  0.100   Jarque-Bera (JB):                1.372
Skew:                           1.001   Prob(JB):                        0.504
Kurtosis:                       3.328   Cond. No.                     9.84e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [239]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.872
Model:                                       GLS   Adj. R-squared:                  0.796
Method:                            Least Squares   F-statistic:                     14.82
Date:                           Tue, 26 Sep 2023   Prob (F-statistic):            0.00638
Time:                                   01:05:15   Log-Likelihood:                -44.808
No. Observations:                              9   AIC:                             97.62
Df Residuals:                                  5   BIC:                             98.40
Df Model:                                      3
Covariance Type:                             HC1
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -5.677e+04   1.61e+04     -3.529      0.000   -8.83e+04   -2.52e+04
Boudin      -5.103e+04   4.07e+04     -1.254      0.210   -1.31e+05    2.87e+04
Year           28.2250      7.971      3.541      0.000      12.602      43.848
Boudin:Year    25.2750     20.143      1.255      0.210     -14.206      64.756
==============================================================================
Omnibus:                        0.568   Durbin-Watson:                   1.447
Prob(Omnibus):                  0.753   Jarque-Bera (JB):                0.540
Skew:                          -0.268   Prob(JB):                        0.763
Kurtosis:                       1.927   Cond. No.                     9.47e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [240]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     85.36
Date:                Tue, 26 Sep 2023   Prob (F-statistic):             0.0116
Time:                        01:05:22   Log-Likelihood:                 17.823
No. Observations:                   9   AIC:                            -21.65
Df Residuals:                       2   BIC:                            -20.27
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -201.0829     51.703     -3.889      0.000    -302.419     -99.747
Boudin                            12.9738    144.231      0.090      0.928    -269.713     295.661
Year                               0.1037      0.026      4.037      0.000       0.053       0.154
Med_Arrest_To_Close                0.0102      0.003      3.800      0.000       0.005       0.015
Med_Arrest_To_Close_Conviction    -0.0100      0.004     -2.865      0.004      -0.017      -0.003
Med_Arrest_To_Close_Dismissal     -0.0057      0.001     -5.603      0.000      -0.008      -0.004
Boudin:Year                       -0.0064      0.071     -0.089      0.929      -0.146       0.133
==============================================================================
Omnibus:                        4.996   Durbin-Watson:                   2.889
Prob(Omnibus):                  0.082   Jarque-Bera (JB):                1.384
Skew:                          -0.875   Prob(JB):                        0.501
Kurtosis:                       3.793   Cond. No.                     1.89e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.89e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [241]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal + Boudin*Year"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.993
Model:                            GLS   Adj. R-squared:                  0.974
Method:                 Least Squares   F-statistic:                     582.9
Date:                Tue, 26 Sep 2023   Prob (F-statistic):            0.00171
Time:                        01:05:30   Log-Likelihood:                 18.610
No. Observations:                   9   AIC:                            -23.22
Df Residuals:                       2   BIC:                            -21.84
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -183.5002     46.111     -3.980      0.000    -273.875     -93.125
Boudin                           206.2158    129.155      1.597      0.110     -46.923     459.355
Year                               0.0950      0.023      4.145      0.000       0.050       0.140
Med_Arrest_To_Close                0.0128      0.002      5.408      0.000       0.008       0.017
Med_Arrest_To_Close_Conviction    -0.0148      0.003     -4.759      0.000      -0.021      -0.009
Med_Arrest_To_Close_Dismissal     -0.0062      0.001     -6.649      0.000      -0.008      -0.004
Boudin:Year                       -0.1019      0.064     -1.595      0.111      -0.227       0.023
==============================================================================
Omnibus:                        5.313   Durbin-Watson:                   2.816
Prob(Omnibus):                  0.070   Jarque-Bera (JB):                1.439
Skew:                          -0.860   Prob(JB):                        0.487
Kurtosis:                       3.938   Cond. No.                     1.89e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.89e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# Part III