In [1]:
# !pip install firebase-admin

# Load in Data & Libraries

In [2]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from scipy import stats
import warnings
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.diagnostic import linear_lm
import sklearn
from sklearn.model_selection import train_test_split
from datetime import datetime
# Initialize the Firebase app with your service account key
cred = credentials.Certificate(r'PRIVATE-KEY-sf-da-analysis-firebase.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://sf-da-analysis-6f156-default-rtdb.firebaseio.com/'
})

In [3]:
# For sf_prosecutions
# Get a reference to the Firebase Realtime Database
ref = db.reference('/District_Attorney_Cases_Prosecuted_2014_2023')

# Load data from the collection
sf_prosecutions = ref.get()

# Process the loaded data & converts it to a df
sf_prosecutions = pd.json_normalize(sf_prosecutions)
sf_prosecutions = sf_prosecutions.drop('id', axis=1)

# For sf_case_resolutions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_All_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_all = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_all = pd.json_normalize(sf_case_resolutions_all)
sf_case_resolutions_all = sf_case_resolutions_all.drop('id', axis=1)

# For sf_case_resolutions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Case_Resoultions_Violent_Crimes_2015_2023')

# Load data from the collection
sf_case_resolutions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_case_resolutions_violent = pd.json_normalize(sf_case_resolutions_violent)
sf_case_resolutions_violent = sf_case_resolutions_violent.drop('id', axis=1)

# For sf_da_actions_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_All_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_all = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_all = pd.json_normalize(sf_da_actions_all)
sf_da_actions_all = sf_da_actions_all.drop('id', axis=1)

# For sf_da_actions_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/DA_Actions_On_Arrests_Violent_Crimes_2015_2023')

# Load data from the collection
sf_da_actions_violent = ref.get()

# Process the loaded data & converts it to a df
sf_da_actions_violent = pd.json_normalize(sf_da_actions_violent)
sf_da_actions_violent = sf_da_actions_violent.drop('id', axis=1)

# For sfpd_incidents_outcomes_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Outcomes_of_SFPD_Incidents_All_Crimes_2015_2023')

# Load data from the collection
sfpd_incidents_outcomes_all = ref.get()

# Process the loaded data & converts it to a df
sfpd_incidents_outcomes_all = pd.json_normalize(sfpd_incidents_outcomes_all)
sfpd_incidents_outcomes_all = sfpd_incidents_outcomes_all.drop('id', axis=1)

# For fed_off_by_crime_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_all = pd.json_normalize(fed_off_by_crime_all)
fed_off_by_crime_all = fed_off_by_crime_all.drop('id', axis=1)

# For fed_off_by_crime_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_by_Type_of_Crime_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_crime_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_crime_violent = pd.json_normalize(fed_off_by_crime_violent)
fed_off_by_crime_violent = fed_off_by_crime_violent.drop('id', axis=1)

# For fed_off_by_dist_all
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_All_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_all = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_all = pd.json_normalize(fed_off_by_dist_all)
fed_off_by_dist_all = fed_off_by_dist_all.drop('id', axis=1)

# For fed_off_by_dist_violent
# Get a reference to the Firebase Realtime Database
ref = db.reference('/Federal_Offenders_in_Each_District_Violent_Crimes_2015_2022')

# Load data from the collection
fed_off_by_dist_violent = ref.get()

# Process the loaded data & converts it to a df
fed_off_by_dist_violent = pd.json_normalize(fed_off_by_dist_violent)
fed_off_by_dist_violent = fed_off_by_dist_violent.drop('id', axis=1)

In [4]:
fed_off_by_dist_all

          Circuit              District  Fiscal_Year      N    Pct
0     Grand Total                 Total         2022  64157  1.000
1      DC Circuit  District of Columbia         2022    312  0.005
2     1st Circuit                 Maine         2022    180  0.003
3     1st Circuit         Massachusetts         2022    466  0.007
4     1st Circuit         New Hampshire         2022    180  0.003
..            ...                   ...          ...    ...    ...
755  11th Circuit     Florida, Northern         2015    255  0.004
756  11th Circuit     Florida, Southern         2015   2238  0.032
757  11th Circuit       Georgia, Middle         2015    377  0.005
758  11th Circuit     Georgia, Northern         2015    592  0.008
759  11th Circuit     Georgia, Southern         2015    420  0.006

[760 rows x 5 columns]

In [5]:
date_format = "%Y-%m-%dT%H:%M:%S.%fZ"

sf_prosecutions['arrest_date'] = pd.to_datetime(sf_prosecutions['arrest_date'], format = date_format)
sf_prosecutions['data_as_of'] = pd.to_datetime(sf_prosecutions['data_as_of'], format = date_format)
sf_prosecutions['data_loaded_at'] = pd.to_datetime(sf_prosecutions['data_loaded_at'], format = date_format)

In [6]:
boudin_start_date = datetime(2020, 1, 8, 0, 0, 0)
boudin_end_date = datetime(2022, 7, 9, 0, 0, 0)
sf_prosecutions_boudin = sf_prosecutions[(sf_prosecutions["arrest_date"] >= boudin_start_date) &
                                         (sf_prosecutions["arrest_date"] < boudin_end_date)]

sf_prosecutions_boudin

,arrest_date,case_status,court_number,crime_type,da_action_taken,data_as_of,data_loaded_at,dv_case,filed_case_type,incident_number,list_of_filed_charges
9383,2020-01-09 08:00:00,Filed Motion to Revoke,2506152,"Forgery, Checks, Access Cards",New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20171107-02506152,470D/F/0
9384,2020-01-30 08:00:00,Filed Motion to Revoke,2520522,Theft,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,Z20200115-02520522,"487C/F/0, 245A4/M/0"
9385,2020-01-14 08:00:00,Filed Motion to Revoke,14005420,Assault,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,Yes,MTR,140153084,"591.5/M/0, 273.5A/F/0, 273.5A/F/0, 273.5A/F/0,..."
9386,2020-01-22 08:00:00,Filed Motion to Revoke,15018930,Robbery,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150735638,"242/M/0, 245A4/F/0, 243B/M/0, 211/F/2"
9387,2020-01-16 08:00:00,Filed Motion to Revoke,15026261,Narcotics,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,MTR,150025953,"11378/F/0, 11377/M/0, 23123A/I/0"
...,...,...,...,...,...,...,...,...,...,...,...
99090,2022-06-24 07:00:00,,2530936,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,23-00344,
99091,2022-06-13 07:00:00,Pending,2530799,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,Z20220613-02530799,
99092,2022-07-06 07:00:00,Fugitive Status,22006648,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,Felony,220445185,"664/1085A/F/0, 664/496DA/F/0"
99096,2022-07-04 07:00:00,Pled Guilty to Other Case or Other DA Action,22006556,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220438726,
99097,2022-07-04 07:00:00,,22006565,,New charges filed,2023-08-28 07:00:00,2023-08-31 05:01:04,No,,220437825,

# PART I - Boudin v National Trends (Fixed Effects)

## All Crimes

In [7]:
def year_marker(year, start, end=9999, mode = 'range'):
  # Default of 9999 is used to indicate ongoing
  if mode == 'before':
    try:
      if year < start:
        return 1
      else:
        return 0
    except:
      return 0

  if mode == 'after':
    start += 1 #Increments start by 1

  # Used for both 'after' and 'range' modes
  else:
    try:
      if year >= start and year <= end:
        return 1
      else:
        return 0
    except:
      return 0

In [8]:
fed_off_totals_all = fed_off_by_dist_all[fed_off_by_dist_all["District"] == "Total"].reset_index(drop=True)
fed_off_totals_all = fed_off_totals_all.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_all.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_all.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_all['Log_Total'] = np.log(fed_off_totals_all['Total'])
fed_off_totals_all['Boudin'] = 0
fed_off_totals_all['SF'] = 0
fed_off_totals_all['Before_COVID'] = fed_off_totals_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_all

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022  64157  11.069088       0   0             0
1  2021  57304  10.956126       0   0             0
2  2020  64591  11.075830       0   0             0
3  2019  76593  11.246261       0   0             1
4  2018  69470  11.148650       0   0             1
5  2017  66899  11.110939       0   0             1
6  2016  67794  11.124229       0   0             1
7  2015  71030  11.170858       0   0             1

In [9]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions = sf_case_resolutions_all[["Year", "Conviction"]]
sfda_convictions["Conviction"] = sfda_convictions["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions['Log_Total'] = np.log(sfda_convictions['Total'])
sfda_convictions['Boudin'] = sfda_convictions.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions['SF'] = 1
sfda_convictions['Before_COVID'] = sfda_convictions.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_proj = sfda_convictions.copy() #Creates defensive copy
sfda_convictions_proj.iloc[8, 1] = sfda_convictions_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_proj = sfda_convictions_proj.drop(9)

# Drops '2023*' Row
sfda_convictions = sfda_convictions.drop(9)

sfda_convictions["Year"] = sfda_convictions["Year"].astype(int)
sfda_convictions_proj["Year"] = sfda_convictions_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

In [10]:
# Concatenate vertically (along rows)
sf_fed_off_totals = pd.concat([fed_off_totals_all, sfda_convictions], axis=0)
sf_fed_off_totals_proj = pd.concat([fed_off_totals_all, sfda_convictions_proj], axis=0)

# Reset the index
sf_fed_off_totals = sf_fed_off_totals.reset_index(drop=True)
sf_fed_off_totals_proj = sf_fed_off_totals_proj.reset_index(drop=True)

sf_fed_off_totals

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0
16  2023   1342   7.201916       0   1             0

### 2023 Inclusive

In [11]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     552.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.72e-13
Time:                        17:08:41   Log-Likelihood:                -156.76
No. Observations:                  17   AIC:                             323.5
Df Residuals:                      12   BIC:                             327.7
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.418e+06   1.33e+06     -1.066      0.286   -4.02e+06    1.19e+06
Year           732.9386    657.868      1.114      0.265    -556.459    2022.337
Boudin        4473.8070   2477.889      1.805      0.071    -382.765    9330.379
SF           -6.588e+04   1731.803    -38.043      0.000   -6.93e+04   -6.25e+04
Before_COVID  9774.9474   4367.214      2.238      0.025    1215.366    1.83e+04
==============================================================================
Omnibus:                        1.133   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.568   Jarque-Bera (JB):                0.112
Skew:                          -0.032   Prob(JB):                        0.945
Kurtosis:                       3.393   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [12]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     410.1
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.02e-12
Time:                        17:08:41   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     74.539      1.211      0.226     -55.831     236.358
Year            -0.0393      0.037     -1.064      0.287      -0.112       0.033
Boudin          -0.3656      0.231     -1.586      0.113      -0.817       0.086
SF              -3.2094      0.125    -25.748      0.000      -3.454      -2.965
Before_COVID     0.1870      0.174      1.075      0.282      -0.154       0.528
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [13]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.994
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     536.0
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           2.07e-13
Time:                        17:08:41   Log-Likelihood:                -157.04
No. Observations:                  17   AIC:                             324.1
Df Residuals:                      12   BIC:                             328.3
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -1.47e+06   1.35e+06     -1.091      0.275   -4.11e+06    1.17e+06
Year           758.6404    666.387      1.138      0.255    -547.454    2064.735
Boudin        4247.6316   2565.171      1.656      0.098    -780.011    9275.274
SF           -6.576e+04   1770.582    -37.140      0.000   -6.92e+04   -6.23e+04
Before_COVID  9713.2632   4389.363      2.213      0.027    1110.269    1.83e+04
==============================================================================
Omnibus:                        1.053   Durbin-Watson:                   1.975
Prob(Omnibus):                  0.591   Jarque-Bera (JB):                0.091
Skew:                          -0.028   Prob(JB):                        0.956
Kurtosis:                       3.353   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [14]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     410.1
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.02e-12
Time:                        17:08:41   Log-Likelihood:                 6.1667
No. Observations:                  17   AIC:                            -2.333
Df Residuals:                      12   BIC:                             1.833
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       90.2635     74.539      1.211      0.226     -55.831     236.358
Year            -0.0393      0.037     -1.064      0.287      -0.112       0.033
Boudin          -0.3656      0.231     -1.586      0.113      -0.817       0.086
SF              -3.2094      0.125    -25.748      0.000      -3.454      -2.965
Before_COVID     0.1870      0.174      1.075      0.282      -0.154       0.528
==============================================================================
Omnibus:                        1.454   Durbin-Watson:                   1.035
Prob(Omnibus):                  0.483   Jarque-Bera (JB):                0.814
Skew:                          -0.532   Prob(JB):                        0.666
Kurtosis:                       2.864   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive

In [15]:
# Drops '2023' Row
sf_fed_off_totals_no2023 = sf_fed_off_totals[sf_fed_off_totals["Year"] != 2023]
sf_fed_off_totals_no2023

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022  64157  11.069088       0   0             0
1   2021  57304  10.956126       0   0             0
2   2020  64591  11.075830       0   0             0
3   2019  76593  11.246261       0   0             1
4   2018  69470  11.148650       0   0             1
5   2017  66899  11.110939       0   0             1
6   2016  67794  11.124229       0   0             1
7   2015  71030  11.170858       0   0             1
8   2015   3460   8.149024       0   1             1
9   2016   3482   8.155362       0   1             1
10  2017   2858   7.957877       0   1             1
11  2018   3327   8.109826       0   1             1
12  2019   3632   8.197539       0   1             1
13  2020   1976   7.588830       1   1             0
14  2021   1258   7.137278       1   1             0
15  2022   1397   7.242082       1   1             0

In [16]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.995
Model:                            GLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     533.0
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.65e-12
Time:                        17:08:41   Log-Likelihood:                -146.75
No. Observations:                  16   AIC:                             303.5
Df Residuals:                      11   BIC:                             307.4
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -9.466e+05   1.16e+06     -0.817      0.431    -3.5e+06     1.6e+06
Year           499.0833    573.186      0.871      0.403    -762.491    1760.658
Boudin        6531.7333   2900.118      2.252      0.046     148.616    1.29e+04
SF           -6.701e+04   1775.953    -37.729      0.000   -7.09e+04   -6.31e+04
Before_COVID  1.034e+04   3076.040      3.360      0.006    3565.882    1.71e+04
==============================================================================
Omnibus:                        0.910   Durbin-Watson:                   2.028
Prob(Omnibus):                  0.634   Jarque-Bera (JB):                0.078
Skew:                           0.127   Prob(JB):                        0.962
Kurtosis:                       3.229   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [17]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_no2023)
result = model.fit()
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.996
Model:                            GLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                     740.7
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           2.73e-13
Time:                        17:08:41   Log-Likelihood:                 13.855
No. Observations:                  16   AIC:                            -17.71
Df Residuals:                      11   BIC:                            -13.85
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       21.7086     50.642      0.429      0.676     -89.753     133.170
Year            -0.0053      0.025     -0.211      0.837      -0.060       0.050
Boudin          -0.6647      0.127     -5.243      0.000      -0.944      -0.386
SF              -3.0463      0.078    -39.236      0.000      -3.217      -2.875
Before_COVID     0.1054      0.134      0.784      0.450      -0.191       0.401
==============================================================================
Omnibus:                        3.222   Durbin-Watson:                   2.141
Prob(Omnibus):                  0.200   Jarque-Bera (JB):                1.170
Skew:                           0.498   Prob(JB):                        0.557
Kurtosis:                       3.874   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

In [18]:
fed_off_totals_violent = fed_off_by_dist_violent[fed_off_by_dist_violent["District"] == "Total"].reset_index(drop=True)
fed_off_totals_violent = fed_off_totals_violent.iloc[0:, 2:5].drop("Pct", axis = 1)

#Renames the column to be consistent with future dfs
fed_off_totals_violent.rename(columns={'Fiscal_Year': 'Year'}, inplace=True)
fed_off_totals_violent.rename(columns={'N': 'Total'}, inplace=True)

fed_off_totals_violent['Log_Total'] = np.log(fed_off_totals_violent['Total'])
fed_off_totals_violent['Boudin'] = 0
fed_off_totals_violent['SF'] = 0
fed_off_totals_violent['Before_COVID'] = fed_off_totals_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)
fed_off_totals_violent

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

   Year  Total  Log_Total  Boudin  SF  Before_COVID
0  2022   4417   8.393216       0   0             0
1  2021   3438   8.142645       0   0             0
2  2020   3219   8.076826       0   0             0
3  2019   4326   8.372399       0   0             1
4  2018   3973   8.287277       0   0             1
5  2017   3927   8.275631       0   0             1
6  2016   3816   8.246958       0   0             1
7  2015   3835   8.251925       0   0             1

In [19]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sfda_convictions_violent = sf_case_resolutions_violent[["Year", "Conviction"]]
sfda_convictions_violent["Conviction"] = sfda_convictions_violent["Conviction"].astype(int)

#Renames the column to be consistent with future dfs
sfda_convictions_violent.rename(columns={'Conviction': 'Total'}, inplace=True)

sfda_convictions_violent['Log_Total'] = np.log(sfda_convictions_violent['Total'])
sfda_convictions_violent['Boudin'] = sfda_convictions_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sfda_convictions_violent['SF'] = 1
sfda_convictions_violent['Before_COVID'] = sfda_convictions_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)

sfda_convictions_violent_proj = sfda_convictions_violent.copy() #Creates defensive copy
sfda_convictions_violent_proj.iloc[8, 1] = sfda_convictions_violent_proj.iloc[9, 1]

# Drops '2023*' Row
sfda_convictions_violent_proj = sfda_convictions_violent_proj.drop(9)

# Drops '2023*' Row
sfda_convictions_violent = sfda_convictions_violent.drop(9)

sfda_convictions_violent["Year"] = sfda_convictions_violent["Year"].astype(int)
sfda_convictions_violent_proj["Year"] = sfda_convictions_violent_proj["Year"].astype(int)

# This resets warnings
warnings.resetwarnings()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [20]:
# Concatenate vertically (along rows)
sf_fed_off_totals_violent = pd.concat([fed_off_totals_violent, sfda_convictions_violent], axis=0)
sf_fed_off_totals_violent_proj = pd.concat([fed_off_totals_violent, sfda_convictions_violent_proj], axis=0)

# Reset the index
sf_fed_off_totals_violent = sf_fed_off_totals_violent.reset_index(drop=True)
sf_fed_off_totals_violent_proj = sf_fed_off_totals_violent_proj.reset_index(drop=True)

sf_fed_off_totals_violent

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0
16  2023    397   5.983936       0   1             0

### 2023 Inclusive

In [21]:
#2023 Raw & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.978
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     256.9
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.64e-11
Time:                        17:08:41   Log-Likelihood:                -116.98
No. Observations:                  17   AIC:                             244.0
Df Residuals:                      12   BIC:                             248.1
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.469e+05   9.21e+04     -1.595      0.111   -3.28e+05    3.36e+04
Year            74.4883     45.623      1.633      0.103     -14.931     163.908
Boudin           9.6696    245.857      0.039      0.969    -472.202     491.541
SF           -3090.4561    133.479    -23.153      0.000   -3352.070   -2828.842
Before_COVID   723.1614    266.602      2.713      0.007     200.630    1245.692
==============================================================================
Omnibus:                       16.100   Durbin-Watson:                   1.503
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               14.752
Skew:                           1.665   Prob(JB):                     0.000626
Kurtosis:                       6.120   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [22]:
#2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     85.70
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.02e-08
Time:                        17:08:41   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     76.498      0.602      0.547    -103.910     195.958
Year            -0.0188      0.038     -0.496      0.620      -0.093       0.055
Boudin          -0.2319      0.247     -0.940      0.347      -0.715       0.251
SF              -1.5740      0.137    -11.514      0.000      -1.842      -1.306
Before_COVID     0.2509      0.155      1.616      0.106      -0.053       0.555
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [23]:
#2023 Projected & Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     362.7
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           2.12e-12
Time:                        17:08:41   Log-Likelihood:                -116.27
No. Observations:                  17   AIC:                             242.5
Df Residuals:                      12   BIC:                             246.7
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.622e+05   8.96e+04     -1.810      0.070   -3.38e+05    1.34e+04
Year            82.0760     44.363      1.850      0.064      -4.873     169.025
Boudin         -57.1023    227.927     -0.251      0.802    -503.830     389.626
SF           -3054.0351    120.200    -25.408      0.000   -3289.624   -2818.447
Before_COVID   704.9509    274.136      2.572      0.010     167.655    1242.247
==============================================================================
Omnibus:                       15.300   Durbin-Watson:                   1.621
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               13.494
Skew:                           1.612   Prob(JB):                      0.00117
Kurtosis:                       5.942   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [24]:
#2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.958
Model:                            GLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     85.70
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.02e-08
Time:                        17:08:41   Log-Likelihood:                 4.9452
No. Observations:                  17   AIC:                            0.1097
Df Residuals:                      12   BIC:                             4.276
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       46.0238     76.498      0.602      0.547    -103.910     195.958
Year            -0.0188      0.038     -0.496      0.620      -0.093       0.055
Boudin          -0.2319      0.247     -0.940      0.347      -0.715       0.251
SF              -1.5740      0.137    -11.514      0.000      -1.842      -1.306
Before_COVID     0.2509      0.155      1.616      0.106      -0.053       0.555
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   0.988
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                0.760
Skew:                          -0.401   Prob(JB):                        0.684
Kurtosis:                       3.656   Cond. No.                     3.28e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.28e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

### 2023 Exclusive

In [25]:
# Drops '2023' Row
sf_fed_off_totals_violent_no2023 = sf_fed_off_totals_violent[sf_fed_off_totals_violent["Year"] != 2023]
sf_fed_off_totals_violent_no2023

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    Year  Total  Log_Total  Boudin  SF  Before_COVID
0   2022   4417   8.393216       0   0             0
1   2021   3438   8.142645       0   0             0
2   2020   3219   8.076826       0   0             0
3   2019   4326   8.372399       0   0             1
4   2018   3973   8.287277       0   0             1
5   2017   3927   8.275631       0   0             1
6   2016   3816   8.246958       0   0             1
7   2015   3835   8.251925       0   0             1
8   2015   1039   6.946014       0   1             1
9   2016    972   6.879356       0   1             1
10  2017    860   6.756932       0   1             1
11  2018    995   6.902743       0   1             1
12  2019   1088   6.992096       0   1             1
13  2020    635   6.453625       1   1             0
14  2021    438   6.082219       1   1             0
15  2022    494   6.202536       1   1             0

In [26]:
# Total NOT Log Normalized
np.random.seed(29)
formula = "Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:                  Total   R-squared:                       0.979
Model:                            GLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     468.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           3.33e-12
Time:                        17:08:41   Log-Likelihood:                -109.36
No. Observations:                  16   AIC:                             228.7
Df Residuals:                      11   BIC:                             232.6
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.914e+05   1.02e+05     -1.882      0.060   -3.91e+05    7899.103
Year            96.5417     50.369      1.917      0.055      -2.181     195.264
Boudin        -184.4000    340.899     -0.541      0.589    -852.550     483.750
SF           -2984.6000     91.138    -32.748      0.000   -3163.227   -2805.973
Before_COVID   670.2333    322.479      2.078      0.038      38.186    1302.281
==============================================================================
Omnibus:                        8.179   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                4.835
Skew:                           1.094   Prob(JB):                       0.0892
Kurtosis:                       4.569   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [27]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Year + Boudin + SF + Before_COVID" # Location FE: SF; Time FE: Before_COVID
model = smf.gls(formula=formula, data=sf_fed_off_totals_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.986
Model:                            GLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     365.5
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           1.30e-11
Time:                        17:08:41   Log-Likelihood:                 14.123
No. Observations:                  16   AIC:                            -18.25
Df Residuals:                      11   BIC:                            -14.38
Df Model:                           4
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -30.7100     39.446     -0.779      0.436    -108.023      46.603
Year             0.0193      0.020      0.986      0.324      -0.019       0.058
Boudin          -0.5667      0.150     -3.785      0.000      -0.860      -0.273
SF              -1.3914      0.044    -31.383      0.000      -1.478      -1.305
Before_COVID     0.1596      0.105      1.515      0.130      -0.047       0.366
==============================================================================
Omnibus:                        1.663   Durbin-Watson:                   2.070
Prob(Omnibus):                  0.435   Jarque-Bera (JB):                0.790
Skew:                           0.544   Prob(JB):                        0.674
Kurtosis:                       2.994   Cond. No.                     3.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# PART II - SF Before & After Boudin Takes Office (RDD)

## All Crimes

### 2023 Inclusive

In [53]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_all = sf_case_resolutions_all.copy()
sf_cr_all["Conviction"] = sf_cr_all["Conviction"].astype(int)

sf_cr_all['Log_Conviction'] = np.log(sf_cr_all['Conviction'])
sf_cr_all['Log_Total'] = np.log(sf_cr_all['Total'])
sf_cr_all['Boudin'] = sf_cr_all.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_all['Before_COVID'] = sf_cr_all.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_all_proj = sf_cr_all.copy() #Creates defensive copy
sf_cr_all_proj.iloc[8, 1] = sf_cr_all_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_all_proj = sf_cr_all_proj.drop(9)

# Drops '2023*' Row
sf_cr_all = sf_cr_all.drop(9)

# Addresses type issues
sf_cr_all["Year"] = sf_cr_all["Year"].astype(int)
sf_cr_all["Med_Arrest_To_Close"] = sf_cr_all["Med_Arrest_To_Close"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Conviction"] = sf_cr_all["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all["Med_Arrest_To_Close_Dismissal"] = sf_cr_all["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_all_proj["Year"] = sf_cr_all_proj["Year"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close"] = sf_cr_all_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_all_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_all_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_all_no2023 = sf_cr_all[sf_cr_all["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [54]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.880
Model:                            GLS   Adj. R-squared:                  0.809
Method:                 Least Squares   F-statistic:                     83.69
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000108
Time:                        17:14:59   Log-Likelihood:                 11.177
No. Observations:                   9   AIC:                            -14.35
Df Residuals:                       5   BIC:                            -13.57
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -84.9060     43.393     -1.957      0.050    -169.956       0.144
Boudin           0.2475      0.067      3.700      0.000       0.116       0.379
Year             0.0460      0.021      2.146      0.032       0.004       0.088
Before_COVID     0.7476      0.143      5.240      0.000       0.468       1.027
==============================================================================
Omnibus:                        0.472   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.790   Jarque-Bera (JB):                0.248
Skew:                           0.333   Prob(JB):                        0.883
Kurtosis:                       2.533   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [55]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.880
Model:                            GLS   Adj. R-squared:                  0.809
Method:                 Least Squares   F-statistic:                     83.69
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000108
Time:                        17:14:59   Log-Likelihood:                 11.177
No. Observations:                   9   AIC:                            -14.35
Df Residuals:                       5   BIC:                            -13.57
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept      -84.9060     43.393     -1.957      0.050    -169.956       0.144
Boudin           0.2475      0.067      3.700      0.000       0.116       0.379
Year             0.0460      0.021      2.146      0.032       0.004       0.088
Before_COVID     0.7476      0.143      5.240      0.000       0.468       1.027
==============================================================================
Omnibus:                        0.472   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.790   Jarque-Bera (JB):                0.248
Skew:                           0.333   Prob(JB):                        0.883
Kurtosis:                       2.533   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [56]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.916
Model:                            GLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     126.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           3.89e-05
Time:                        17:14:59   Log-Likelihood:                 6.0050
No. Observations:                   9   AIC:                            -4.010
Df Residuals:                       5   BIC:                            -3.221
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       56.9768     82.649      0.689      0.491    -105.012     218.965
Boudin           0.0716      0.122      0.588      0.556      -0.167       0.310
Year            -0.0246      0.041     -0.602      0.547      -0.105       0.055
Before_COVID     0.7644      0.275      2.777      0.005       0.225       1.304
==============================================================================
Omnibus:                        0.553   Durbin-Watson:                   2.080
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.256
Skew:                           0.353   Prob(JB):                        0.880
Kurtosis:                       2.571   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [57]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.916
Model:                            GLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     126.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           3.89e-05
Time:                        17:14:59   Log-Likelihood:                 6.0050
No. Observations:                   9   AIC:                            -4.010
Df Residuals:                       5   BIC:                            -3.221
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       56.9768     82.649      0.689      0.491    -105.012     218.965
Boudin           0.0716      0.122      0.588      0.556      -0.167       0.310
Year            -0.0246      0.041     -0.602      0.547      -0.105       0.055
Before_COVID     0.7644      0.275      2.777      0.005       0.225       1.304
==============================================================================
Omnibus:                        0.553   Durbin-Watson:                   2.080
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.256
Skew:                           0.353   Prob(JB):                        0.880
Kurtosis:                       2.571   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [58]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.913
Model:                              GLS   Adj. R-squared:                  0.861
Method:                   Least Squares   F-statistic:                     16.28
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):            0.00517
Time:                          17:14:59   Log-Likelihood:                -55.955
No. Observations:                     9   AIC:                             119.9
Df Residuals:                         5   BIC:                             120.7
Df Model:                             3
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.254e+05   1.17e+05     -2.779      0.005   -5.55e+05   -9.59e+04
Boudin         599.8333    139.085      4.313      0.000     327.233     872.434
Year           161.4167     57.886      2.789      0.005      47.961     274.872
Before_COVID   498.1000    344.183      1.447      0.148    -176.485    1172.685
==============================================================================
Omnibus:                        0.211   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.900   Jarque-Bera (JB):                0.376
Skew:                           0.154   Prob(JB):                        0.828
Kurtosis:                       2.047   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [59]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.913
Model:                              GLS   Adj. R-squared:                  0.861
Method:                   Least Squares   F-statistic:                     16.28
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):            0.00517
Time:                          17:14:59   Log-Likelihood:                -55.955
No. Observations:                     9   AIC:                             119.9
Df Residuals:                         5   BIC:                             120.7
Df Model:                             3
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.254e+05   1.17e+05     -2.779      0.005   -5.55e+05   -9.59e+04
Boudin         599.8333    139.085      4.313      0.000     327.233     872.434
Year           161.4167     57.886      2.789      0.005      47.961     274.872
Before_COVID   498.1000    344.183      1.447      0.148    -176.485    1172.685
==============================================================================
Omnibus:                        0.211   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.900   Jarque-Bera (JB):                0.376
Skew:                           0.154   Prob(JB):                        0.828
Kurtosis:                       2.047   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [60]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.963
Model:                             GLS   Adj. R-squared:                  0.941
Method:                  Least Squares   F-statistic:                     926.0
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):           2.79e-07
Time:                         17:14:59   Log-Likelihood:                -39.339
No. Observations:                    9   AIC:                             86.68
Df Residuals:                        5   BIC:                             87.47
Df Model:                            3
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.058e+04   1.12e+04     -3.614      0.000   -6.26e+04   -1.86e+04
Boudin          33.8333     20.550      1.646      0.100      -6.443      74.110
Year            20.2500      5.550      3.649      0.000       9.373      31.127
Before_COVID   -74.9000     35.314     -2.121      0.034    -144.114      -5.686
==============================================================================
Omnibus:                        2.843   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.241   Jarque-Bera (JB):                0.254
Skew:                          -0.067   Prob(JB):                        0.881
Kurtosis:                       3.813   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [61]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.963
Model:                             GLS   Adj. R-squared:                  0.941
Method:                  Least Squares   F-statistic:                     926.0
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):           2.79e-07
Time:                         17:14:59   Log-Likelihood:                -39.339
No. Observations:                    9   AIC:                             86.68
Df Residuals:                        5   BIC:                             87.47
Df Model:                            3
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.058e+04   1.12e+04     -3.614      0.000   -6.26e+04   -1.86e+04
Boudin          33.8333     20.550      1.646      0.100      -6.443      74.110
Year            20.2500      5.550      3.649      0.000       9.373      31.127
Before_COVID   -74.9000     35.314     -2.121      0.034    -144.114      -5.686
==============================================================================
Omnibus:                        2.843   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.241   Jarque-Bera (JB):                0.254
Skew:                          -0.067   Prob(JB):                        0.881
Kurtosis:                       3.813   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [62]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.993
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     431.5
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):           1.87e-06
Time:                                    17:14:59   Log-Likelihood:                -28.819
No. Observations:                               9   AIC:                             65.64
Df Residuals:                                   5   BIC:                             66.43
Df Model:                                       3
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.104e+04   4124.611     -7.527      0.000   -3.91e+04    -2.3e+04
Boudin          26.3333      4.999      5.267      0.000      16.535      36.132
Year            15.5000      2.039      7.602      0.000      11.504      19.496
Before_COVID   -50.2000     13.427     -3.739      0.000     -76.516     -23.884
==============================================================================
Omnibus:                        1.206   Durbin-Watson:                   1.764
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.710
Skew:                           0.625   Prob(JB):                        0.701
Kurtosis:                       2.425   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [63]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.993
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     431.5
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):           1.87e-06
Time:                                    17:14:59   Log-Likelihood:                -28.819
No. Observations:                               9   AIC:                             65.64
Df Residuals:                                   5   BIC:                             66.43
Df Model:                                       3
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.104e+04   4124.611     -7.527      0.000   -3.91e+04    -2.3e+04
Boudin          26.3333      4.999      5.267      0.000      16.535      36.132
Year            15.5000      2.039      7.602      0.000      11.504      19.496
Before_COVID   -50.2000     13.427     -3.739      0.000     -76.516     -23.884
==============================================================================
Omnibus:                        1.206   Durbin-Watson:                   1.764
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.710
Skew:                           0.625   Prob(JB):                        0.701
Kurtosis:                       2.425   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [64]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.927
Model:                                       GLS   Adj. R-squared:                  0.883
Method:                            Least Squares   F-statistic:                     144.9
Date:                           Thu, 28 Sep 2023   Prob (F-statistic):           2.80e-05
Time:                                   17:14:59   Log-Likelihood:                -38.402
No. Observations:                              9   AIC:                             84.80
Df Residuals:                                  5   BIC:                             85.59
Df Model:                                      3
Covariance Type:                             HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.195e+04   1.47e+04     -0.814      0.416   -4.07e+04    1.68e+04
Boudin         -65.8333     22.954     -2.868      0.004    -110.821     -20.845
Year             6.0833      7.256      0.838      0.402      -8.138      20.305
Before_COVID  -136.3000     47.721     -2.856      0.004    -229.832     -42.768
==============================================================================
Omnibus:                        0.572   Durbin-Watson:                   2.046
Prob(Omnibus):                  0.751   Jarque-Bera (JB):                0.502
Skew:                          -0.003   Prob(JB):                        0.778
Kurtosis:                       1.843   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [65]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.999
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     1643.
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000609
Time:                        17:14:59   Log-Likelihood:                 33.812
No. Observations:                   9   AIC:                            -53.62
Df Residuals:                       2   BIC:                            -52.24
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -365.0293     27.144    -13.448      0.000    -418.230    -311.828
Boudin                             0.4844      0.026     18.764      0.000       0.434       0.535
Year                               0.1859      0.014     13.732      0.000       0.159       0.212
Before_COVID                       0.2739      0.052      5.247      0.000       0.172       0.376
Med_Arrest_To_Close               -0.0024      0.000    -18.018      0.000      -0.003      -0.002
Med_Arrest_To_Close_Conviction    -0.0059      0.001     -7.788      0.000      -0.007      -0.004
Med_Arrest_To_Close_Dismissal   9.208e-06      0.000      0.034      0.973      -0.001       0.001
==============================================================================
Omnibus:                        1.466   Durbin-Watson:                   2.441
Prob(Omnibus):                  0.480   Jarque-Bera (JB):                0.614
Skew:                           0.621   Prob(JB):                        0.735
Kurtosis:                       2.687   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [66]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.999
Model:                            GLS   Adj. R-squared:                  0.997
Method:                 Least Squares   F-statistic:                     1643.
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000609
Time:                        17:14:59   Log-Likelihood:                 33.812
No. Observations:                   9   AIC:                            -53.62
Df Residuals:                       2   BIC:                            -52.24
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -365.0293     27.144    -13.448      0.000    -418.230    -311.828
Boudin                             0.4844      0.026     18.764      0.000       0.434       0.535
Year                               0.1859      0.014     13.732      0.000       0.159       0.212
Before_COVID                       0.2739      0.052      5.247      0.000       0.172       0.376
Med_Arrest_To_Close               -0.0024      0.000    -18.018      0.000      -0.003      -0.002
Med_Arrest_To_Close_Conviction    -0.0059      0.001     -7.788      0.000      -0.007      -0.004
Med_Arrest_To_Close_Dismissal   9.208e-06      0.000      0.034      0.973      -0.001       0.001
==============================================================================
Omnibus:                        1.466   Durbin-Watson:                   2.441
Prob(Omnibus):                  0.480   Jarque-Bera (JB):                0.614
Skew:                           0.621   Prob(JB):                        0.735
Kurtosis:                       2.687   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [67]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                     1000.
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000999
Time:                        17:14:59   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -28.50
Df Residuals:                       2   BIC:                            -27.12
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.8469    103.756     -3.738      0.000    -591.204    -184.490
Boudin                             0.4843      0.094      5.150      0.000       0.300       0.669
Year                               0.1974      0.052      3.813      0.000       0.096       0.299
Before_COVID                       0.0626      0.221      0.284      0.776      -0.370       0.495
Med_Arrest_To_Close               -0.0044      0.001     -8.084      0.000      -0.005      -0.003
Med_Arrest_To_Close_Conviction    -0.0088      0.004     -2.495      0.013      -0.016      -0.002
Med_Arrest_To_Close_Dismissal      0.0005      0.001      0.807      0.419      -0.001       0.002
==============================================================================
Omnibus:                        7.408   Durbin-Watson:                   3.048
Prob(Omnibus):                  0.025   Jarque-Bera (JB):                2.497
Skew:                           1.173   Prob(JB):                        0.287
Kurtosis:                       4.076   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [68]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                     1000.
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000999
Time:                        17:14:59   Log-Likelihood:                 21.248
No. Observations:                   9   AIC:                            -28.50
Df Residuals:                       2   BIC:                            -27.12
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -387.8469    103.756     -3.738      0.000    -591.204    -184.490
Boudin                             0.4843      0.094      5.150      0.000       0.300       0.669
Year                               0.1974      0.052      3.813      0.000       0.096       0.299
Before_COVID                       0.0626      0.221      0.284      0.776      -0.370       0.495
Med_Arrest_To_Close               -0.0044      0.001     -8.084      0.000      -0.005      -0.003
Med_Arrest_To_Close_Conviction    -0.0088      0.004     -2.495      0.013      -0.016      -0.002
Med_Arrest_To_Close_Dismissal      0.0005      0.001      0.807      0.419      -0.001       0.002
==============================================================================
Omnibus:                        7.408   Durbin-Watson:                   3.048
Prob(Omnibus):                  0.025   Jarque-Bera (JB):                2.497
Skew:                           1.173   Prob(JB):                        0.287
Kurtosis:                       4.076   Cond. No.                     1.16e+07
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [76]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.829
Model:                            GLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     7.916
Date:                Thu, 28 Sep 2023   Prob (F-statistic):             0.0282
Time:                        17:16:57   Log-Likelihood:                 9.4643
No. Observations:                   8   AIC:                            -12.93
Df Residuals:                       5   BIC:                            -12.69
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -84.1583     40.780     -2.064      0.039    -164.086      -4.231
Boudin        -0.5002      0.145     -3.460      0.001      -0.784      -0.217
Year           0.0460      0.020      2.276      0.023       0.006       0.086
==============================================================================
Omnibus:                        0.282   Durbin-Watson:                   2.069
Prob(Omnibus):                  0.869   Jarque-Bera (JB):                0.318
Skew:                           0.314   Prob(JB):                        0.853
Kurtosis:                       2.251   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [70]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.895
Model:                            GLS   Adj. R-squared:                  0.853
Method:                 Least Squares   F-statistic:                     29.98
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00164
Time:                        17:15:22   Log-Likelihood:                 4.8666
No. Observations:                   8   AIC:                            -3.733
Df Residuals:                       5   BIC:                            -3.495
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     57.7411     77.667      0.743      0.457     -94.483     209.965
Boudin        -0.6928      0.266     -2.607      0.009      -1.214      -0.172
Year          -0.0246      0.039     -0.639      0.523      -0.100       0.051
==============================================================================
Omnibus:                        0.324   Durbin-Watson:                   2.057
Prob(Omnibus):                  0.851   Jarque-Bera (JB):                0.318
Skew:                           0.333   Prob(JB):                        0.853
Kurtosis:                       2.285   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [71]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.911
Model:                              GLS   Adj. R-squared:                  0.876
Method:                   Least Squares   F-statistic:                     27.20
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):            0.00206
Time:                          17:15:34   Log-Likelihood:                -50.209
No. Observations:                     8   AIC:                             106.4
Df Residuals:                         5   BIC:                             106.7
Df Model:                             2
Covariance Type:                    HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.249e+05    1.1e+05     -2.951      0.003   -5.41e+05   -1.09e+05
Boudin       101.7333    220.148      0.462      0.644    -329.748     533.215
Year         161.4167     54.576      2.958      0.003      54.450     268.383
==============================================================================
Omnibus:                        0.561   Durbin-Watson:                   1.687
Prob(Omnibus):                  0.756   Jarque-Bera (JB):                0.493
Skew:                           0.146   Prob(JB):                        0.782
Kurtosis:                       1.820   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [72]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.956
Model:                             GLS   Adj. R-squared:                  0.939
Method:                  Least Squares   F-statistic:                     96.68
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):           0.000101
Time:                         17:15:47   Log-Likelihood:                -35.439
No. Observations:                    8   AIC:                             76.88
Df Residuals:                        5   BIC:                             77.12
Df Model:                            2
Covariance Type:                   HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.065e+04   1.06e+04     -3.853      0.000   -6.13e+04      -2e+04
Boudin       108.7333     40.079      2.713      0.007      30.180     187.286
Year          20.2500      5.232      3.870      0.000       9.995      30.505
==============================================================================
Omnibus:                        2.024   Durbin-Watson:                   2.562
Prob(Omnibus):                  0.364   Jarque-Bera (JB):                0.056
Skew:                          -0.063   Prob(JB):                        0.972
Kurtosis:                       3.389   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [73]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.992
Model:                                        GLS   Adj. R-squared:                  0.989
Method:                             Least Squares   F-statistic:                     436.5
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):           2.45e-06
Time:                                    17:15:58   Log-Likelihood:                -26.088
No. Observations:                               8   AIC:                             58.18
Df Residuals:                                   5   BIC:                             58.41
Df Model:                                       2
Covariance Type:                              HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.109e+04   3876.695     -8.021      0.000   -3.87e+04   -2.35e+04
Boudin        76.5333     10.277      7.447      0.000      56.390      96.677
Year          15.5000      1.922      8.063      0.000      11.732      19.268
==============================================================================
Omnibus:                        0.987   Durbin-Watson:                   1.710
Prob(Omnibus):                  0.610   Jarque-Bera (JB):                0.701
Skew:                           0.589   Prob(JB):                        0.704
Kurtosis:                       2.155   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [74]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_all_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.807
Model:                                       GLS   Adj. R-squared:                  0.742
Method:                            Least Squares   F-statistic:                     14.43
Date:                           Thu, 28 Sep 2023   Prob (F-statistic):            0.00510
Time:                                   17:16:22   Log-Likelihood:                -42.790
No. Observations:                              9   AIC:                             91.58
Df Residuals:                                  6   BIC:                             92.17
Df Model:                                      2
Covariance Type:                             HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.481e+04   1.05e+04     -4.252      0.000   -6.55e+04   -2.42e+04
Boudin        -0.9286     34.298     -0.027      0.978     -68.151      66.294
Year          22.3095      5.224      4.271      0.000      12.071      32.548
==============================================================================
Omnibus:                        0.411   Durbin-Watson:                   2.320
Prob(Omnibus):                  0.814   Jarque-Bera (JB):                0.475
Skew:                          -0.246   Prob(JB):                        0.789
Kurtosis:                       1.988   Cond. No.                     1.89e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.89e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [77]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.990
Model:                            GLS   Adj. R-squared:                  0.973
Method:                 Least Squares   F-statistic:                     197.3
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000565
Time:                        17:17:37   Log-Likelihood:                 22.334
No. Observations:                   9   AIC:                            -32.67
Df Residuals:                       3   BIC:                            -31.48
Df Model:                           5
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -426.5880     52.814     -8.077      0.000    -530.101    -323.075
Boudin                             0.4582      0.080      5.727      0.000       0.301       0.615
Year                               0.2168      0.026      8.250      0.000       0.165       0.268
Med_Arrest_To_Close               -0.0027      0.001     -3.298      0.001      -0.004      -0.001
Med_Arrest_To_Close_Conviction    -0.0075      0.002     -3.236      0.001      -0.012      -0.003
Med_Arrest_To_Close_Dismissal     -0.0008      0.000     -1.880      0.060      -0.002    3.56e-05
==============================================================================
Omnibus:                        1.552   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.460   Jarque-Bera (JB):                0.559
Skew:                           0.601   Prob(JB):                        0.756
Kurtosis:                       2.788   Cond. No.                     9.58e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.58e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [78]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_all)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.997
Model:                            GLS   Adj. R-squared:                  0.992
Method:                 Least Squares   F-statistic:                     622.5
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000101
Time:                        17:17:56   Log-Likelihood:                 21.081
No. Observations:                   9   AIC:                            -30.16
Df Residuals:                       3   BIC:                            -28.98
Df Model:                           5
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -401.9264     63.730     -6.307      0.000    -526.835    -277.017
Boudin                             0.4784      0.079      6.089      0.000       0.324       0.632
Year                               0.2045      0.032      6.450      0.000       0.142       0.267
Med_Arrest_To_Close               -0.0045      0.001     -7.413      0.000      -0.006      -0.003
Med_Arrest_To_Close_Conviction    -0.0091      0.002     -4.277      0.000      -0.013      -0.005
Med_Arrest_To_Close_Dismissal      0.0003      0.000      0.848      0.397      -0.000       0.001
==============================================================================
Omnibus:                        5.962   Durbin-Watson:                   2.974
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                2.014
Skew:                           1.107   Prob(JB):                        0.365
Kurtosis:                       3.682   Cond. No.                     9.58e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 9.58e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

## Violent Crimes

### 2023 Inclusive

In [79]:
# This temporarily disables warnings; A warning of a depreciated opperation displayed
warnings.filterwarnings('ignore')

sf_cr_violent = sf_case_resolutions_violent.copy()
sf_cr_violent["Conviction"] = sf_cr_violent["Conviction"].astype(int)

sf_cr_violent['Log_Conviction'] = np.log(sf_cr_violent['Conviction'])
sf_cr_violent['Log_Total'] = np.log(sf_cr_violent['Total'])
sf_cr_violent['Boudin'] = sf_cr_violent.apply(lambda row : year_marker(row['Year'],
                                                                             2020, 2022),
                                                    axis = 1)
sf_cr_violent['Before_COVID'] = sf_cr_violent.apply(lambda row :
                                                              year_marker(row['Year'],
                                                                          2020, mode = 'before'),
                                                              axis = 1)



sf_cr_violent_proj = sf_cr_violent.copy() #Creates defensive copy
sf_cr_violent_proj.iloc[8, 1] = sf_cr_violent_proj.iloc[9, 1] #Moves 2023* to 2023 slot

# Drops '2023*' Row
sf_cr_violent_proj = sf_cr_violent_proj.drop(9)

# Drops '2023*' Row
sf_cr_violent = sf_cr_violent.drop(9)

# Addresses type issues
sf_cr_violent["Year"] = sf_cr_violent["Year"].astype(int)
sf_cr_violent["Med_Arrest_To_Close"] = sf_cr_violent["Med_Arrest_To_Close"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Conviction"] = sf_cr_violent["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent["Med_Arrest_To_Close_Dismissal"].astype(int)

sf_cr_violent_proj["Year"] = sf_cr_violent_proj["Year"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close"] = sf_cr_violent_proj["Med_Arrest_To_Close"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"] = sf_cr_violent_proj["Med_Arrest_To_Close_Conviction"].astype(int)
sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"] = sf_cr_violent_proj["Med_Arrest_To_Close_Dismissal"].astype(int)

# Gets rid of 2023 Row
sf_cr_violent_no2023 = sf_cr_violent[sf_cr_violent["Year"] != 2023]

# This resets warnings
warnings.resetwarnings()

In [80]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.833
Model:                            GLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     37.23
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000762
Time:                        17:18:29   Log-Likelihood:                 10.557
No. Observations:                   9   AIC:                            -13.11
Df Residuals:                       5   BIC:                            -12.32
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -103.5084     59.362     -1.744      0.081    -219.856      12.839
Boudin           0.2378      0.079      2.992      0.003       0.082       0.394
Year             0.0546      0.029      1.862      0.063      -0.003       0.112
Before_COVID     0.7266      0.193      3.761      0.000       0.348       1.105
==============================================================================
Omnibus:                        1.157   Durbin-Watson:                   1.532
Prob(Omnibus):                  0.561   Jarque-Bera (JB):                0.853
Skew:                           0.597   Prob(JB):                        0.653
Kurtosis:                       2.079   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [82]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.833
Model:                            GLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     37.23
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           0.000762
Time:                        17:19:02   Log-Likelihood:                 10.557
No. Observations:                   9   AIC:                            -13.11
Df Residuals:                       5   BIC:                            -12.32
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     -103.5084     59.362     -1.744      0.081    -219.856      12.839
Boudin           0.2378      0.079      2.992      0.003       0.082       0.394
Year             0.0546      0.029      1.862      0.063      -0.003       0.112
Before_COVID     0.7266      0.193      3.761      0.000       0.348       1.105
==============================================================================
Omnibus:                        1.157   Durbin-Watson:                   1.532
Prob(Omnibus):                  0.561   Jarque-Bera (JB):                0.853
Skew:                           0.597   Prob(JB):                        0.653
Kurtosis:                       2.079   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [83]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.874
Method:                 Least Squares   F-statistic:                     140.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           3.00e-05
Time:                        17:19:13   Log-Likelihood:                 7.4034
No. Observations:                   9   AIC:                            -6.807
Df Residuals:                       5   BIC:                            -6.018
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.8333     71.759      0.402      0.688    -111.812     169.479
Boudin           0.2396      0.104      2.303      0.021       0.036       0.444
Year            -0.0113      0.035     -0.318      0.750      -0.081       0.058
Before_COVID     0.8437      0.240      3.523      0.000       0.374       1.313
==============================================================================
Omnibus:                        0.166   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.920   Jarque-Bera (JB):                0.188
Skew:                           0.200   Prob(JB):                        0.910
Kurtosis:                       2.416   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [84]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.921
Model:                            GLS   Adj. R-squared:                  0.874
Method:                 Least Squares   F-statistic:                     140.8
Date:                Thu, 28 Sep 2023   Prob (F-statistic):           3.00e-05
Time:                        17:19:27   Log-Likelihood:                 7.4034
No. Observations:                   9   AIC:                            -6.807
Df Residuals:                       5   BIC:                            -6.018
Df Model:                           3
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       28.8333     71.759      0.402      0.688    -111.812     169.479
Boudin           0.2396      0.104      2.303      0.021       0.036       0.444
Year            -0.0113      0.035     -0.318      0.750      -0.081       0.058
Before_COVID     0.8437      0.240      3.523      0.000       0.374       1.313
==============================================================================
Omnibus:                        0.166   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.920   Jarque-Bera (JB):                0.188
Skew:                           0.200   Prob(JB):                        0.910
Kurtosis:                       2.416   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [85]:
# 2023 Raw & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.939
Model:                              GLS   Adj. R-squared:                  0.903
Method:                   Least Squares   F-statistic:                     44.94
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):           0.000486
Time:                          17:19:38   Log-Likelihood:                -44.154
No. Observations:                     9   AIC:                             96.31
Df Residuals:                         5   BIC:                             97.10
Df Model:                             3
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.035e+05   3.21e+04     -3.225      0.001   -1.66e+05   -4.06e+04
Boudin         126.6667     38.811      3.264      0.001      50.599     202.735
Year            51.3333     15.860      3.237      0.001      20.249      82.418
Before_COVID    96.8000    105.445      0.918      0.359    -109.868     303.468
==============================================================================
Omnibus:                        0.657   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.576
Skew:                           0.288   Prob(JB):                        0.750
Kurtosis:                       1.903   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [86]:
# 2023 Projected & Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.939
Model:                              GLS   Adj. R-squared:                  0.903
Method:                   Least Squares   F-statistic:                     44.94
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):           0.000486
Time:                          17:19:51   Log-Likelihood:                -44.154
No. Observations:                     9   AIC:                             96.31
Df Residuals:                         5   BIC:                             97.10
Df Model:                             3
Covariance Type:                    HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -1.035e+05   3.21e+04     -3.225      0.001   -1.66e+05   -4.06e+04
Boudin         126.6667     38.811      3.264      0.001      50.599     202.735
Year            51.3333     15.860      3.237      0.001      20.249      82.418
Before_COVID    96.8000    105.445      0.918      0.359    -109.868     303.468
==============================================================================
Omnibus:                        0.657   Durbin-Watson:                   1.453
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.576
Skew:                           0.288   Prob(JB):                        0.750
Kurtosis:                       1.903   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [87]:
# 2023 Raw & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.942
Model:                             GLS   Adj. R-squared:                  0.907
Method:                  Least Squares   F-statistic:                     323.7
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):           3.82e-06
Time:                         17:20:05   Log-Likelihood:                -43.566
No. Observations:                    9   AIC:                             95.13
Df Residuals:                        5   BIC:                             95.92
Df Model:                            3
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.225e+04   1.73e+04     -2.443      0.015   -7.62e+04   -8348.531
Boudin          92.1667     44.757      2.059      0.039       4.444     179.889
Year            21.0833      8.550      2.466      0.014       4.326      37.841
Before_COVID   -76.9000     58.850     -1.307      0.191    -192.244      38.444
==============================================================================
Omnibus:                        2.997   Durbin-Watson:                   3.394
Prob(Omnibus):                  0.223   Jarque-Bera (JB):                0.860
Skew:                           0.749   Prob(JB):                        0.651
Kurtosis:                       3.223   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [88]:
# 2023 Projected & Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.942
Model:                             GLS   Adj. R-squared:                  0.907
Method:                  Least Squares   F-statistic:                     323.7
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):           3.82e-06
Time:                         17:20:20   Log-Likelihood:                -43.566
No. Observations:                    9   AIC:                             95.13
Df Residuals:                        5   BIC:                             95.92
Df Model:                            3
Covariance Type:                   HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -4.225e+04   1.73e+04     -2.443      0.015   -7.62e+04   -8348.531
Boudin          92.1667     44.757      2.059      0.039       4.444     179.889
Year            21.0833      8.550      2.466      0.014       4.326      37.841
Before_COVID   -76.9000     58.850     -1.307      0.191    -192.244      38.444
==============================================================================
Omnibus:                        2.997   Durbin-Watson:                   3.394
Prob(Omnibus):                  0.223   Jarque-Bera (JB):                0.860
Skew:                           0.749   Prob(JB):                        0.651
Kurtosis:                       3.223   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [89]:
# 2023 Raw & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.953
Model:                                        GLS   Adj. R-squared:                  0.924
Method:                             Least Squares   F-statistic:                     260.7
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):           6.54e-06
Time:                                    17:20:52   Log-Likelihood:                -41.987
No. Observations:                               9   AIC:                             91.97
Df Residuals:                                   5   BIC:                             92.76
Df Model:                                       3
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.773e+04   1.41e+04     -2.672      0.008   -6.54e+04   -1.01e+04
Boudin          90.6667     42.062      2.156      0.031       8.226     173.107
Year            18.8333      6.979      2.699      0.007       5.155      32.512
Before_COVID   -73.2000     43.293     -1.691      0.091    -158.052      11.652
==============================================================================
Omnibus:                        2.270   Durbin-Watson:                   2.996
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                0.140
Skew:                           0.078   Prob(JB):                        0.932
Kurtosis:                       3.592   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [90]:
# 2023 Projected & Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.953
Model:                                        GLS   Adj. R-squared:                  0.924
Method:                             Least Squares   F-statistic:                     260.7
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):           6.54e-06
Time:                                    17:21:04   Log-Likelihood:                -41.987
No. Observations:                               9   AIC:                             91.97
Df Residuals:                                   5   BIC:                             92.76
Df Model:                                       3
Covariance Type:                              HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.773e+04   1.41e+04     -2.672      0.008   -6.54e+04   -1.01e+04
Boudin          90.6667     42.062      2.156      0.031       8.226     173.107
Year            18.8333      6.979      2.699      0.007       5.155      32.512
Before_COVID   -73.2000     43.293     -1.691      0.091    -158.052      11.652
==============================================================================
Omnibus:                        2.270   Durbin-Watson:                   2.996
Prob(Omnibus):                  0.321   Jarque-Bera (JB):                0.140
Skew:                           0.078   Prob(JB):                        0.932
Kurtosis:                       3.592   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [91]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year + Before_COVID"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.909
Model:                                       GLS   Adj. R-squared:                  0.855
Method:                            Least Squares   F-statistic:                     98.55
Date:                           Thu, 28 Sep 2023   Prob (F-statistic):           7.22e-05
Time:                                   17:21:13   Log-Likelihood:                -43.266
No. Observations:                              9   AIC:                             94.53
Df Residuals:                                  5   BIC:                             95.32
Df Model:                                      3
Covariance Type:                             HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -2.626e+04      2e+04     -1.311      0.190   -6.55e+04     1.3e+04
Boudin         -14.6667     29.496     -0.497      0.619     -72.478      43.145
Year            13.1667      9.902      1.330      0.184      -6.241      32.575
Before_COVID  -136.6000     63.202     -2.161      0.031    -260.474     -12.726
==============================================================================
Omnibus:                        2.568   Durbin-Watson:                   2.466
Prob(Omnibus):                  0.277   Jarque-Bera (JB):                1.209
Skew:                          -0.883   Prob(JB):                        0.546
Kurtosis:                       2.674   Cond. No.                     3.54e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.54e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [92]:
# 2023 Raw & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit()
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     9.685
Date:                Thu, 28 Sep 2023   Prob (F-statistic):             0.0965
Time:                        17:21:33   Log-Likelihood:                 17.819
No. Observations:                   9   AIC:                            -21.64
Df Residuals:                       2   BIC:                            -20.26
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -196.9036     64.578     -3.049      0.093    -474.762      80.955
Boudin                             0.1195      0.131      0.914      0.457      -0.443       0.682
Year                               0.1016      0.032      3.157      0.087      -0.037       0.240
Before_COVID                       0.0161      0.322      0.050      0.965      -1.368       1.400
Med_Arrest_To_Close                0.0099      0.005      1.941      0.192      -0.012       0.032
Med_Arrest_To_Close_Conviction    -0.0096      0.005     -1.845      0.206      -0.032       0.013
Med_Arrest_To_Close_Dismissal     -0.0056      0.002     -2.571      0.124      -0.015       0.004
==============================================================================
Omnibus:                        3.691   Durbin-Watson:                   2.801
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                0.915
Skew:                          -0.734   Prob(JB):                        0.633
Kurtosis:                       3.537   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [93]:
# 2023 Projected & Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.867
Method:                 Least Squares   F-statistic:                     87.75
Date:                Thu, 28 Sep 2023   Prob (F-statistic):             0.0113
Time:                        17:21:49   Log-Likelihood:                 17.819
No. Observations:                   9   AIC:                            -21.64
Df Residuals:                       2   BIC:                            -20.26
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -196.9036     48.155     -4.089      0.000    -291.285    -102.522
Boudin                             0.1195      0.031      3.870      0.000       0.059       0.180
Year                               0.1016      0.024      4.254      0.000       0.055       0.148
Before_COVID                       0.0161      0.250      0.064      0.949      -0.473       0.505
Med_Arrest_To_Close                0.0099      0.004      2.308      0.021       0.001       0.018
Med_Arrest_To_Close_Conviction    -0.0096      0.005     -2.090      0.037      -0.019      -0.001
Med_Arrest_To_Close_Dismissal     -0.0056      0.001     -3.843      0.000      -0.008      -0.003
==============================================================================
Omnibus:                        3.691   Durbin-Watson:                   2.801
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                0.915
Skew:                          -0.734   Prob(JB):                        0.633
Kurtosis:                       3.537   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [94]:
# 2023 Raw & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.992
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     191.1
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00522
Time:                        17:22:08   Log-Likelihood:                 17.937
No. Observations:                   9   AIC:                            -21.87
Df Residuals:                       2   BIC:                            -20.49
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -154.4127     51.498     -2.998      0.003    -255.346     -53.479
Boudin                             0.1800      0.033      5.414      0.000       0.115       0.245
Year                               0.0808      0.026      3.154      0.002       0.031       0.131
Before_COVID                      -0.2949      0.265     -1.114      0.265      -0.814       0.224
Med_Arrest_To_Close                0.0151      0.005      3.236      0.001       0.006       0.024
Med_Arrest_To_Close_Conviction    -0.0160      0.005     -3.234      0.001      -0.026      -0.006
Med_Arrest_To_Close_Dismissal     -0.0082      0.002     -4.966      0.000      -0.012      -0.005
==============================================================================
Omnibus:                        1.803   Durbin-Watson:                   3.003
Prob(Omnibus):                  0.406   Jarque-Bera (JB):                0.712
Skew:                          -0.679   Prob(JB):                        0.700
Kurtosis:                       2.765   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [95]:
# 2023 Projected & Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Before_COVID + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.992
Model:                            GLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     191.1
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00522
Time:                        17:22:20   Log-Likelihood:                 17.937
No. Observations:                   9   AIC:                            -21.87
Df Residuals:                       2   BIC:                            -20.49
Df Model:                           6
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -154.4127     51.498     -2.998      0.003    -255.346     -53.479
Boudin                             0.1800      0.033      5.414      0.000       0.115       0.245
Year                               0.0808      0.026      3.154      0.002       0.031       0.131
Before_COVID                      -0.2949      0.265     -1.114      0.265      -0.814       0.224
Med_Arrest_To_Close                0.0151      0.005      3.236      0.001       0.006       0.024
Med_Arrest_To_Close_Conviction    -0.0160      0.005     -3.234      0.001      -0.026      -0.006
Med_Arrest_To_Close_Dismissal     -0.0082      0.002     -4.966      0.000      -0.012      -0.005
==============================================================================
Omnibus:                        1.803   Durbin-Watson:                   3.003
Prob(Omnibus):                  0.406   Jarque-Bera (JB):                0.712
Skew:                          -0.679   Prob(JB):                        0.700
Kurtosis:                       2.765   Cond. No.                     5.68e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.68e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### 2023 Exclusive
(Note: Can't Use Before_COVID because between (2015 & 2022), Boudin & Before_COVID are **Linearly Dependent**)

In [96]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.774
Model:                            GLS   Adj. R-squared:                  0.684
Method:                 Least Squares   F-statistic:                     5.642
Date:                Thu, 28 Sep 2023   Prob (F-statistic):             0.0522
Time:                        17:22:45   Log-Likelihood:                 8.9127
No. Observations:                   8   AIC:                            -11.83
Df Residuals:                       5   BIC:                            -11.59
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -102.7817     55.788     -1.842      0.065    -212.125       6.561
Boudin        -0.4889      0.165     -2.963      0.003      -0.812      -0.166
Year           0.0546      0.028      1.975      0.048       0.000       0.109
==============================================================================
Omnibus:                        1.316   Durbin-Watson:                   1.444
Prob(Omnibus):                  0.518   Jarque-Bera (JB):                0.865
Skew:                           0.563   Prob(JB):                        0.649
Kurtosis:                       1.848   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [97]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.886
Model:                            GLS   Adj. R-squared:                  0.841
Method:                 Least Squares   F-statistic:                     25.13
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00246
Time:                        17:22:55   Log-Likelihood:                 6.1097
No. Observations:                   8   AIC:                            -6.219
Df Residuals:                       5   BIC:                            -5.981
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     29.6771     67.433      0.440      0.660    -102.490     161.844
Boudin        -0.6041      0.226     -2.677      0.007      -1.046      -0.162
Year          -0.0113      0.033     -0.338      0.736      -0.077       0.054
==============================================================================
Omnibus:                        0.115   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.944   Jarque-Bera (JB):                0.289
Skew:                           0.189   Prob(JB):                        0.865
Kurtosis:                       2.148   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [98]:
# Successful_Diversion Not Log Normalized
np.random.seed(29)
formula = "Successful_Diversion ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
================================================================================
Dep. Variable:     Successful_Diversion   R-squared:                       0.934
Model:                              GLS   Adj. R-squared:                  0.907
Method:                   Least Squares   F-statistic:                     46.51
Date:                  Thu, 28 Sep 2023   Prob (F-statistic):           0.000588
Time:                          17:23:03   Log-Likelihood:                -39.719
No. Observations:                     8   AIC:                             85.44
Df Residuals:                         5   BIC:                             85.68
Df Model:                             2
Covariance Type:                    HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1.034e+05   3.02e+04     -3.428      0.001   -1.62e+05   -4.43e+04
Boudin        29.8667     72.981      0.409      0.682    -113.174     172.907
Year          51.3333     14.953      3.433      0.001      22.027      80.640
==============================================================================
Omnibus:                        1.154   Durbin-Watson:                   1.323
Prob(Omnibus):                  0.562   Jarque-Bera (JB):                0.669
Skew:                           0.271   Prob(JB):                        0.716
Kurtosis:                       1.691   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [99]:
# Med_Arrest_To_Close Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                             GLS Regression Results
===============================================================================
Dep. Variable:     Med_Arrest_To_Close   R-squared:                       0.937
Model:                             GLS   Adj. R-squared:                  0.912
Method:                  Least Squares   F-statistic:                     26.58
Date:                 Thu, 28 Sep 2023   Prob (F-statistic):            0.00217
Time:                         17:23:19   Log-Likelihood:                -39.196
No. Observations:                    8   AIC:                             84.39
Df Residuals:                        5   BIC:                             84.63
Df Model:                            2
Covariance Type:                   HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -4.233e+04   1.63e+04     -2.604      0.009   -7.42e+04   -1.05e+04
Boudin       169.0667     47.498      3.559      0.000      75.973     262.161
Year          21.0833      8.061      2.615      0.009       5.284      36.883
==============================================================================
Omnibus:                        2.151   Durbin-Watson:                   3.153
Prob(Omnibus):                  0.341   Jarque-Bera (JB):                0.671
Skew:                           0.706   Prob(JB):                        0.715
Kurtosis:                       2.865   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [100]:
# Med_Arrest_To_Close_Conviction Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Conviction ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_no2023)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
==========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Conviction   R-squared:                       0.949
Model:                                        GLS   Adj. R-squared:                  0.929
Method:                             Least Squares   F-statistic:                     30.10
Date:                            Thu, 28 Sep 2023   Prob (F-statistic):            0.00163
Time:                                    17:23:28   Log-Likelihood:                -37.793
No. Observations:                               8   AIC:                             81.59
Df Residuals:                                   5   BIC:                             81.82
Df Model:                                       2
Covariance Type:                              HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -3.78e+04   1.33e+04     -2.848      0.004   -6.38e+04   -1.18e+04
Boudin       163.8667     28.290      5.792      0.000     108.420     219.314
Year          18.8333      6.580      2.862      0.004       5.937      31.729
==============================================================================
Omnibus:                        1.518   Durbin-Watson:                   2.561
Prob(Omnibus):                  0.468   Jarque-Bera (JB):                0.020
Skew:                           0.074   Prob(JB):                        0.990
Kurtosis:                       3.193   Cond. No.                     3.32e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 3.32e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [101]:
# 2023 Projected & Med_Arrest_To_Close_Dismissal Not Log Normalized
np.random.seed(29)
formula = "Med_Arrest_To_Close_Dismissal ~ Boudin + Year"
model = smf.gls(formula=formula, data=sf_cr_violent_proj)
result = model.fit(cov_type='HC1')
print(result.summary())

                                  GLS Regression Results
=========================================================================================
Dep. Variable:     Med_Arrest_To_Close_Dismissal   R-squared:                       0.858
Model:                                       GLS   Adj. R-squared:                  0.811
Method:                            Least Squares   F-statistic:                     21.74
Date:                           Thu, 28 Sep 2023   Prob (F-statistic):            0.00178
Time:                                   17:23:35   Log-Likelihood:                -45.275
No. Observations:                              9   AIC:                             96.55
Df Residuals:                                  6   BIC:                             97.14
Df Model:                                      2
Covariance Type:                             HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -5.919e+04   1.33e+04     -4.450      0.000   -8.53e+04   -3.31e+04
Boudin        50.3810     37.736      1.335      0.182     -23.580     124.342
Year          29.4286      6.591      4.465      0.000      16.510      42.347
==============================================================================
Omnibus:                        1.186   Durbin-Watson:                   1.205
Prob(Omnibus):                  0.553   Jarque-Bera (JB):                0.767
Skew:                          -0.381   Prob(JB):                        0.681
Kurtosis:                       1.789   Cond. No.                     1.89e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 1.89e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [102]:
# Total Log Normalized
np.random.seed(29)
formula = "Log_Total ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:              Log_Total   R-squared:                       0.967
Model:                            GLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                     105.6
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00143
Time:                        17:23:44   Log-Likelihood:                 17.813
No. Observations:                   9   AIC:                            -23.63
Df Residuals:                       3   BIC:                            -22.44
Df Model:                           5
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -198.0056     42.667     -4.641      0.000    -281.632    -114.379
Boudin                             0.1171      0.028      4.205      0.000       0.063       0.172
Year                               0.1022      0.021      4.826      0.000       0.061       0.144
Med_Arrest_To_Close                0.0101      0.002      5.757      0.000       0.007       0.014
Med_Arrest_To_Close_Conviction    -0.0099      0.002     -5.766      0.000      -0.013      -0.007
Med_Arrest_To_Close_Dismissal     -0.0057      0.001     -7.357      0.000      -0.007      -0.004
==============================================================================
Omnibus:                        4.205   Durbin-Watson:                   2.849
Prob(Omnibus):                  0.122   Jarque-Bera (JB):                1.101
Skew:                          -0.797   Prob(JB):                        0.577
Kurtosis:                       3.630   Cond. No.                     5.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

In [103]:
# Conviction Log Normalized
np.random.seed(29)
formula = "Log_Conviction ~ Boudin + Year + Med_Arrest_To_Close + Med_Arrest_To_Close_Conviction + Med_Arrest_To_Close_Dismissal"
model = smf.gls(formula=formula, data=sf_cr_violent)
result = model.fit(cov_type='HC1')
print(result.summary())

                            GLS Regression Results
==============================================================================
Dep. Variable:         Log_Conviction   R-squared:                       0.989
Model:                            GLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     103.0
Date:                Thu, 28 Sep 2023   Prob (F-statistic):            0.00149
Time:                        17:23:55   Log-Likelihood:                 16.323
No. Observations:                   9   AIC:                            -20.65
Df Residuals:                       3   BIC:                            -19.46
Df Model:                           5
Covariance Type:                  HC1
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -134.1947     57.999     -2.314      0.021    -247.870     -20.519
Boudin                             0.2243      0.050      4.457      0.000       0.126       0.323
Year                               0.0705      0.029      2.445      0.014       0.014       0.127
Med_Arrest_To_Close                0.0113      0.003      4.108      0.000       0.006       0.017
Med_Arrest_To_Close_Conviction    -0.0121      0.003     -4.604      0.000      -0.017      -0.007
Med_Arrest_To_Close_Dismissal     -0.0065      0.001     -6.290      0.000      -0.009      -0.004
==============================================================================
Omnibus:                        2.440   Durbin-Watson:                   2.096
Prob(Omnibus):                  0.295   Jarque-Bera (JB):                0.893
Skew:                           0.194   Prob(JB):                        0.640
Kurtosis:                       1.507   Cond. No.                     5.33e+06
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
[2] The condition number is large, 5.33e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

# Part III